# pylint: skip-file
# mypy: ignore-errors
# pyright: reportInvalidTypeForm=false, reportAttributeAccessIssue=false
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'public/settings.proto')
_sym_db = _symbol_database.Default()
from .. import auth_pb2 as auth__pb2
from ..google.api import visibility_pb2 as google_dot_api_dot_visibility__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from .. import paradigm_params_pb2 as paradigm__params__pb2
from ..public import chat_pb2 as public_dot_chat__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15public/settings.proto\x12\x1atextql.rpc.public.settings\x1a\nauth.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x15paradigm_params.proto\x1a\x11public/chat.proto"\xf15\n!UpdateOrganizationSettingsRequest\x12\x15\n\x06org_id\x18\x01 \x01(\tR\x05orgId\x12B\n\x11organization_name\x18\x02 \x01(\tB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALH\x00R\x10organizationName\x88\x01\x01\x12W\n\x10require_attached\x18\x03 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0frequireAttached\x12|\n$inject_whole_ontology_disable_search\x18\x04 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR injectWholeOntologyDisableSearch\x12U\n\x0fsecrets_enabled\x18\x05 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0esecretsEnabled\x12`\n\x15email_polling_enabled\x18\x06 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x13emailPollingEnabled\x12S\n\x0edisable_emojis\x18\x07 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\rdisableEmojis\x12H\n\x07warning\x18\x08 \x01(\x0b2\x1c.google.protobuf.StringValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x07warning\x12T\n\x0fchat_v5_cutover\x18\t \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\rchatV5Cutover\x12S\n\x0epublic_preview\x18\n \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\rpublicPreview\x12S\n\x0econsole_access\x18\x0c \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\rconsoleAccess\x12M\n\nbrand_name\x18\r \x01(\x0b2\x1c.google.protobuf.StringValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\tbrandName\x12Y\n\x11default_llm_model\x18\x0e \x01(\x0b2\x1b.google.protobuf.Int32ValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0fdefaultLlmModel\x12]\n\x12preferred_provider\x18\x0f \x01(\x0b2\x1c.google.protobuf.StringValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x11preferredProvider\x12R\n\x17hide_example_connectors\x18\x10 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x15hideExampleConnectors\x12X\n\x0fparadigm_params\x18\x11 \x01(\x0b2*.textql.rpc.paradigm_params.ParadigmParamsH\x01R\x0eparadigmParams\x88\x01\x01\x12s\n\x15default_paradigm_mode\x18\x12 \x01(\x0e2(.textql.rpc.paradigm_params.ParadigmTypeB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALH\x02R\x13defaultParadigmMode\x88\x01\x01\x12D\n\x15default_connector_ids\x18\x13 \x03(\x05B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x13defaultConnectorIds\x12K\n\x19add_allowed_email_domains\x18\x14 \x03(\tB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x16addAllowedEmailDomains\x12Q\n\x1cremove_allowed_email_domains\x18\x15 \x03(\tB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x19removeAllowedEmailDomains\x12?\n\rtraining_mode\x18\x16 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x0ctrainingMode\x12I\n\x12dashboards_enabled\x18\x17 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x11dashboardsEnabled\x12X\n\x10billing_admin_id\x18\x18 \x01(\x0b2\x1c.google.protobuf.StringValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0ebillingAdminId\x12K\n\x13methodology_enabled\x18\x19 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x12methodologyEnabled\x12]\n\x14allow_all_api_access\x18\x1a \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x11allowAllApiAccess\x12=\n\x0cfeed_enabled\x18\x1b \x01(\x0b2\x1a.google.protobuf.BoolValueR\x0bfeedEnabled\x12Z\n\x12context_v3_enabled\x18\x1c \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x10contextV3Enabled\x12O\n\x0cbash_enabled\x18\x1d \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0bbashEnabled\x12d\n\x17default_routing_enabled\x18\x1e \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x15defaultRoutingEnabled\x12<\n\x11enabled_model_ids\x18\x1f \x03(\x05B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0fenabledModelIds\x12B\n\x14restricted_model_ids\x18  \x03(\x05B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x12restrictedModelIds\x12A\n\x13restricted_families\x18! \x03(\tB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x12restrictedFamilies\x12G\n\x17clear_enabled_model_ids\x18" \x01(\x08B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x14clearEnabledModelIds\x12M\n\x1aclear_restricted_model_ids\x18# \x01(\x08B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x17clearRestrictedModelIds\x12L\n\x19clear_restricted_families\x18$ \x01(\x08B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x17clearRestrictedFamilies\x12P\n\x0cdiscoverable\x18% \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0cdiscoverable\x12O\n\x15observability_enabled\x18\' \x01(\x0b2\x1a.google.protobuf.BoolValueR\x14observabilityEnabled\x12O\n\x15notifications_enabled\x18( \x01(\x0b2\x1a.google.protobuf.BoolValueR\x14notificationsEnabled\x12i\n\x1aclient_db_override_enabled\x18* \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x17clientDbOverrideEnabled\x12d\n\x17context_review_required\x18+ \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x15contextReviewRequired\x12f\n\x18google_connector_enabled\x18, \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x16googleConnectorEnabled\x126\n\x0eclear_logo_url\x18- \x01(\x08B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0cclearLogoUrl\x12\\\n\x13hide_api_connectors\x18. \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x11hideApiConnectors\x12F\n\x11fast_mode_enabled\x18/ \x01(\x0b2\x1a.google.protobuf.BoolValueR\x0ffastModeEnabled\x12L\n\x14max_thinking_enabled\x18L \x01(\x0b2\x1a.google.protobuf.BoolValueR\x12maxThinkingEnabled\x12O\n\x1bclear_default_connector_ids\x180 \x01(\x08B\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x18clearDefaultConnectorIds\x12n\n\x1csandbox_state_retention_days\x181 \x01(\x0b2\x1b.google.protobuf.Int32ValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x19sandboxStateRetentionDays\x12m\n\x1csandbox_lease_config_enabled\x18S \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x19sandboxLeaseConfigEnabled\x12`\n\x10asset_url_expiry\x18D \x01(\x0e2\x1f.textql.rpc.auth.AssetUrlExpiryB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALH\x03R\x0eassetUrlExpiry\x88\x01\x01\x12^\n\x14email_output_enabled\x182 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x12emailOutputEnabled\x12f\n\x18default_playbook_private\x183 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x16defaultPlaybookPrivate\x12f\n\x18default_dashboard_output\x185 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x16defaultDashboardOutput\x12k\n\x13default_methodology\x18C \x01(\x0e2#.textql.rpc.public.chat.MethodologyB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALH\x04R\x12defaultMethodology\x88\x01\x01\x12u\n scim_new_group_default_role_type\x186 \x01(\x0b2\x1c.google.protobuf.StringValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x1bscimNewGroupDefaultRoleType\x12b\n\x16groups_feature_enabled\x187 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x14groupsFeatureEnabled\x12X\n\x11show_textql_usage\x188 \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0fshowTextqlUsage\x12A\n\x0etraces_enabled\x189 \x01(\x0b2\x1a.google.protobuf.BoolValueR\rtracesEnabled\x12e\n\x18allow_llm_data_retention\x18: \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x15allowLlmDataRetention\x12r\n\x1fsox_db_session_metadata_enabled\x18; \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x1bsoxDbSessionMetadataEnabled\x12M\n\x0bsms_enabled\x18= \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\nsmsEnabled\x12e\n\x18scim_assign_default_role\x18> \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x15scimAssignDefaultRole\x12j\n\x1amigration_banner_dismissed\x18? \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x18migrationBannerDismissed\x12j\n\x19config_migrations_enabled\x18@ \x01(\x0b2\x1a.google.protobuf.BoolValueB\x12\x18\x01\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x17configMigrationsEnabled\x12^\n\x1dsandbox_observability_enabled\x18A \x01(\x0b2\x1a.google.protobuf.BoolValueR\x1bsandboxObservabilityEnabled\x12F\n\x11data_apps_enabled\x18B \x01(\x0b2\x1a.google.protobuf.BoolValueR\x0fdataAppsEnabled\x12S\n\x0eissues_enabled\x18E \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\rissuesEnabled\x12b\n\x16config_objects_enabled\x18F \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x14configObjectsEnabled\x12u\n config_objects_playbooks_enabled\x18G \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x1dconfigObjectsPlaybooksEnabled\x12w\n!config_objects_dashboards_enabled\x18H \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x1econfigObjectsDashboardsEnabled\x12b\n\x16config_autofix_enabled\x18I \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x14configAutofixEnabled\x12j\n\x1aspend_transparency_enabled\x18J \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x18spendTransparencyEnabled\x12W\n\x10sharing_disabled\x18K \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0fsharingDisabled\x12x\n"app_writeback_auto_approve_enabled\x18N \x01(\x0b2\x1a.google.protobuf.BoolValueB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x1eappWritebackAutoApproveEnabled\x12\\\n\x11tool_restrictions\x18T \x01(\x0b2*.textql.rpc.paradigm_params.ParadigmParamsH\x05R\x10toolRestrictions\x88\x01\x01\x12G\n\x11subagents_enabled\x18M \x01(\x0b2\x1a.google.protobuf.BoolValueR\x10subagentsEnabledB\x14\n\x12_organization_nameB\x12\n\x10_paradigm_paramsB\x18\n\x16_default_paradigm_modeB\x13\n\x11_asset_url_expiryB\x16\n\x14_default_methodologyB\x14\n\x12_tool_restrictionsJ\x04\x08\x0b\x10\x0cJ\x04\x08&\x10\'J\x04\x084\x105J\x04\x08<\x10="y\n"UpdateOrganizationSettingsResponse\x12S\n\x0corganization\x18\x01 \x01(\x0b2\x1d.textql.rpc.auth.OrganizationB\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALR\x0corganization"7\n\x1eListOrganizationMembersRequest\x12\x15\n\x06org_id\x18\x01 \x01(\tR\x05orgId"T\n\x1fListOrganizationMembersResponse\x121\n\x07members\x18\x01 \x03(\x0b2\x17.textql.rpc.auth.MemberR\x07members"p\n\x1fInviteOrganizationMemberRequest\x12\x15\n\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n\x04role\x18\x03 \x01(\tH\x00R\x04role\x88\x01\x01B\x07\n\x05_role"<\n InviteOrganizationMemberResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success"v\n\x1fDeleteOrganizationMemberRequest\x12\x15\n\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n\tmember_id\x18\x02 \x01(\tR\x08memberId\x12\x1f\n\x0bhard_delete\x18\x03 \x01(\x08R\nhardDelete"<\n DeleteOrganizationMemberResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success"2\n\x19DeleteOrganizationRequest\x12\x15\n\x06org_id\x18\x01 \x01(\tR\x05orgId"6\n\x1aDeleteOrganizationResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success"\xb2\x02\n!UpdateCurrentMemberProfileRequest\x12N\n\x14preferred_first_name\x18\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x12preferredFirstName\x12L\n\x13preferred_last_name\x18\x02 \x01(\x0b2\x1c.google.protobuf.StringValueR\x11preferredLastName\x127\n\tshow_code\x18\x03 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x08showCode\x126\n\x08steering\x18\x04 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x08steering"U\n"UpdateCurrentMemberProfileResponse\x12/\n\x06member\x18\x01 \x01(\x0b2\x17.textql.rpc.auth.MemberR\x06member"?\n\x18CheckMemberStatusRequest\x12#\n\rforce_refresh\x18\x01 \x01(\x08R\x0cforceRefresh"\xdd\x03\n\x19CheckMemberStatusResponse\x12!\n\x0cis_suspended\x18\x01 \x01(\x08R\x0bisSuspended\x12%\n\x0econsole_access\x18\x03 \x01(\x08R\rconsoleAccess\x12.\n\x13is_suspended_manual\x18\x04 \x01(\x08R\x11isSuspendedManual\x120\n\x14is_suspended_overage\x18\x05 \x01(\x08R\x12isSuspendedOverage\x12,\n\x12is_suspended_usage\x18\x06 \x01(\x08R\x10isSuspendedUsage\x129\n\x19is_suspended_member_usage\x18\x07 \x01(\x08R\x16isSuspendedMemberUsage\x12-\n\x12suspension_message\x18\x08 \x01(\tR\x11suspensionMessage\x124\n\x16suspended_cost_centers\x18\t \x03(\tR\x14suspendedCostCenters\x123\n\x16is_suspended_org_limit\x18\n \x01(\x08R\x13isSuspendedOrgLimitJ\x04\x08\x02\x10\x03R\x0bacu_balance"\xfb\x01\n\x14ModelDeprecationInfo\x12)\n\x10deprecated_model\x18\x01 \x01(\x05R\x0fdeprecatedModel\x12\'\n\x0fsuccessor_model\x18\x02 \x01(\x05R\x0esuccessorModel\x122\n\x15deprecated_model_name\x18\x03 \x01(\tR\x13deprecatedModelName\x120\n\x14successor_model_name\x18\x04 \x01(\tR\x12successorModelName\x12)\n\x10deprecation_date\x18\x05 \x01(\tR\x0fdeprecationDate"\x1d\n\x1bGetModelDeprecationsRequest"t\n\x1cGetModelDeprecationsResponse\x12T\n\x0cdeprecations\x18\x01 \x03(\x0b20.textql.rpc.public.settings.ModelDeprecationInfoR\x0cdeprecations2\xdf\t\n\x0fSettingsService\x12\x9b\x01\n\x1aUpdateOrganizationSettings\x12=.textql.rpc.public.settings.UpdateOrganizationSettingsRequest\x1a>.textql.rpc.public.settings.UpdateOrganizationSettingsResponse\x12\x94\x01\n\x17ListOrganizationMembers\x12:.textql.rpc.public.settings.ListOrganizationMembersRequest\x1a;.textql.rpc.public.settings.ListOrganizationMembersResponse"\x00\x12\x95\x01\n\x18InviteOrganizationMember\x12;.textql.rpc.public.settings.InviteOrganizationMemberRequest\x1a<.textql.rpc.public.settings.InviteOrganizationMemberResponse\x12\x95\x01\n\x18DeleteOrganizationMember\x12;.textql.rpc.public.settings.DeleteOrganizationMemberRequest\x1a<.textql.rpc.public.settings.DeleteOrganizationMemberResponse\x12\x95\x01\n\x12DeleteOrganization\x125.textql.rpc.public.settings.DeleteOrganizationRequest\x1a6.textql.rpc.public.settings.DeleteOrganizationResponse"\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL\x12\xad\x01\n\x1aUpdateCurrentMemberProfile\x12=.textql.rpc.public.settings.UpdateCurrentMemberProfileRequest\x1a>.textql.rpc.public.settings.UpdateCurrentMemberProfileResponse"\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL\x12\x80\x01\n\x11CheckMemberStatus\x124.textql.rpc.public.settings.CheckMemberStatusRequest\x1a5.textql.rpc.public.settings.CheckMemberStatusResponse\x12\x9b\x01\n\x14GetModelDeprecations\x127.textql.rpc.public.settings.GetModelDeprecationsRequest\x1a8.textql.rpc.public.settings.GetModelDeprecationsResponse"\x10\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNALb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['organization_name']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['organization_name']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['require_attached']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['require_attached']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['inject_whole_ontology_disable_search']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['inject_whole_ontology_disable_search']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['secrets_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['secrets_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['email_polling_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['email_polling_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['disable_emojis']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['disable_emojis']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['warning']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['warning']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['chat_v5_cutover']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['chat_v5_cutover']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['public_preview']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['public_preview']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['console_access']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['console_access']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['brand_name']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['brand_name']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_llm_model']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_llm_model']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['preferred_provider']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['preferred_provider']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_paradigm_mode']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_paradigm_mode']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_connector_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_connector_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['add_allowed_email_domains']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['add_allowed_email_domains']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['remove_allowed_email_domains']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['remove_allowed_email_domains']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['billing_admin_id']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['billing_admin_id']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['allow_all_api_access']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['allow_all_api_access']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['context_v3_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['context_v3_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['bash_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['bash_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_routing_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_routing_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['enabled_model_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['enabled_model_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['restricted_model_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['restricted_model_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['restricted_families']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['restricted_families']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_enabled_model_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_enabled_model_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_restricted_model_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_restricted_model_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_restricted_families']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_restricted_families']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['discoverable']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['discoverable']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['client_db_override_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['client_db_override_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['context_review_required']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['context_review_required']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['google_connector_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['google_connector_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_logo_url']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_logo_url']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['hide_api_connectors']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['hide_api_connectors']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_default_connector_ids']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['clear_default_connector_ids']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sandbox_state_retention_days']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sandbox_state_retention_days']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sandbox_lease_config_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sandbox_lease_config_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['asset_url_expiry']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['asset_url_expiry']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['email_output_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['email_output_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_playbook_private']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_playbook_private']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_dashboard_output']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_dashboard_output']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_methodology']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['default_methodology']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['scim_new_group_default_role_type']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['scim_new_group_default_role_type']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['groups_feature_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['groups_feature_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['show_textql_usage']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['show_textql_usage']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['allow_llm_data_retention']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['allow_llm_data_retention']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sox_db_session_metadata_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sox_db_session_metadata_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sms_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sms_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['scim_assign_default_role']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['scim_assign_default_role']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['migration_banner_dismissed']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['migration_banner_dismissed']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_migrations_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_migrations_enabled']._serialized_options = b'\x18\x01\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['issues_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['issues_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_playbooks_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_playbooks_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_dashboards_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_objects_dashboards_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_autofix_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['config_autofix_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['spend_transparency_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['spend_transparency_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sharing_disabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['sharing_disabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['app_writeback_auto_approve_enabled']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST'].fields_by_name['app_writeback_auto_approve_enabled']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSRESPONSE'].fields_by_name['organization']._loaded_options = None
    _globals['_UPDATEORGANIZATIONSETTINGSRESPONSE'].fields_by_name['organization']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_SETTINGSSERVICE'].methods_by_name['DeleteOrganization']._loaded_options = None
    _globals['_SETTINGSSERVICE'].methods_by_name['DeleteOrganization']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_SETTINGSSERVICE'].methods_by_name['UpdateCurrentMemberProfile']._loaded_options = None
    _globals['_SETTINGSSERVICE'].methods_by_name['UpdateCurrentMemberProfile']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_SETTINGSSERVICE'].methods_by_name['GetModelDeprecations']._loaded_options = None
    _globals['_SETTINGSSERVICE'].methods_by_name['GetModelDeprecations']._serialized_options = b'\xfa\xd2\xe4\x93\x02\n\x12\x08INTERNAL'
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST']._serialized_start = 169
    _globals['_UPDATEORGANIZATIONSETTINGSREQUEST']._serialized_end = 7066
    _globals['_UPDATEORGANIZATIONSETTINGSRESPONSE']._serialized_start = 7068
    _globals['_UPDATEORGANIZATIONSETTINGSRESPONSE']._serialized_end = 7189
    _globals['_LISTORGANIZATIONMEMBERSREQUEST']._serialized_start = 7191
    _globals['_LISTORGANIZATIONMEMBERSREQUEST']._serialized_end = 7246
    _globals['_LISTORGANIZATIONMEMBERSRESPONSE']._serialized_start = 7248
    _globals['_LISTORGANIZATIONMEMBERSRESPONSE']._serialized_end = 7332
    _globals['_INVITEORGANIZATIONMEMBERREQUEST']._serialized_start = 7334
    _globals['_INVITEORGANIZATIONMEMBERREQUEST']._serialized_end = 7446
    _globals['_INVITEORGANIZATIONMEMBERRESPONSE']._serialized_start = 7448
    _globals['_INVITEORGANIZATIONMEMBERRESPONSE']._serialized_end = 7508
    _globals['_DELETEORGANIZATIONMEMBERREQUEST']._serialized_start = 7510
    _globals['_DELETEORGANIZATIONMEMBERREQUEST']._serialized_end = 7628
    _globals['_DELETEORGANIZATIONMEMBERRESPONSE']._serialized_start = 7630
    _globals['_DELETEORGANIZATIONMEMBERRESPONSE']._serialized_end = 7690
    _globals['_DELETEORGANIZATIONREQUEST']._serialized_start = 7692
    _globals['_DELETEORGANIZATIONREQUEST']._serialized_end = 7742
    _globals['_DELETEORGANIZATIONRESPONSE']._serialized_start = 7744
    _globals['_DELETEORGANIZATIONRESPONSE']._serialized_end = 7798
    _globals['_UPDATECURRENTMEMBERPROFILEREQUEST']._serialized_start = 7801
    _globals['_UPDATECURRENTMEMBERPROFILEREQUEST']._serialized_end = 8107
    _globals['_UPDATECURRENTMEMBERPROFILERESPONSE']._serialized_start = 8109
    _globals['_UPDATECURRENTMEMBERPROFILERESPONSE']._serialized_end = 8194
    _globals['_CHECKMEMBERSTATUSREQUEST']._serialized_start = 8196
    _globals['_CHECKMEMBERSTATUSREQUEST']._serialized_end = 8259
    _globals['_CHECKMEMBERSTATUSRESPONSE']._serialized_start = 8262
    _globals['_CHECKMEMBERSTATUSRESPONSE']._serialized_end = 8739
    _globals['_MODELDEPRECATIONINFO']._serialized_start = 8742
    _globals['_MODELDEPRECATIONINFO']._serialized_end = 8993
    _globals['_GETMODELDEPRECATIONSREQUEST']._serialized_start = 8995
    _globals['_GETMODELDEPRECATIONSREQUEST']._serialized_end = 9024
    _globals['_GETMODELDEPRECATIONSRESPONSE']._serialized_start = 9026
    _globals['_GETMODELDEPRECATIONSRESPONSE']._serialized_end = 9142
    _globals['_SETTINGSSERVICE']._serialized_start = 9145
    _globals['_SETTINGSSERVICE']._serialized_end = 10392