"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from textql_sdk import errors, models, utils
from textql_sdk._hooks import HookContext
from textql_sdk.types import OptionalNullable, UNSET
from textql_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional, Union


class AppServices(BaseSDK):
    def create_app(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        name: Optional[str] = None,
        description: OptionalNullable[str] = UNSET,
        code: Optional[str] = None,
        data_sources: Optional[
            Union[
                Iterable[models.TextqlRPCPublicDashboardDataSource],
                Iterable[models.TextqlRPCPublicDashboardDataSourceTypedDict],
            ]
        ] = None,
        compute_functions: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppComputeFunction],
                Iterable[models.TextqlRPCPublicAppComputeFunctionTypedDict],
            ]
        ] = None,
        files: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppAppFile],
                Iterable[models.TextqlRPCPublicAppAppFileTypedDict],
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceCreateAppResponse:
        r"""CreateApp

        :param connect_timeout_ms:
        :param name:
        :param description:
        :param code:
        :param data_sources:
        :param compute_functions:
        :param files:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceCreateAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppCreateAppRequest(
                name=name,
                description=description,
                code=code,
                data_sources=utils.get_pydantic_model(
                    data_sources,
                    Optional[List[models.TextqlRPCPublicDashboardDataSource]],
                ),
                compute_functions=utils.get_pydantic_model(
                    compute_functions,
                    Optional[List[models.TextqlRPCPublicAppComputeFunction]],
                ),
                files=utils.get_pydantic_model(
                    files, Optional[List[models.TextqlRPCPublicAppAppFile]]
                ),
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.app.AppService/CreateApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppCreateAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_CreateApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppCreateAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def create_app_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        name: Optional[str] = None,
        description: OptionalNullable[str] = UNSET,
        code: Optional[str] = None,
        data_sources: Optional[
            Union[
                Iterable[models.TextqlRPCPublicDashboardDataSource],
                Iterable[models.TextqlRPCPublicDashboardDataSourceTypedDict],
            ]
        ] = None,
        compute_functions: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppComputeFunction],
                Iterable[models.TextqlRPCPublicAppComputeFunctionTypedDict],
            ]
        ] = None,
        files: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppAppFile],
                Iterable[models.TextqlRPCPublicAppAppFileTypedDict],
            ]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceCreateAppResponse:
        r"""CreateApp

        :param connect_timeout_ms:
        :param name:
        :param description:
        :param code:
        :param data_sources:
        :param compute_functions:
        :param files:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceCreateAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppCreateAppRequest(
                name=name,
                description=description,
                code=code,
                data_sources=utils.get_pydantic_model(
                    data_sources,
                    Optional[List[models.TextqlRPCPublicDashboardDataSource]],
                ),
                compute_functions=utils.get_pydantic_model(
                    compute_functions,
                    Optional[List[models.TextqlRPCPublicAppComputeFunction]],
                ),
                files=utils.get_pydantic_model(
                    files, Optional[List[models.TextqlRPCPublicAppAppFile]]
                ),
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.app.AppService/CreateApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppCreateAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_CreateApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppCreateAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def delete_app(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceDeleteAppResponse:
        r"""DeleteApp

        :param connect_timeout_ms:
        :param app_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceDeleteAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppDeleteAppRequest(
                app_id=app_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.app.AppService/DeleteApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppDeleteAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_DeleteApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleProtobufEmpty, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def delete_app_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceDeleteAppResponse:
        r"""DeleteApp

        :param connect_timeout_ms:
        :param app_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceDeleteAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppDeleteAppRequest(
                app_id=app_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.app.AppService/DeleteApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppDeleteAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_DeleteApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleProtobufEmpty, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def refresh(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceRefreshAppResponse:
        r"""Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.

        Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.

        :param connect_timeout_ms:
        :param app_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceRefreshAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppRefreshAppRequest(
                app_id=app_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.app.AppService/RefreshApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppRefreshAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_RefreshApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppRefreshAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def refresh_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceRefreshAppResponse:
        r"""Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.

        Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.

        :param connect_timeout_ms:
        :param app_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceRefreshAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppRefreshAppRequest(
                app_id=app_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.app.AppService/RefreshApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppRefreshAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_RefreshApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppRefreshAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def update(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        name: OptionalNullable[str] = UNSET,
        description: OptionalNullable[str] = UNSET,
        code: OptionalNullable[str] = UNSET,
        data_sources: Optional[
            Union[
                Iterable[models.TextqlRPCPublicDashboardDataSource],
                Iterable[models.TextqlRPCPublicDashboardDataSourceTypedDict],
            ]
        ] = None,
        replace_data_sources: OptionalNullable[bool] = UNSET,
        publish: OptionalNullable[bool] = UNSET,
        staleness_seconds: OptionalNullable[int] = UNSET,
        compute_functions: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppComputeFunction],
                Iterable[models.TextqlRPCPublicAppComputeFunctionTypedDict],
            ]
        ] = None,
        replace_compute_functions: OptionalNullable[bool] = UNSET,
        files: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppAppFile],
                Iterable[models.TextqlRPCPublicAppAppFileTypedDict],
            ]
        ] = None,
        replace_files: OptionalNullable[bool] = UNSET,
        schedule_enabled: OptionalNullable[bool] = UNSET,
        cron_string: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceUpdateAppResponse:
        r"""UpdateApp

        :param connect_timeout_ms:
        :param app_id:
        :param name:
        :param description:
        :param code:
        :param data_sources:
        :param replace_data_sources:
        :param publish:
        :param staleness_seconds:
        :param compute_functions:
        :param replace_compute_functions:
        :param files:
        :param replace_files:
        :param schedule_enabled:
        :param cron_string:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceUpdateAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppUpdateAppRequest(
                app_id=app_id,
                name=name,
                description=description,
                code=code,
                data_sources=utils.get_pydantic_model(
                    data_sources,
                    Optional[List[models.TextqlRPCPublicDashboardDataSource]],
                ),
                replace_data_sources=replace_data_sources,
                publish=publish,
                staleness_seconds=staleness_seconds,
                compute_functions=utils.get_pydantic_model(
                    compute_functions,
                    Optional[List[models.TextqlRPCPublicAppComputeFunction]],
                ),
                replace_compute_functions=replace_compute_functions,
                files=utils.get_pydantic_model(
                    files, Optional[List[models.TextqlRPCPublicAppAppFile]]
                ),
                replace_files=replace_files,
                schedule_enabled=schedule_enabled,
                cron_string=cron_string,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.app.AppService/UpdateApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppUpdateAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_UpdateApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppUpdateAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def update_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        app_id: Optional[str] = None,
        name: OptionalNullable[str] = UNSET,
        description: OptionalNullable[str] = UNSET,
        code: OptionalNullable[str] = UNSET,
        data_sources: Optional[
            Union[
                Iterable[models.TextqlRPCPublicDashboardDataSource],
                Iterable[models.TextqlRPCPublicDashboardDataSourceTypedDict],
            ]
        ] = None,
        replace_data_sources: OptionalNullable[bool] = UNSET,
        publish: OptionalNullable[bool] = UNSET,
        staleness_seconds: OptionalNullable[int] = UNSET,
        compute_functions: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppComputeFunction],
                Iterable[models.TextqlRPCPublicAppComputeFunctionTypedDict],
            ]
        ] = None,
        replace_compute_functions: OptionalNullable[bool] = UNSET,
        files: Optional[
            Union[
                Iterable[models.TextqlRPCPublicAppAppFile],
                Iterable[models.TextqlRPCPublicAppAppFileTypedDict],
            ]
        ] = None,
        replace_files: OptionalNullable[bool] = UNSET,
        schedule_enabled: OptionalNullable[bool] = UNSET,
        cron_string: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AppServiceUpdateAppResponse:
        r"""UpdateApp

        :param connect_timeout_ms:
        :param app_id:
        :param name:
        :param description:
        :param code:
        :param data_sources:
        :param replace_data_sources:
        :param publish:
        :param staleness_seconds:
        :param compute_functions:
        :param replace_compute_functions:
        :param files:
        :param replace_files:
        :param schedule_enabled:
        :param cron_string:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.AppServiceUpdateAppRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicAppUpdateAppRequest(
                app_id=app_id,
                name=name,
                description=description,
                code=code,
                data_sources=utils.get_pydantic_model(
                    data_sources,
                    Optional[List[models.TextqlRPCPublicDashboardDataSource]],
                ),
                replace_data_sources=replace_data_sources,
                publish=publish,
                staleness_seconds=staleness_seconds,
                compute_functions=utils.get_pydantic_model(
                    compute_functions,
                    Optional[List[models.TextqlRPCPublicAppComputeFunction]],
                ),
                replace_compute_functions=replace_compute_functions,
                files=utils.get_pydantic_model(
                    files, Optional[List[models.TextqlRPCPublicAppAppFile]]
                ),
                replace_files=replace_files,
                schedule_enabled=schedule_enabled,
                cron_string=cron_string,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.app.AppService/UpdateApp",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicAppUpdateAppRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AppService_UpdateApp",
                oauth2_scopes=None,
                security_source=None,
                tags=["AppService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicAppUpdateAppResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)
