"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from textql_sdk import errors, models, utils
from textql_sdk._hooks import HookContext
from textql_sdk.types import OptionalNullable, UNSET
from textql_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional, Union


class Dashboards(BaseSDK):
    def create_folder(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        name: Optional[str] = None,
        parent_id: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceCreateDashboardFolderResponse:
        r"""Folder management

        Folder management

        :param connect_timeout_ms:
        :param name:
        :param parent_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceCreateDashboardFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardCreateDashboardFolderRequest(
                name=name,
                parent_id=parent_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/CreateDashboardFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardCreateDashboardFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_CreateDashboardFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardCreateDashboardFolderResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def create_folder_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        name: Optional[str] = None,
        parent_id: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceCreateDashboardFolderResponse:
        r"""Folder management

        Folder management

        :param connect_timeout_ms:
        :param name:
        :param parent_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceCreateDashboardFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardCreateDashboardFolderRequest(
                name=name,
                parent_id=parent_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/CreateDashboardFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardCreateDashboardFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_CreateDashboardFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardCreateDashboardFolderResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def delete_folder(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        folder_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceDeleteDashboardFolderResponse:
        r"""DeleteDashboardFolder

        :param connect_timeout_ms:
        :param folder_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceDeleteDashboardFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardDeleteDashboardFolderRequest(
                folder_id=folder_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/DeleteDashboardFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardDeleteDashboardFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_DeleteDashboardFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleProtobufEmpty, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def delete_folder_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        folder_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceDeleteDashboardFolderResponse:
        r"""DeleteDashboardFolder

        :param connect_timeout_ms:
        :param folder_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceDeleteDashboardFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardDeleteDashboardFolderRequest(
                folder_id=folder_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/DeleteDashboardFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardDeleteDashboardFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_DeleteDashboardFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GoogleProtobufEmpty, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def duplicate(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        name: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceDuplicateDashboardResponse:
        r"""DuplicateDashboard

        :param connect_timeout_ms:
        :param dashboard_id:
        :param name: Optional new name for the duplicate (defaults to \"Copy of [original name]\")
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceDuplicateDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardDuplicateDashboardRequest(
                dashboard_id=dashboard_id,
                name=name,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/DuplicateDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardDuplicateDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_DuplicateDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardDuplicateDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def duplicate_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        name: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceDuplicateDashboardResponse:
        r"""DuplicateDashboard

        :param connect_timeout_ms:
        :param dashboard_id:
        :param name: Optional new name for the duplicate (defaults to \"Copy of [original name]\")
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceDuplicateDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardDuplicateDashboardRequest(
                dashboard_id=dashboard_id,
                name=name,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/DuplicateDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardDuplicateDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_DuplicateDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardDuplicateDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def list_folders(
        self,
        *,
        body: Union[
            models.TextqlRPCPublicDashboardListDashboardFoldersRequest,
            models.TextqlRPCPublicDashboardListDashboardFoldersRequestTypedDict,
        ],
        connect_timeout_ms: Optional[float] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceListDashboardFoldersResponse:
        r"""ListDashboardFolders

        :param body:
        :param connect_timeout_ms:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceListDashboardFoldersRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=utils.get_pydantic_model(
                body, models.TextqlRPCPublicDashboardListDashboardFoldersRequest
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/ListDashboardFolders",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardListDashboardFoldersRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_ListDashboardFolders",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardListDashboardFoldersResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def list_folders_async(
        self,
        *,
        body: Union[
            models.TextqlRPCPublicDashboardListDashboardFoldersRequest,
            models.TextqlRPCPublicDashboardListDashboardFoldersRequestTypedDict,
        ],
        connect_timeout_ms: Optional[float] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceListDashboardFoldersResponse:
        r"""ListDashboardFolders

        :param body:
        :param connect_timeout_ms:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceListDashboardFoldersRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=utils.get_pydantic_model(
                body, models.TextqlRPCPublicDashboardListDashboardFoldersRequest
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/ListDashboardFolders",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardListDashboardFoldersRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_ListDashboardFolders",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardListDashboardFoldersResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def list(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        search_term: OptionalNullable[str] = UNSET,
        my_dashboards_only: OptionalNullable[bool] = UNSET,
        sort_by: Optional[models.TextqlRPCPublicDashboardDashboardSortField] = None,
        sort_direction: Optional[models.TextqlRPCPublicCommonSortDirection] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        folder_id: OptionalNullable[str] = UNSET,
        uncategorized_only: OptionalNullable[bool] = UNSET,
        creator_member_id: OptionalNullable[str] = UNSET,
        shared_with_me: OptionalNullable[bool] = UNSET,
        creator_member_ids: Optional[Iterable[str]] = None,
        status_filter: Optional[models.TextqlRPCPublicDashboardDashboardStatus] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceListDashboardsResponse:
        r"""ListDashboards

        :param connect_timeout_ms:
        :param search_term:
        :param my_dashboards_only:
        :param sort_by:
        :param sort_direction: Common enum for sort direction used across multiple services
        :param limit:
        :param offset:
        :param folder_id: Filter by specific folder
        :param uncategorized_only: Only show dashboards with no folder
        :param creator_member_id: Filter by specific creator member ID (single-select; superseded by creator_member_ids when non-empty)
        :param shared_with_me:
        :param creator_member_ids: Multi-select creator filter (union). Supersedes creator_member_id when non-empty.
        :param status_filter:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceListDashboardsRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardListDashboardsRequest(
                search_term=search_term,
                my_dashboards_only=my_dashboards_only,
                sort_by=sort_by,
                sort_direction=sort_direction,
                limit=limit,
                offset=offset,
                folder_id=folder_id,
                uncategorized_only=uncategorized_only,
                creator_member_id=creator_member_id,
                shared_with_me=shared_with_me,
                creator_member_ids=utils.unmarshal(
                    creator_member_ids, Optional[List[str]]
                ),
                status_filter=status_filter,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/ListDashboards",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardListDashboardsRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_ListDashboards",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardListDashboardsResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def list_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        search_term: OptionalNullable[str] = UNSET,
        my_dashboards_only: OptionalNullable[bool] = UNSET,
        sort_by: Optional[models.TextqlRPCPublicDashboardDashboardSortField] = None,
        sort_direction: Optional[models.TextqlRPCPublicCommonSortDirection] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        folder_id: OptionalNullable[str] = UNSET,
        uncategorized_only: OptionalNullable[bool] = UNSET,
        creator_member_id: OptionalNullable[str] = UNSET,
        shared_with_me: OptionalNullable[bool] = UNSET,
        creator_member_ids: Optional[Iterable[str]] = None,
        status_filter: Optional[models.TextqlRPCPublicDashboardDashboardStatus] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceListDashboardsResponse:
        r"""ListDashboards

        :param connect_timeout_ms:
        :param search_term:
        :param my_dashboards_only:
        :param sort_by:
        :param sort_direction: Common enum for sort direction used across multiple services
        :param limit:
        :param offset:
        :param folder_id: Filter by specific folder
        :param uncategorized_only: Only show dashboards with no folder
        :param creator_member_id: Filter by specific creator member ID (single-select; superseded by creator_member_ids when non-empty)
        :param shared_with_me:
        :param creator_member_ids: Multi-select creator filter (union). Supersedes creator_member_id when non-empty.
        :param status_filter:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceListDashboardsRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardListDashboardsRequest(
                search_term=search_term,
                my_dashboards_only=my_dashboards_only,
                sort_by=sort_by,
                sort_direction=sort_direction,
                limit=limit,
                offset=offset,
                folder_id=folder_id,
                uncategorized_only=uncategorized_only,
                creator_member_id=creator_member_id,
                shared_with_me=shared_with_me,
                creator_member_ids=utils.unmarshal(
                    creator_member_ids, Optional[List[str]]
                ),
                status_filter=status_filter,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/ListDashboards",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardListDashboardsRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_ListDashboards",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardListDashboardsResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def move_to_folder(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        folder_id: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceMoveDashboardToFolderResponse:
        r"""MoveDashboardToFolder

        :param connect_timeout_ms:
        :param dashboard_id:
        :param folder_id: null/empty = move to root (uncategorized)
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceMoveDashboardToFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardMoveDashboardToFolderRequest(
                dashboard_id=dashboard_id,
                folder_id=folder_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/MoveDashboardToFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardMoveDashboardToFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_MoveDashboardToFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardMoveDashboardToFolderResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def move_to_folder_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        folder_id: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceMoveDashboardToFolderResponse:
        r"""MoveDashboardToFolder

        :param connect_timeout_ms:
        :param dashboard_id:
        :param folder_id: null/empty = move to root (uncategorized)
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceMoveDashboardToFolderRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardMoveDashboardToFolderRequest(
                dashboard_id=dashboard_id,
                folder_id=folder_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/MoveDashboardToFolder",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardMoveDashboardToFolderRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_MoveDashboardToFolder",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardMoveDashboardToFolderResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def publish(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        label: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServicePublishDashboardResponse:
        r"""Publishing workflow

        Publishing workflow

        :param connect_timeout_ms:
        :param dashboard_id:
        :param label: Optional version label/description
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServicePublishDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardPublishDashboardRequest(
                dashboard_id=dashboard_id,
                label=label,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/PublishDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardPublishDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_PublishDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardPublishDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def publish_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        label: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServicePublishDashboardResponse:
        r"""Publishing workflow

        Publishing workflow

        :param connect_timeout_ms:
        :param dashboard_id:
        :param label: Optional version label/description
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServicePublishDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardPublishDashboardRequest(
                dashboard_id=dashboard_id,
                label=label,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/PublishDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardPublishDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_PublishDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardPublishDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def regenerate_screenshot(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceRegenerateScreenshotResponse:
        r"""Screenshot management

        Screenshot management

        :param connect_timeout_ms:
        :param dashboard_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceRegenerateScreenshotRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardRegenerateScreenshotRequest(
                dashboard_id=dashboard_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/RegenerateScreenshot",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardRegenerateScreenshotRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_RegenerateScreenshot",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardRegenerateScreenshotResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def regenerate_screenshot_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceRegenerateScreenshotResponse:
        r"""Screenshot management

        Screenshot management

        :param connect_timeout_ms:
        :param dashboard_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceRegenerateScreenshotRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardRegenerateScreenshotRequest(
                dashboard_id=dashboard_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/RegenerateScreenshot",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardRegenerateScreenshotRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_RegenerateScreenshot",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardRegenerateScreenshotResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    def run_scheduled_dashboard(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceRunScheduledDashboardResponse:
        r"""RunScheduledDashboard

        :param connect_timeout_ms:
        :param dashboard_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceRunScheduledDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardRunScheduledDashboardRequest(
                dashboard_id=dashboard_id,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/RunScheduledDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardRunScheduledDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_RunScheduledDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardRunScheduledDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)

    async def run_scheduled_dashboard_async(
        self,
        *,
        connect_timeout_ms: Optional[float] = None,
        dashboard_id: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DashboardServiceRunScheduledDashboardResponse:
        r"""RunScheduledDashboard

        :param connect_timeout_ms:
        :param dashboard_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DashboardServiceRunScheduledDashboardRequest(
            connect_timeout_ms=connect_timeout_ms,
            body=models.TextqlRPCPublicDashboardRunScheduledDashboardRequest(
                dashboard_id=dashboard_id,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/textql.rpc.public.dashboard.DashboardService/RunScheduledDashboard",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body,
                False,
                False,
                "json",
                models.TextqlRPCPublicDashboardRunScheduledDashboardRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DashboardService_RunScheduledDashboard",
                oauth2_scopes=None,
                security_source=None,
                tags=["DashboardService"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.TextqlRPCPublicDashboardRunScheduledDashboardResponse, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.TextqlDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "default", "application/json"):
            return unmarshal_json_response(models.ConnectError, http_res)

        raise errors.TextqlDefaultError("Unexpected response received", http_res)
