"""Handwritten helpers — not generated by Speakeasy."""

from __future__ import annotations

from textql_sdk.models import (
    AnsCell,
    AppCell,
    BashCell,
    CompactionCell,
    ConnectorsCell,
    ContextPromptEditorCell,
    DashboardCell,
    DocumentCell,
    EmailCell,
    FeedCommentCell,
    FeedCreateCell,
    FeedEngageCell,
    FeedExplorerCell,
    FeedPostCell,
    FormCell,
    FormEditorCell,
    GmailEmailContentCell,
    GmailEmailSearchCell,
    GoogleCalendarSearchCell,
    GoogleDriveContentCell,
    GoogleDriveSearchCell,
    ImageCell,
    JavascriptCell,
    LinkedinSearchCell,
    ListAppsCell,
    ListDashboardsCell,
    ListUsersCell,
    McpToolCell,
    MdCell,
    MetricsCell,
    Microsoft365CalendarCell,
    Microsoft365EmailContentCell,
    Microsoft365EmailSearchCell,
    OntologyEditorCell,
    OntologyOpenObjectCell,
    OntologyQueryCell,
    OntologySearchMetricsCell,
    PatchCell,
    PlaybookEditorCell,
    PowerbiCell,
    PowerbiDaxCell,
    PreviewCell,
    PyCell,
    QuestionsCell,
    ReportCell,
    ReportHistoryCell,
    SQLCell,
    StatusCell,
    StreamlitCell,
    SummaryCell,
    TableauCell,
    TableauSearchFieldsCell,
    TableauSQLCell,
    TabularFileCell,
    TextCell,
    TextqlRPCPublicChatCell,
    UseSkillCell,
    WsCell,
)


def cell_text(cell: TextqlRPCPublicChatCell) -> tuple[str, str]:
    """Return ``(kind, text)`` for any cell variant in a chat history.

    ``kind`` is a short label (e.g. ``"md"``, ``"py"``, ``"report"``).
    ``text`` is the human-readable content, empty string for structural cells.
    """
    if isinstance(cell, PyCell):
        return "py", cell.py_cell.code or ""
    if isinstance(cell, BashCell):
        bash = cell.bash_cell
        return "bash", " | ".join(filter(None, [bash.script, bash.stdout, bash.stderr]))
    if isinstance(cell, SQLCell):
        return "sql", cell.sql_cell.query or ""
    if isinstance(cell, JavascriptCell):
        return "js", cell.javascript_cell.code or ""
    if isinstance(cell, StreamlitCell):
        return "streamlit", cell.streamlit_cell.code or ""
    if isinstance(cell, OntologyQueryCell):
        return "ontology_query", cell.ontology_query_cell.sql or ""
    if isinstance(cell, TableauSQLCell):
        return "tableau_sql", cell.tableau_sql_cell.query or ""
    if isinstance(cell, DashboardCell):
        dash = cell.dashboard_cell
        return "dashboard", f"{dash.name or ''} {dash.code or ''}".strip()
    if isinstance(cell, MdCell):
        return "md", cell.md_cell.content or ""
    if isinstance(cell, AnsCell):
        return "ans", cell.ans_cell.content or ""
    if isinstance(cell, TextCell):
        return "text", cell.text_cell.content or ""
    if isinstance(cell, CompactionCell):
        return "compaction", cell.compaction_cell.content or ""
    if isinstance(cell, FeedCommentCell):
        return "feed_comment", cell.feed_comment_cell.content or ""
    if isinstance(cell, FeedPostCell):
        fp = cell.feed_post_cell
        return "feed_post", f"{fp.title or ''}: {fp.content or ''}".strip(": ")
    if isinstance(cell, PreviewCell):
        prev = cell.preview_cell
        return "preview", f"{prev.name or ''}: {prev.content or ''}".strip(": ")
    if isinstance(cell, GoogleDriveContentCell):
        return "gdrive_content", cell.google_drive_content_cell.content or ""
    if isinstance(cell, McpToolCell):
        mcp = cell.mcp_tool_cell
        return "mcp", f"{mcp.tool_name or ''} {mcp.arguments_json or ''}".strip()
    if isinstance(cell, ReportCell):
        rpt = cell.report_cell
        return "report", f"{rpt.subject or ''} — {rpt.summary or ''}".strip(" —")
    if isinstance(cell, SummaryCell):
        return "summary", cell.summary_cell.summary or ""
    if isinstance(cell, PatchCell):
        patch = cell.patch_cell
        return "patch", f"{patch.title or ''}: {patch.description or ''}".strip(": ")
    if isinstance(cell, ReportHistoryCell):
        return "report_history", repr(cell.report_history_cell)
    if isinstance(cell, MetricsCell):
        return "metrics", cell.metrics_cell.query or ""
    if isinstance(cell, OntologySearchMetricsCell):
        return "ontology_search", cell.ontology_search_metrics_cell.query or ""
    if isinstance(cell, LinkedinSearchCell):
        return "linkedin_search", cell.linkedin_search_cell.query or ""
    if isinstance(cell, WsCell):
        return "web_search", cell.ws_cell.query or ""
    if isinstance(cell, EmailCell):
        email = cell.email_cell
        return "email", f"{email.subject or ''}: {email.body or ''}".strip(": ")
    if isinstance(cell, GmailEmailContentCell):
        return "gmail", cell.gmail_email_content_cell.subject or ""
    if isinstance(cell, Microsoft365EmailContentCell):
        return "m365_email", cell.microsoft365_email_content_cell.subject or ""
    if isinstance(cell, StatusCell):
        return "status", cell.status_cell.status or ""
    if isinstance(cell, AppCell):
        return "app", cell.app_cell.name or ""
    if isinstance(cell, DocumentCell):
        return "document", cell.document_cell.name or ""
    if isinstance(cell, ImageCell):
        return "image", cell.image_cell.name or ""
    if isinstance(cell, UseSkillCell):
        return "skill", cell.use_skill_cell.name or ""
    if isinstance(cell, FormCell):
        return "form", cell.form_cell.name or ""
    if isinstance(cell, (
        QuestionsCell, ConnectorsCell, ListAppsCell, ListDashboardsCell,
        ListUsersCell, OntologyEditorCell, OntologyOpenObjectCell,
        PowerbiCell, PowerbiDaxCell, TableauCell, TableauSearchFieldsCell,
        TabularFileCell, PlaybookEditorCell, ContextPromptEditorCell,
        FeedExplorerCell, FeedCreateCell, FeedEngageCell,
        GoogleCalendarSearchCell, GoogleDriveSearchCell, GmailEmailSearchCell,
        Microsoft365EmailSearchCell, Microsoft365CalendarCell, FormEditorCell,
    )):
        return type(cell).__name__.removesuffix("Cell").lower(), ""
    return "unknown", repr(cell)
