"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connect_error import ConnectError, ConnectErrorTypedDict
from .textql_rpc_public_audit_log_tests3exportconnectionrequest import (
    TextqlRPCPublicAuditLogTestS3ExportConnectionRequest,
    TextqlRPCPublicAuditLogTestS3ExportConnectionRequestTypedDict,
)
from .textql_rpc_public_audit_log_tests3exportconnectionresponse import (
    TextqlRPCPublicAuditLogTestS3ExportConnectionResponse,
    TextqlRPCPublicAuditLogTestS3ExportConnectionResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from textql_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    validate_const,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class AuditLogServiceTestS3ExportConnectionRequestTypedDict(TypedDict):
    body: TextqlRPCPublicAuditLogTestS3ExportConnectionRequestTypedDict
    connect_protocol_version: float
    connect_timeout_ms: NotRequired[float]


class AuditLogServiceTestS3ExportConnectionRequest(BaseModel):
    body: Annotated[
        TextqlRPCPublicAuditLogTestS3ExportConnectionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    connect_protocol_version: Annotated[
        Annotated[float, AfterValidator(validate_const(1))],
        pydantic.Field(alias="Connect-Protocol-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = 1

    connect_timeout_ms: Annotated[
        Optional[float],
        pydantic.Field(alias="Connect-Timeout-Ms"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Connect-Timeout-Ms"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


AuditLogServiceTestS3ExportConnectionResponseTypedDict = TypeAliasType(
    "AuditLogServiceTestS3ExportConnectionResponseTypedDict",
    Union[
        TextqlRPCPublicAuditLogTestS3ExportConnectionResponseTypedDict,
        ConnectErrorTypedDict,
    ],
)


AuditLogServiceTestS3ExportConnectionResponse = TypeAliasType(
    "AuditLogServiceTestS3ExportConnectionResponse",
    Union[TextqlRPCPublicAuditLogTestS3ExportConnectionResponse, ConnectError],
)


try:
    AuditLogServiceTestS3ExportConnectionRequest.model_rebuild()
except NameError:
    pass
