"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_connectorref import (
    TextqlRPCPublicCellsConnectorRef,
    TextqlRPCPublicCellsConnectorRefTypedDict,
)
from .textql_rpc_public_cells_feedagentaction import TextqlRPCPublicCellsFeedAgentAction
from .textql_rpc_public_cells_feedagentinfo import (
    TextqlRPCPublicCellsFeedAgentInfo,
    TextqlRPCPublicCellsFeedAgentInfoTypedDict,
)
from .textql_rpc_public_cells_fieldchange import (
    TextqlRPCPublicCellsFieldChange,
    TextqlRPCPublicCellsFieldChangeTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsFeedCreateCellTypedDict(TypedDict):
    action: NotRequired[TextqlRPCPublicCellsFeedAgentAction]
    agent: NotRequired[TextqlRPCPublicCellsFeedAgentInfoTypedDict]
    error_message: NotRequired[Nullable[str]]
    updated_fields: NotRequired[List[str]]
    field_changes: NotRequired[List[TextqlRPCPublicCellsFieldChangeTypedDict]]
    connectors: NotRequired[List[TextqlRPCPublicCellsConnectorRefTypedDict]]


class TextqlRPCPublicCellsFeedCreateCell(BaseModel):
    action: Optional[TextqlRPCPublicCellsFeedAgentAction] = None

    agent: Optional[TextqlRPCPublicCellsFeedAgentInfo] = None

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    updated_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="updatedFields")
    ] = None

    field_changes: Annotated[
        Optional[List[TextqlRPCPublicCellsFieldChange]],
        pydantic.Field(alias="fieldChanges"),
    ] = None

    connectors: Optional[List[TextqlRPCPublicCellsConnectorRef]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "agent",
                "errorMessage",
                "updatedFields",
                "fieldChanges",
                "connectors",
            ]
        )
        nullable_fields = set(["errorMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsFeedCreateCell.model_rebuild()
except NameError:
    pass
