"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicDashboardSQLQuerySourceTypedDict(TypedDict):
    query: NotRequired[str]
    connector_id: NotRequired[int]
    predicate: NotRequired[str]
    r"""Optional viewer row-filter appended server-side at live-query time; binds :viewer_member_id / :viewer_email. Presence forces the source out of the published snapshot."""


class TextqlRPCPublicDashboardSQLQuerySource(BaseModel):
    query: Optional[str] = None

    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    predicate: Optional[str] = None
    r"""Optional viewer row-filter appended server-side at live-query time; binds :viewer_member_id / :viewer_email. Presence forces the source out of the published snapshot."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["query", "connectorId", "predicate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicDashboardSQLQuerySource.model_rebuild()
except NameError:
    pass
