"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_configdiagnosticclass import (
    TextqlRPCPublicPatchesConfigDiagnosticClass,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesConfigDiagnosticTypedDict(TypedDict):
    path: NotRequired[str]
    r"""path is the config file the finding is attributed to."""
    message: NotRequired[str]
    class_: NotRequired[TextqlRPCPublicPatchesConfigDiagnosticClass]
    r"""ConfigDiagnosticClass partitions a finding by who can fix it, so an authoring loop
    knows whether to keep iterating.
    """


class TextqlRPCPublicPatchesConfigDiagnostic(BaseModel):
    path: Optional[str] = None
    r"""path is the config file the finding is attributed to."""

    message: Optional[str] = None

    class_: Annotated[
        Optional[TextqlRPCPublicPatchesConfigDiagnosticClass],
        pydantic.Field(alias="class"),
    ] = None
    r"""ConfigDiagnosticClass partitions a finding by who can fix it, so an authoring loop
    knows whether to keep iterating.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "message", "class"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesConfigDiagnostic.model_rebuild()
except NameError:
    pass
