"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_tableau_tableauproject import (
    TextqlRPCPublicTableauTableauProject,
    TextqlRPCPublicTableauTableauProjectTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicTableauListTableauProjectsResponseTypedDict(TypedDict):
    projects: NotRequired[List[TextqlRPCPublicTableauTableauProjectTypedDict]]


class TextqlRPCPublicTableauListTableauProjectsResponse(BaseModel):
    projects: Optional[List[TextqlRPCPublicTableauTableauProject]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["projects"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
