"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_cell import (
    TextqlRPCPublicChatCell,
    TextqlRPCPublicChatCellTypedDict,
)
from .textql_rpc_public_chat_threadwarningtype import (
    TextqlRPCPublicChatThreadWarningType,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicObserveThreadWarningTypedDict(TypedDict):
    id: NotRequired[str]
    chat_id: NotRequired[str]
    warning_type: NotRequired[TextqlRPCPublicChatThreadWarningType]
    r"""ThreadWarningType is the canonical set of thread warning types"""
    severity: NotRequired[str]
    detail: NotRequired[str]
    fix_chat_id: NotRequired[Nullable[str]]
    fix_patch_cell: NotRequired[TextqlRPCPublicChatCellTypedDict]
    fix_run_active: NotRequired[bool]
    fix_status: NotRequired[Nullable[str]]


class TextqlRPCPublicObserveThreadWarning(BaseModel):
    id: Optional[str] = None

    chat_id: Annotated[Optional[str], pydantic.Field(alias="chatId")] = None

    warning_type: Annotated[
        Optional[TextqlRPCPublicChatThreadWarningType],
        pydantic.Field(alias="warningType"),
    ] = None
    r"""ThreadWarningType is the canonical set of thread warning types"""

    severity: Optional[str] = None

    detail: Optional[str] = None

    fix_chat_id: Annotated[OptionalNullable[str], pydantic.Field(alias="fixChatId")] = (
        UNSET
    )

    fix_patch_cell: Annotated[
        Optional[TextqlRPCPublicChatCell], pydantic.Field(alias="fixPatchCell")
    ] = None

    fix_run_active: Annotated[Optional[bool], pydantic.Field(alias="fixRunActive")] = (
        None
    )

    fix_status: Annotated[OptionalNullable[str], pydantic.Field(alias="fixStatus")] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "chatId",
                "warningType",
                "severity",
                "detail",
                "fixChatId",
                "fixPatchCell",
                "fixRunActive",
                "fixStatus",
            ]
        )
        nullable_fields = set(["fixChatId", "fixStatus"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicObserveThreadWarning.model_rebuild()
except NameError:
    pass
