"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_previewontologypullfolderrow import (
    TextqlRPCPublicPatchesPreviewOntologyPullFolderRow,
    TextqlRPCPublicPatchesPreviewOntologyPullFolderRowTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesPreviewOntologyPullFromRemoteResponseTypedDict(TypedDict):
    total_files: NotRequired[int]
    top_level_folder_count: NotRequired[int]
    folder_rows: NotRequired[
        List[TextqlRPCPublicPatchesPreviewOntologyPullFolderRowTypedDict]
    ]
    unrelated_histories: NotRequired[bool]
    unrelated_histories_remote_additions: NotRequired[List[str]]
    unrelated_histories_conflict_paths: NotRequired[List[str]]


class TextqlRPCPublicPatchesPreviewOntologyPullFromRemoteResponse(BaseModel):
    total_files: Annotated[Optional[int], pydantic.Field(alias="totalFiles")] = None

    top_level_folder_count: Annotated[
        Optional[int], pydantic.Field(alias="topLevelFolderCount")
    ] = None

    folder_rows: Annotated[
        Optional[List[TextqlRPCPublicPatchesPreviewOntologyPullFolderRow]],
        pydantic.Field(alias="folderRows"),
    ] = None

    unrelated_histories: Annotated[
        Optional[bool], pydantic.Field(alias="unrelatedHistories")
    ] = None

    unrelated_histories_remote_additions: Annotated[
        Optional[List[str]], pydantic.Field(alias="unrelatedHistoriesRemoteAdditions")
    ] = None

    unrelated_histories_conflict_paths: Annotated[
        Optional[List[str]], pydantic.Field(alias="unrelatedHistoriesConflictPaths")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "totalFiles",
                "topLevelFolderCount",
                "folderRows",
                "unrelatedHistories",
                "unrelatedHistoriesRemoteAdditions",
                "unrelatedHistoriesConflictPaths",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesPreviewOntologyPullFromRemoteResponse.model_rebuild()
except NameError:
    pass
