"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicObserveUpdateCustomTopicRequestTypedDict(TypedDict):
    topic_id: NotRequired[str]
    name: NotRequired[str]
    covers: NotRequired[Nullable[str]]
    r"""When present, the definition is replaced. A changed definition wipes the
    topic's verdict='tagged' rows (manual exclusions survive) — the caller is
    expected to follow with BackfillCustomTopic to rebuild them.
    """
    excludes: NotRequired[Nullable[str]]


class TextqlRPCPublicObserveUpdateCustomTopicRequest(BaseModel):
    topic_id: Annotated[Optional[str], pydantic.Field(alias="topicId")] = None

    name: Optional[str] = None

    covers: OptionalNullable[str] = UNSET
    r"""When present, the definition is replaced. A changed definition wipes the
    topic's verdict='tagged' rows (manual exclusions survive) — the caller is
    expected to follow with BackfillCustomTopic to rebuild them.
    """

    excludes: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["topicId", "name", "covers", "excludes"])
        nullable_fields = set(["covers", "excludes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicObserveUpdateCustomTopicRequest.model_rebuild()
except NameError:
    pass
