"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorExecuteQueryResponseTypedDict(TypedDict):
    arrow_data: NotRequired[str]
    success: NotRequired[bool]
    error_message: NotRequired[str]


class TextqlRPCPublicConnectorExecuteQueryResponse(BaseModel):
    arrow_data: Annotated[Optional[str], pydantic.Field(alias="arrowData")] = None

    success: Optional[bool] = None

    error_message: Annotated[Optional[str], pydantic.Field(alias="errorMessage")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["arrowData", "success", "errorMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorExecuteQueryResponse.model_rebuild()
except NameError:
    pass
