"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicDashboardDashboardType = Union[
    Literal[
        "DASHBOARD_TYPE_UNSPECIFIED",
        "DASHBOARD_TYPE_STREAMLIT",
        "DASHBOARD_TYPE_HTML",
        "DASHBOARD_TYPE_DASH",
    ],
    UnrecognizedStr,
]
