"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorSQLServerMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    database: NotRequired[str]
    schema_: NotRequired[str]
    ssl_mode: NotRequired[bool]
    auth_type: NotRequired[str]
    krb5_realm: NotRequired[str]
    krb5_config: NotRequired[str]
    krb5_keytab: NotRequired[str]
    krb5_spn: NotRequired[str]
    client_cert: NotRequired[str]
    client_key: NotRequired[str]
    tenant_id: NotRequired[str]
    client_id: NotRequired[str]
    client_secret: NotRequired[str]


class TextqlRPCPublicConnectorSQLServerMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    database: Optional[str] = None

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = None

    ssl_mode: Annotated[Optional[bool], pydantic.Field(alias="sslMode")] = None

    auth_type: Annotated[Optional[str], pydantic.Field(alias="authType")] = None

    krb5_realm: Annotated[Optional[str], pydantic.Field(alias="krb5Realm")] = None

    krb5_config: Annotated[Optional[str], pydantic.Field(alias="krb5Config")] = None

    krb5_keytab: Annotated[Optional[str], pydantic.Field(alias="krb5Keytab")] = None

    krb5_spn: Annotated[Optional[str], pydantic.Field(alias="krb5Spn")] = None

    client_cert: Annotated[Optional[str], pydantic.Field(alias="clientCert")] = None

    client_key: Annotated[Optional[str], pydantic.Field(alias="clientKey")] = None

    tenant_id: Annotated[Optional[str], pydantic.Field(alias="tenantId")] = None

    client_id: Annotated[Optional[str], pydantic.Field(alias="clientId")] = None

    client_secret: Annotated[Optional[str], pydantic.Field(alias="clientSecret")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "database",
                "schema",
                "sslMode",
                "authType",
                "krb5Realm",
                "krb5Config",
                "krb5Keytab",
                "krb5Spn",
                "clientCert",
                "clientKey",
                "tenantId",
                "clientId",
                "clientSecret",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorSQLServerMetadata.model_rebuild()
except NameError:
    pass
