"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesSaveAllObjectsAsConfigRequestTypedDict(TypedDict):
    r"""SaveObjectAsConfig renders an existing DB object (object_type keyed like
    config_source: \"playbook\", later \"dashboard\", ...) as a config file and
    authors it as a new OPEN patch under the type's default ontology folder. The
    file can be moved/edited like any patch file before merging; on merge,
    reconcile takes over the original object when content and permissions allow.
    """

    object_type: NotRequired[str]


class TextqlRPCPublicPatchesSaveAllObjectsAsConfigRequest(BaseModel):
    r"""SaveObjectAsConfig renders an existing DB object (object_type keyed like
    config_source: \"playbook\", later \"dashboard\", ...) as a config file and
    authors it as a new OPEN patch under the type's default ontology folder. The
    file can be moved/edited like any patch file before merging; on merge,
    reconcile takes over the original object when content and permissions allow.
    """

    object_type: Annotated[Optional[str], pydantic.Field(alias="objectType")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["objectType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesSaveAllObjectsAsConfigRequest.model_rebuild()
except NameError:
    pass
