"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from textql_sdk.types import BaseModel
from typing_extensions import Annotated, TypedDict


class TextqlRPCPublicChatDeleteChatRequestTypedDict(TypedDict):
    chat_id: str


class TextqlRPCPublicChatDeleteChatRequest(BaseModel):
    chat_id: Annotated[str, pydantic.Field(alias="chatId")]


try:
    TextqlRPCPublicChatDeleteChatRequest.model_rebuild()
except NameError:
    pass
