"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_connectoraccessgrant import (
    TextqlRPCPublicConnectorConnectorAccessGrant,
    TextqlRPCPublicConnectorConnectorAccessGrantTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorConnectorAccessConfigTypedDict(TypedDict):
    is_public: NotRequired[bool]
    grants: NotRequired[List[TextqlRPCPublicConnectorConnectorAccessGrantTypedDict]]


class TextqlRPCPublicConnectorConnectorAccessConfig(BaseModel):
    is_public: Annotated[Optional[bool], pydantic.Field(alias="isPublic")] = None

    grants: Optional[List[TextqlRPCPublicConnectorConnectorAccessGrant]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["isPublic", "grants"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorConnectorAccessConfig.model_rebuild()
except NameError:
    pass
