"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicCellsContextPromptChangeStatus = Union[
    Literal[
        "STATUS_UNKNOWN",
        "STATUS_DRAFT",
        "STATUS_PENDING",
        "STATUS_REJECTED",
        "STATUS_APPLIED",
    ],
    UnrecognizedStr,
]
