"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_paradigm_params_paradigmparams import (
    TextqlRPCParadigmParamsParadigmParams,
    TextqlRPCParadigmParamsParadigmParamsTypedDict,
)
from datetime import datetime
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCAuthMemberTypedDict(TypedDict):
    id: NotRequired[int]
    org_id: NotRequired[str]
    member_id: NotRequired[str]
    role: NotRequired[Nullable[str]]
    preferred_first_name: NotRequired[Nullable[str]]
    preferred_last_name: NotRequired[Nullable[str]]
    show_code: NotRequired[Nullable[bool]]
    profile_image_url: NotRequired[Nullable[str]]
    email_address: NotRequired[str]
    name: NotRequired[Nullable[str]]
    is_admin: NotRequired[bool]
    selected_connector_id: NotRequired[Nullable[int]]
    roles: NotRequired[List[str]]
    created_at: NotRequired[datetime]
    r"""A Timestamp represents a point in time independent of any time zone or local
    calendar, encoded as a count of seconds and fractions of seconds at
    nanosecond resolution. The count is relative to an epoch at UTC midnight on
    January 1, 1970, in the proleptic Gregorian calendar which extends the
    Gregorian calendar backwards to year one.

    All minutes are 60 seconds long. Leap seconds are \"smeared\" so that no leap
    second table is needed for interpretation, using a [24-hour linear
    smear](https://developers.google.com/time/smear).

    The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
    restricting to that range, we ensure that we can convert to and from [RFC
    3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

    # Examples

    Example 1: Compute Timestamp from POSIX `time()`.

    Timestamp timestamp;
    timestamp.set_seconds(time(NULL));
    timestamp.set_nanos(0);

    Example 2: Compute Timestamp from POSIX `gettimeofday()`.

    struct timeval tv;
    gettimeofday(&tv, NULL);

    Timestamp timestamp;
    timestamp.set_seconds(tv.tv_sec);
    timestamp.set_nanos(tv.tv_usec * 1000);

    Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

    // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
    // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
    Timestamp timestamp;
    timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
    timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

    Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

    long millis = System.currentTimeMillis();

    Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
    .setNanos((int) ((millis % 1000) * 1000000)).build();

    Example 5: Compute Timestamp from Java `Instant.now()`.

    Instant now = Instant.now();

    Timestamp timestamp =
    Timestamp.newBuilder().setSeconds(now.getEpochSecond())
    .setNanos(now.getNano()).build();

    Example 6: Compute Timestamp from current time in Python.

    timestamp = Timestamp()
    timestamp.GetCurrentTime()

    # JSON Mapping

    In JSON format, the Timestamp type is encoded as a string in the
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
    format is \"{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z\" 
    where {year} is always expressed using four digits while {month}, {day},
    {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
    seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
    are optional. The \"Z\" suffix indicates the timezone (\"UTC\"); the timezone
    is required. A proto3 JSON serializer should always use UTC (as indicated by
    \"Z\") when printing the Timestamp type and a proto3 JSON parser should be
    able to accept both UTC and other timezones (as indicated by an offset).

    For example, \"2017-01-15T01:30:15.01Z\" encodes 15.01 seconds past
    01:30 UTC on January 15, 2017.

    In JavaScript, one can convert a Date object to this format using the
    standard
    [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
    method. In Python, a standard `datetime.datetime` object can be converted
    to this format using
    [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
    the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
    the Joda Time's [`ISODateTimeFormat.dateTime()`](
    http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
    ) to obtain a formatter capable of generating timestamps in this format.
    """
    updated_at: NotRequired[datetime]
    r"""A Timestamp represents a point in time independent of any time zone or local
    calendar, encoded as a count of seconds and fractions of seconds at
    nanosecond resolution. The count is relative to an epoch at UTC midnight on
    January 1, 1970, in the proleptic Gregorian calendar which extends the
    Gregorian calendar backwards to year one.

    All minutes are 60 seconds long. Leap seconds are \"smeared\" so that no leap
    second table is needed for interpretation, using a [24-hour linear
    smear](https://developers.google.com/time/smear).

    The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
    restricting to that range, we ensure that we can convert to and from [RFC
    3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

    # Examples

    Example 1: Compute Timestamp from POSIX `time()`.

    Timestamp timestamp;
    timestamp.set_seconds(time(NULL));
    timestamp.set_nanos(0);

    Example 2: Compute Timestamp from POSIX `gettimeofday()`.

    struct timeval tv;
    gettimeofday(&tv, NULL);

    Timestamp timestamp;
    timestamp.set_seconds(tv.tv_sec);
    timestamp.set_nanos(tv.tv_usec * 1000);

    Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

    // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
    // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
    Timestamp timestamp;
    timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
    timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

    Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

    long millis = System.currentTimeMillis();

    Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
    .setNanos((int) ((millis % 1000) * 1000000)).build();

    Example 5: Compute Timestamp from Java `Instant.now()`.

    Instant now = Instant.now();

    Timestamp timestamp =
    Timestamp.newBuilder().setSeconds(now.getEpochSecond())
    .setNanos(now.getNano()).build();

    Example 6: Compute Timestamp from current time in Python.

    timestamp = Timestamp()
    timestamp.GetCurrentTime()

    # JSON Mapping

    In JSON format, the Timestamp type is encoded as a string in the
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
    format is \"{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z\" 
    where {year} is always expressed using four digits while {month}, {day},
    {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
    seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
    are optional. The \"Z\" suffix indicates the timezone (\"UTC\"); the timezone
    is required. A proto3 JSON serializer should always use UTC (as indicated by
    \"Z\") when printing the Timestamp type and a proto3 JSON parser should be
    able to accept both UTC and other timezones (as indicated by an offset).

    For example, \"2017-01-15T01:30:15.01Z\" encodes 15.01 seconds past
    01:30 UTC on January 15, 2017.

    In JavaScript, one can convert a Date object to this format using the
    standard
    [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
    method. In Python, a standard `datetime.datetime` object can be converted
    to this format using
    [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
    the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
    the Joda Time's [`ISODateTimeFormat.dateTime()`](
    http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
    ) to obtain a formatter capable of generating timestamps in this format.
    """
    paradigm_params: NotRequired[TextqlRPCParadigmParamsParadigmParamsTypedDict]
    email_verified: NotRequired[bool]
    selected_connector_ids: NotRequired[List[int]]
    is_service_account: NotRequired[bool]
    is_scim_managed: NotRequired[bool]
    steering: NotRequired[Nullable[bool]]
    phone_number: NotRequired[Nullable[str]]
    phone_verified: NotRequired[Nullable[bool]]
    personal_agent_id: NotRequired[Nullable[str]]
    agent_number: NotRequired[Nullable[str]]
    default_methodology: NotRequired[Nullable[int]]
    r"""Per-member default response methodology for new chats, as a
    textql.rpc.public.chat.Methodology enum value (int to avoid an import
    cycle). 0 = UNKNOWN/unset -> fall back to the org default. Overrides the
    org default when set.
    """
    default_llm_model: NotRequired[Nullable[int]]
    r"""Per-member default LLM model for new chats, as a
    textql.rpc.public.chat.LlmModel enum value (int, matching the org-level
    default_llm_model). 0/MODEL_DEFAULT = unset -> role/org/system resolution.
    """
    default_fast_mode: NotRequired[Nullable[bool]]
    r"""Per-member default fast-mode preference for new chats. Unset -> off. Only
    applies when the org enables fast mode and the resolved model supports it.
    """
    first_name: NotRequired[Nullable[str]]
    r"""Identity (auth-provider) names, distinct from the user-set preferred names."""
    last_name: NotRequired[Nullable[str]]
    theme_mode: NotRequired[Nullable[str]]
    r"""Per-member UI theme preference: \"light\" | \"dark\" | \"system\".
    Unset -> the client falls back to its own default. Scoped to the
    membership, so a user in multiple orgs sets this per org.
    """
    share_app_builder_chat: NotRequired[Nullable[bool]]
    r"""When this member creates a data app from a chat, share that builder chat
    (read-only) with everyone who can view the app. Unset -> off (opt-in).
    Snapshotted onto the app at creation time; later toggles only affect future apps.
    """


class TextqlRPCAuthMember(BaseModel):
    id: Optional[int] = None

    org_id: Annotated[Optional[str], pydantic.Field(alias="orgId")] = None

    member_id: Annotated[Optional[str], pydantic.Field(alias="memberId")] = None

    role: OptionalNullable[str] = UNSET

    preferred_first_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="preferredFirstName")
    ] = UNSET

    preferred_last_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="preferredLastName")
    ] = UNSET

    show_code: Annotated[OptionalNullable[bool], pydantic.Field(alias="showCode")] = (
        UNSET
    )

    profile_image_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="profileImageUrl")
    ] = UNSET

    email_address: Annotated[Optional[str], pydantic.Field(alias="emailAddress")] = None

    name: OptionalNullable[str] = UNSET

    is_admin: Annotated[Optional[bool], pydantic.Field(alias="isAdmin")] = None

    selected_connector_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="selectedConnectorId")
    ] = UNSET

    roles: Optional[List[str]] = None

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None
    r"""A Timestamp represents a point in time independent of any time zone or local
    calendar, encoded as a count of seconds and fractions of seconds at
    nanosecond resolution. The count is relative to an epoch at UTC midnight on
    January 1, 1970, in the proleptic Gregorian calendar which extends the
    Gregorian calendar backwards to year one.

    All minutes are 60 seconds long. Leap seconds are \"smeared\" so that no leap
    second table is needed for interpretation, using a [24-hour linear
    smear](https://developers.google.com/time/smear).

    The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
    restricting to that range, we ensure that we can convert to and from [RFC
    3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

    # Examples

    Example 1: Compute Timestamp from POSIX `time()`.

    Timestamp timestamp;
    timestamp.set_seconds(time(NULL));
    timestamp.set_nanos(0);

    Example 2: Compute Timestamp from POSIX `gettimeofday()`.

    struct timeval tv;
    gettimeofday(&tv, NULL);

    Timestamp timestamp;
    timestamp.set_seconds(tv.tv_sec);
    timestamp.set_nanos(tv.tv_usec * 1000);

    Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

    // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
    // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
    Timestamp timestamp;
    timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
    timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

    Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

    long millis = System.currentTimeMillis();

    Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
    .setNanos((int) ((millis % 1000) * 1000000)).build();

    Example 5: Compute Timestamp from Java `Instant.now()`.

    Instant now = Instant.now();

    Timestamp timestamp =
    Timestamp.newBuilder().setSeconds(now.getEpochSecond())
    .setNanos(now.getNano()).build();

    Example 6: Compute Timestamp from current time in Python.

    timestamp = Timestamp()
    timestamp.GetCurrentTime()

    # JSON Mapping

    In JSON format, the Timestamp type is encoded as a string in the
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
    format is \"{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z\" 
    where {year} is always expressed using four digits while {month}, {day},
    {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
    seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
    are optional. The \"Z\" suffix indicates the timezone (\"UTC\"); the timezone
    is required. A proto3 JSON serializer should always use UTC (as indicated by
    \"Z\") when printing the Timestamp type and a proto3 JSON parser should be
    able to accept both UTC and other timezones (as indicated by an offset).

    For example, \"2017-01-15T01:30:15.01Z\" encodes 15.01 seconds past
    01:30 UTC on January 15, 2017.

    In JavaScript, one can convert a Date object to this format using the
    standard
    [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
    method. In Python, a standard `datetime.datetime` object can be converted
    to this format using
    [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
    the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
    the Joda Time's [`ISODateTimeFormat.dateTime()`](
    http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
    ) to obtain a formatter capable of generating timestamps in this format.
    """

    updated_at: Annotated[Optional[datetime], pydantic.Field(alias="updatedAt")] = None
    r"""A Timestamp represents a point in time independent of any time zone or local
    calendar, encoded as a count of seconds and fractions of seconds at
    nanosecond resolution. The count is relative to an epoch at UTC midnight on
    January 1, 1970, in the proleptic Gregorian calendar which extends the
    Gregorian calendar backwards to year one.

    All minutes are 60 seconds long. Leap seconds are \"smeared\" so that no leap
    second table is needed for interpretation, using a [24-hour linear
    smear](https://developers.google.com/time/smear).

    The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
    restricting to that range, we ensure that we can convert to and from [RFC
    3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

    # Examples

    Example 1: Compute Timestamp from POSIX `time()`.

    Timestamp timestamp;
    timestamp.set_seconds(time(NULL));
    timestamp.set_nanos(0);

    Example 2: Compute Timestamp from POSIX `gettimeofday()`.

    struct timeval tv;
    gettimeofday(&tv, NULL);

    Timestamp timestamp;
    timestamp.set_seconds(tv.tv_sec);
    timestamp.set_nanos(tv.tv_usec * 1000);

    Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

    // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
    // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
    Timestamp timestamp;
    timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
    timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

    Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

    long millis = System.currentTimeMillis();

    Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
    .setNanos((int) ((millis % 1000) * 1000000)).build();

    Example 5: Compute Timestamp from Java `Instant.now()`.

    Instant now = Instant.now();

    Timestamp timestamp =
    Timestamp.newBuilder().setSeconds(now.getEpochSecond())
    .setNanos(now.getNano()).build();

    Example 6: Compute Timestamp from current time in Python.

    timestamp = Timestamp()
    timestamp.GetCurrentTime()

    # JSON Mapping

    In JSON format, the Timestamp type is encoded as a string in the
    [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
    format is \"{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z\" 
    where {year} is always expressed using four digits while {month}, {day},
    {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
    seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
    are optional. The \"Z\" suffix indicates the timezone (\"UTC\"); the timezone
    is required. A proto3 JSON serializer should always use UTC (as indicated by
    \"Z\") when printing the Timestamp type and a proto3 JSON parser should be
    able to accept both UTC and other timezones (as indicated by an offset).

    For example, \"2017-01-15T01:30:15.01Z\" encodes 15.01 seconds past
    01:30 UTC on January 15, 2017.

    In JavaScript, one can convert a Date object to this format using the
    standard
    [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
    method. In Python, a standard `datetime.datetime` object can be converted
    to this format using
    [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
    the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
    the Joda Time's [`ISODateTimeFormat.dateTime()`](
    http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
    ) to obtain a formatter capable of generating timestamps in this format.
    """

    paradigm_params: Annotated[
        Optional[TextqlRPCParadigmParamsParadigmParams],
        pydantic.Field(alias="paradigmParams"),
    ] = None

    email_verified: Annotated[Optional[bool], pydantic.Field(alias="emailVerified")] = (
        None
    )

    selected_connector_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="selectedConnectorIds")
    ] = None

    is_service_account: Annotated[
        Optional[bool], pydantic.Field(alias="isServiceAccount")
    ] = None

    is_scim_managed: Annotated[
        Optional[bool], pydantic.Field(alias="isScimManaged")
    ] = None

    steering: OptionalNullable[bool] = UNSET

    phone_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="phoneNumber")
    ] = UNSET

    phone_verified: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="phoneVerified")
    ] = UNSET

    personal_agent_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="personalAgentId")
    ] = UNSET

    agent_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="agentNumber")
    ] = UNSET

    default_methodology: Annotated[
        OptionalNullable[int], pydantic.Field(alias="defaultMethodology")
    ] = UNSET
    r"""Per-member default response methodology for new chats, as a
    textql.rpc.public.chat.Methodology enum value (int to avoid an import
    cycle). 0 = UNKNOWN/unset -> fall back to the org default. Overrides the
    org default when set.
    """

    default_llm_model: Annotated[
        OptionalNullable[int], pydantic.Field(alias="defaultLlmModel")
    ] = UNSET
    r"""Per-member default LLM model for new chats, as a
    textql.rpc.public.chat.LlmModel enum value (int, matching the org-level
    default_llm_model). 0/MODEL_DEFAULT = unset -> role/org/system resolution.
    """

    default_fast_mode: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="defaultFastMode")
    ] = UNSET
    r"""Per-member default fast-mode preference for new chats. Unset -> off. Only
    applies when the org enables fast mode and the resolved model supports it.
    """

    first_name: Annotated[OptionalNullable[str], pydantic.Field(alias="firstName")] = (
        UNSET
    )
    r"""Identity (auth-provider) names, distinct from the user-set preferred names."""

    last_name: Annotated[OptionalNullable[str], pydantic.Field(alias="lastName")] = (
        UNSET
    )

    theme_mode: Annotated[OptionalNullable[str], pydantic.Field(alias="themeMode")] = (
        UNSET
    )
    r"""Per-member UI theme preference: \"light\" | \"dark\" | \"system\".
    Unset -> the client falls back to its own default. Scoped to the
    membership, so a user in multiple orgs sets this per org.
    """

    share_app_builder_chat: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="shareAppBuilderChat")
    ] = UNSET
    r"""When this member creates a data app from a chat, share that builder chat
    (read-only) with everyone who can view the app. Unset -> off (opt-in).
    Snapshotted onto the app at creation time; later toggles only affect future apps.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "orgId",
                "memberId",
                "role",
                "preferredFirstName",
                "preferredLastName",
                "showCode",
                "profileImageUrl",
                "emailAddress",
                "name",
                "isAdmin",
                "selectedConnectorId",
                "roles",
                "createdAt",
                "updatedAt",
                "paradigmParams",
                "emailVerified",
                "selectedConnectorIds",
                "isServiceAccount",
                "isScimManaged",
                "steering",
                "phoneNumber",
                "phoneVerified",
                "personalAgentId",
                "agentNumber",
                "defaultMethodology",
                "defaultLlmModel",
                "defaultFastMode",
                "firstName",
                "lastName",
                "themeMode",
                "shareAppBuilderChat",
            ]
        )
        nullable_fields = set(
            [
                "role",
                "preferredFirstName",
                "preferredLastName",
                "showCode",
                "profileImageUrl",
                "name",
                "selectedConnectorId",
                "steering",
                "phoneNumber",
                "phoneVerified",
                "personalAgentId",
                "agentNumber",
                "defaultMethodology",
                "defaultLlmModel",
                "defaultFastMode",
                "firstName",
                "lastName",
                "themeMode",
                "shareAppBuilderChat",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCAuthMember.model_rebuild()
except NameError:
    pass
