"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAgentListAgentsRequestTypedDict(TypedDict):
    include_inactive: NotRequired[bool]
    include_all_org: NotRequired[bool]
    days: NotRequired[int]


class TextqlRPCPublicAgentListAgentsRequest(BaseModel):
    include_inactive: Annotated[
        Optional[bool], pydantic.Field(alias="includeInactive")
    ] = None

    include_all_org: Annotated[
        Optional[bool], pydantic.Field(alias="includeAllOrg")
    ] = None

    days: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["includeInactive", "includeAllOrg", "days"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAgentListAgentsRequest.model_rebuild()
except NameError:
    pass
