"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPlaybookGetPlaybookReportsRequestTypedDict(TypedDict):
    playbook_id: NotRequired[str]
    r"""UUID"""
    limit: NotRequired[int]
    offset: NotRequired[int]
    chat_id: NotRequired[Nullable[str]]
    r"""UUID"""
    template_data_id: NotRequired[Nullable[str]]
    r"""UUID"""
    batch_run_id: NotRequired[Nullable[str]]
    r"""UUID - filter reports by batch run"""


class TextqlRPCPublicPlaybookGetPlaybookReportsRequest(BaseModel):
    playbook_id: Annotated[Optional[str], pydantic.Field(alias="playbookId")] = None
    r"""UUID"""

    limit: Optional[int] = None

    offset: Optional[int] = None

    chat_id: Annotated[OptionalNullable[str], pydantic.Field(alias="chatId")] = UNSET
    r"""UUID"""

    template_data_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="templateDataId")
    ] = UNSET
    r"""UUID"""

    batch_run_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="batchRunId")
    ] = UNSET
    r"""UUID - filter reports by batch run"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["playbookId", "limit", "offset", "chatId", "templateDataId", "batchRunId"]
        )
        nullable_fields = set(["chatId", "templateDataId", "batchRunId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicPlaybookGetPlaybookReportsRequest.model_rebuild()
except NameError:
    pass
