"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicOntologyTableNameTypedDict(TypedDict):
    r"""Core data types"""

    schema_: NotRequired[str]
    table: NotRequired[str]
    database: NotRequired[str]


class TextqlRPCPublicOntologyTableName(BaseModel):
    r"""Core data types"""

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = None

    table: Optional[str] = None

    database: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["schema", "table", "database"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicOntologyTableName.model_rebuild()
except NameError:
    pass
