"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_connectorcontext import (
    TextqlRPCPublicConnectorConnectorContext,
    TextqlRPCPublicConnectorConnectorContextTypedDict,
)
from .textql_rpc_public_connector_featuretype import TextqlRPCPublicConnectorFeatureType
from .textql_rpc_public_connector_messagesegment import (
    TextqlRPCPublicConnectorMessageSegment,
    TextqlRPCPublicConnectorMessageSegmentTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorExampleQueryTypedDict(TypedDict):
    id: NotRequired[str]
    r"""PowerBI report IDs"""
    label: NotRequired[str]
    r"""PowerBI dataset IDs (PowerBI datasets, not internal dataset_source)"""
    message: NotRequired[str]
    r"""workspace dataset_source IDs (cache key, like Tableau collections)"""
    is_multi_source: NotRequired[bool]
    required_connector_ids: NotRequired[List[int]]
    category: NotRequired[str]
    segments: NotRequired[List[TextqlRPCPublicConnectorMessageSegmentTypedDict]]
    required_features: NotRequired[List[TextqlRPCPublicConnectorFeatureType]]
    source_context: NotRequired[TextqlRPCPublicConnectorConnectorContextTypedDict]


class TextqlRPCPublicConnectorExampleQuery(BaseModel):
    id: Optional[str] = None
    r"""PowerBI report IDs"""

    label: Optional[str] = None
    r"""PowerBI dataset IDs (PowerBI datasets, not internal dataset_source)"""

    message: Optional[str] = None
    r"""workspace dataset_source IDs (cache key, like Tableau collections)"""

    is_multi_source: Annotated[
        Optional[bool], pydantic.Field(alias="isMultiSource")
    ] = None

    required_connector_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="requiredConnectorIds")
    ] = None

    category: Optional[str] = None

    segments: Optional[List[TextqlRPCPublicConnectorMessageSegment]] = None

    required_features: Annotated[
        Optional[List[TextqlRPCPublicConnectorFeatureType]],
        pydantic.Field(alias="requiredFeatures"),
    ] = None

    source_context: Annotated[
        Optional[TextqlRPCPublicConnectorConnectorContext],
        pydantic.Field(alias="sourceContext"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "label",
                "message",
                "isMultiSource",
                "requiredConnectorIds",
                "category",
                "segments",
                "requiredFeatures",
                "sourceContext",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorExampleQuery.model_rebuild()
except NameError:
    pass
