"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorTrinoMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    catalog: NotRequired[str]
    schema_: NotRequired[str]
    ssl_mode: NotRequired[bool]
    access_token: NotRequired[str]
    skip_tls_verify: NotRequired[bool]


class TextqlRPCPublicConnectorTrinoMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    catalog: Optional[str] = None

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = None

    ssl_mode: Annotated[Optional[bool], pydantic.Field(alias="sslMode")] = None

    access_token: Annotated[Optional[str], pydantic.Field(alias="accessToken")] = None

    skip_tls_verify: Annotated[
        Optional[bool], pydantic.Field(alias="skipTlsVerify")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "catalog",
                "schema",
                "sslMode",
                "accessToken",
                "skipTlsVerify",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorTrinoMetadata.model_rebuild()
except NameError:
    pass
