"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_chat import (
    TextqlRPCPublicChatChat,
    TextqlRPCPublicChatChatTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicChatGetChatsResponseTypedDict(TypedDict):
    chats: NotRequired[List[TextqlRPCPublicChatChatTypedDict]]
    total_count: NotRequired[int]


class TextqlRPCPublicChatGetChatsResponse(BaseModel):
    chats: Optional[List[TextqlRPCPublicChatChat]] = None

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["chats", "totalCount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicChatGetChatsResponse.model_rebuild()
except NameError:
    pass
