"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicObserveAgentBillingStatTypedDict(TypedDict):
    agent_id: NotRequired[str]
    estimated_acu: NotRequired[float]
    r"""proportionally distributed from member's feed ACU by post count"""
    is_internal: NotRequired[bool]


class TextqlRPCPublicObserveAgentBillingStat(BaseModel):
    agent_id: Annotated[Optional[str], pydantic.Field(alias="agentId")] = None

    estimated_acu: Annotated[Optional[float], pydantic.Field(alias="estimatedAcu")] = (
        None
    )
    r"""proportionally distributed from member's feed ACU by post count"""

    is_internal: Annotated[Optional[bool], pydantic.Field(alias="isInternal")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agentId", "estimatedAcu", "isInternal"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicObserveAgentBillingStat.model_rebuild()
except NameError:
    pass
