"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicDashboardGrantTypedDict(TypedDict):
    r"""Grant is an author allowlist gating a data source or compute function. A viewer whose
    effective role names intersect roles, or whose member id is listed in members, may call it.
    Absent grant = org-visible (today's behavior); an empty grant object is invalid.
    """

    roles: NotRequired[List[str]]
    r"""org role names"""
    members: NotRequired[List[str]]
    r"""explicit member ids"""


class TextqlRPCPublicDashboardGrant(BaseModel):
    r"""Grant is an author allowlist gating a data source or compute function. A viewer whose
    effective role names intersect roles, or whose member id is listed in members, may call it.
    Absent grant = org-visible (today's behavior); an empty grant object is invalid.
    """

    roles: Optional[List[str]] = None
    r"""org role names"""

    members: Optional[List[str]] = None
    r"""explicit member ids"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["roles", "members"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
