"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


MinGenerationTypedDict = TypeAliasType("MinGenerationTypedDict", Union[int, str])


MinGeneration = TypeAliasType("MinGeneration", Union[int, str])


class TextqlRPCPublicChatPollChatEventsRequestTypedDict(TypedDict):
    chat_id: str
    resume_cursor: NotRequired[Nullable[str]]
    min_generation: NotRequired[MinGenerationTypedDict]


class TextqlRPCPublicChatPollChatEventsRequest(BaseModel):
    chat_id: Annotated[str, pydantic.Field(alias="chatId")]

    resume_cursor: Annotated[
        OptionalNullable[str], pydantic.Field(alias="resumeCursor")
    ] = UNSET

    min_generation: Annotated[
        Optional[MinGeneration], pydantic.Field(alias="minGeneration")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["resumeCursor", "minGeneration"])
        nullable_fields = set(["resumeCursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicChatPollChatEventsRequest.model_rebuild()
except NameError:
    pass
