"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_audit_log_s3authmode import TextqlRPCPublicAuditLogS3AuthMode
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAuditLogTestS3ExportConnectionRequestTypedDict(TypedDict):
    bucket: NotRequired[str]
    region: NotRequired[str]
    aws_access_key_id: NotRequired[str]
    aws_secret_access_key: NotRequired[str]
    auth_mode: NotRequired[TextqlRPCPublicAuditLogS3AuthMode]
    role_arn: NotRequired[str]
    external_id: NotRequired[str]


class TextqlRPCPublicAuditLogTestS3ExportConnectionRequest(BaseModel):
    bucket: Optional[str] = None

    region: Optional[str] = None

    aws_access_key_id: Annotated[
        Optional[str], pydantic.Field(alias="awsAccessKeyId")
    ] = None

    aws_secret_access_key: Annotated[
        Optional[str], pydantic.Field(alias="awsSecretAccessKey")
    ] = None

    auth_mode: Annotated[
        Optional[TextqlRPCPublicAuditLogS3AuthMode], pydantic.Field(alias="authMode")
    ] = None

    role_arn: Annotated[Optional[str], pydantic.Field(alias="roleArn")] = None

    external_id: Annotated[Optional[str], pydantic.Field(alias="externalId")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "bucket",
                "region",
                "awsAccessKeyId",
                "awsSecretAccessKey",
                "authMode",
                "roleArn",
                "externalId",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAuditLogTestS3ExportConnectionRequest.model_rebuild()
except NameError:
    pass
