"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsAppCellTypedDict(TypedDict):
    r"""AppCell records an agent action on a data app (the generative app execution primitive; apps are first-class rows in the apps table)."""

    action: NotRequired[str]
    r"""create | update | publish"""
    app_id: NotRequired[str]
    name: NotRequired[str]
    error_message: NotRequired[Nullable[str]]
    screenshot_url: NotRequired[Nullable[str]]
    last_run_at: NotRequired[Nullable[str]]
    build_line_count: NotRequired[Nullable[int]]
    r"""Size of the app being written, updated live as the tool args stream so the
    builder loader can show real \"N lines / M files\" progress during generation.
    """
    build_file_count: NotRequired[Nullable[int]]


class TextqlRPCPublicCellsAppCell(BaseModel):
    r"""AppCell records an agent action on a data app (the generative app execution primitive; apps are first-class rows in the apps table)."""

    action: Optional[str] = None
    r"""create | update | publish"""

    app_id: Annotated[Optional[str], pydantic.Field(alias="appId")] = None

    name: Optional[str] = None

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    screenshot_url: Annotated[
        OptionalNullable[str], pydantic.Field(alias="screenshotUrl")
    ] = UNSET

    last_run_at: Annotated[OptionalNullable[str], pydantic.Field(alias="lastRunAt")] = (
        UNSET
    )

    build_line_count: Annotated[
        OptionalNullable[int], pydantic.Field(alias="buildLineCount")
    ] = UNSET
    r"""Size of the app being written, updated live as the tool args stream so the
    builder loader can show real \"N lines / M files\" progress during generation.
    """

    build_file_count: Annotated[
        OptionalNullable[int], pydantic.Field(alias="buildFileCount")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "appId",
                "name",
                "errorMessage",
                "screenshotUrl",
                "lastRunAt",
                "buildLineCount",
                "buildFileCount",
            ]
        )
        nullable_fields = set(
            [
                "errorMessage",
                "screenshotUrl",
                "lastRunAt",
                "buildLineCount",
                "buildFileCount",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsAppCell.model_rebuild()
except NameError:
    pass
