"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_ontologyremote import (
    TextqlRPCPublicPatchesOntologyRemote,
    TextqlRPCPublicPatchesOntologyRemoteTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesGetOntologyRemoteResponseTypedDict(TypedDict):
    remote: NotRequired[TextqlRPCPublicPatchesOntologyRemoteTypedDict]
    r"""Deprecated: use SetOntologyOwnersRequest."""
    hosted_github_app_available: NotRequired[bool]
    hosted_github_app_slug: NotRequired[Nullable[str]]
    github_oauth_available: NotRequired[bool]


class TextqlRPCPublicPatchesGetOntologyRemoteResponse(BaseModel):
    remote: Optional[TextqlRPCPublicPatchesOntologyRemote] = None
    r"""Deprecated: use SetOntologyOwnersRequest."""

    hosted_github_app_available: Annotated[
        Optional[bool], pydantic.Field(alias="hostedGithubAppAvailable")
    ] = None

    hosted_github_app_slug: Annotated[
        OptionalNullable[str], pydantic.Field(alias="hostedGithubAppSlug")
    ] = UNSET

    github_oauth_available: Annotated[
        Optional[bool], pydantic.Field(alias="githubOauthAvailable")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "remote",
                "hostedGithubAppAvailable",
                "hostedGithubAppSlug",
                "githubOauthAvailable",
            ]
        )
        nullable_fields = set(["hostedGithubAppSlug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesGetOntologyRemoteResponse.model_rebuild()
except NameError:
    pass
