"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicRbacChatPermissionAction = Union[
    Literal[
        "CHAT_ACTION_UNSPECIFIED",
        "CHAT_ACTION_READ",
        "CHAT_ACTION_READ_PRIVATE",
        "CHAT_ACTION_WRITE",
        "CHAT_ACTION_WRITE_PRIVATE",
    ],
    UnrecognizedStr,
]
