"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_configdiagnostic import (
    TextqlRPCPublicPatchesConfigDiagnostic,
    TextqlRPCPublicPatchesConfigDiagnosticTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicPatchesValidateConfigResponseTypedDict(TypedDict):
    r"""ValidateConfigResponse: ok == true with no diagnostics means functionally valid
    against current org state — not a merge guarantee.
    """

    ok: NotRequired[bool]
    diagnostics: NotRequired[List[TextqlRPCPublicPatchesConfigDiagnosticTypedDict]]


class TextqlRPCPublicPatchesValidateConfigResponse(BaseModel):
    r"""ValidateConfigResponse: ok == true with no diagnostics means functionally valid
    against current org state — not a merge guarantee.
    """

    ok: Optional[bool] = None

    diagnostics: Optional[List[TextqlRPCPublicPatchesConfigDiagnostic]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ok", "diagnostics"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
