"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicChatCheckChatPermissionsResponseTypedDict(TypedDict):
    has_write_permission: NotRequired[bool]
    has_read_permission: NotRequired[bool]
    connector_id: NotRequired[Nullable[int]]
    ontology_id: NotRequired[Nullable[int]]
    connector_ids: NotRequired[List[int]]
    ontology_ids: NotRequired[List[int]]


class TextqlRPCPublicChatCheckChatPermissionsResponse(BaseModel):
    has_write_permission: Annotated[
        Optional[bool], pydantic.Field(alias="hasWritePermission")
    ] = None

    has_read_permission: Annotated[
        Optional[bool], pydantic.Field(alias="hasReadPermission")
    ] = None

    connector_id: Annotated[
        OptionalNullable[int],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.",
            alias="connectorId",
        ),
    ] = UNSET

    ontology_id: Annotated[
        OptionalNullable[int],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.",
            alias="ontologyId",
        ),
    ] = UNSET

    connector_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="connectorIds")
    ] = None

    ontology_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="ontologyIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "hasWritePermission",
                "hasReadPermission",
                "connectorId",
                "ontologyId",
                "connectorIds",
                "ontologyIds",
            ]
        )
        nullable_fields = set(["connectorId", "ontologyId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicChatCheckChatPermissionsResponse.model_rebuild()
except NameError:
    pass
