"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_powerbi_selection_powerbiselection import (
    TextqlRPCPowerbiSelectionPowerBISelection,
    TextqlRPCPowerbiSelectionPowerBISelectionTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicParadigmUniversalOptionsTypedDict(TypedDict):
    connector_ids: NotRequired[List[int]]
    dataset_id: NotRequired[Nullable[str]]
    web_search_enabled: NotRequired[bool]
    sql_enabled: NotRequired[bool]
    ontology_enabled: NotRequired[bool]
    ontology_editing_enabled: NotRequired[bool]
    python_enabled: NotRequired[bool]
    auto_approve_enabled: NotRequired[bool]
    google_drive_enabled: NotRequired[bool]
    powerbi_enabled: NotRequired[bool]
    context_editing_enabled: NotRequired[bool]
    form_editor_enabled: NotRequired[bool]
    playbook_tools_enabled: NotRequired[bool]
    microsoft365_enabled: NotRequired[bool]
    feed_explorer_enabled: NotRequired[bool]
    bash_enabled: NotRequired[bool]
    javascript_enabled: NotRequired[bool]
    feed_post_enabled: NotRequired[bool]
    feed_comment_enabled: NotRequired[bool]
    feed_engage_enabled: NotRequired[bool]
    streamlit_enabled: NotRequired[bool]
    compaction_disabled: NotRequired[bool]
    r"""compaction enabled by default"""
    gmail_enabled: NotRequired[bool]
    chat_history_search_enabled: NotRequired[bool]
    google_calendar_enabled: NotRequired[bool]
    email_output_enabled: NotRequired[bool]
    powerbi_selections: NotRequired[
        List[TextqlRPCPowerbiSelectionPowerBISelectionTypedDict]
    ]
    sms_mode: NotRequired[bool]
    api_access_key_ids: NotRequired[List[str]]


class TextqlRPCPublicParadigmUniversalOptions(BaseModel):
    connector_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="connectorIds")
    ] = None

    dataset_id: Annotated[OptionalNullable[str], pydantic.Field(alias="datasetId")] = (
        UNSET
    )

    web_search_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="webSearchEnabled")
    ] = None

    sql_enabled: Annotated[Optional[bool], pydantic.Field(alias="sqlEnabled")] = None

    ontology_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="ontologyEnabled")
    ] = None

    ontology_editing_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="ontologyEditingEnabled")
    ] = None

    python_enabled: Annotated[Optional[bool], pydantic.Field(alias="pythonEnabled")] = (
        None
    )

    auto_approve_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="autoApproveEnabled")
    ] = None

    google_drive_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="googleDriveEnabled")
    ] = None

    powerbi_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="powerbiEnabled")
    ] = None

    context_editing_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="contextEditingEnabled")
    ] = None

    form_editor_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="formEditorEnabled")
    ] = None

    playbook_tools_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="playbookToolsEnabled")
    ] = None

    microsoft365_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="microsoft365Enabled")
    ] = None

    feed_explorer_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="feedExplorerEnabled")
    ] = None

    bash_enabled: Annotated[Optional[bool], pydantic.Field(alias="bashEnabled")] = None

    javascript_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="javascriptEnabled")
    ] = None

    feed_post_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="feedPostEnabled")
    ] = None

    feed_comment_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="feedCommentEnabled")
    ] = None

    feed_engage_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="feedEngageEnabled")
    ] = None

    streamlit_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="streamlitEnabled")
    ] = None

    compaction_disabled: Annotated[
        Optional[bool], pydantic.Field(alias="compactionDisabled")
    ] = None
    r"""compaction enabled by default"""

    gmail_enabled: Annotated[Optional[bool], pydantic.Field(alias="gmailEnabled")] = (
        None
    )

    chat_history_search_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="chatHistorySearchEnabled")
    ] = None

    google_calendar_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="googleCalendarEnabled")
    ] = None

    email_output_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="emailOutputEnabled")
    ] = None

    powerbi_selections: Annotated[
        Optional[List[TextqlRPCPowerbiSelectionPowerBISelection]],
        pydantic.Field(alias="powerbiSelections"),
    ] = None

    sms_mode: Annotated[Optional[bool], pydantic.Field(alias="smsMode")] = None

    api_access_key_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="apiAccessKeyIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connectorIds",
                "datasetId",
                "webSearchEnabled",
                "sqlEnabled",
                "ontologyEnabled",
                "ontologyEditingEnabled",
                "pythonEnabled",
                "autoApproveEnabled",
                "googleDriveEnabled",
                "powerbiEnabled",
                "contextEditingEnabled",
                "formEditorEnabled",
                "playbookToolsEnabled",
                "microsoft365Enabled",
                "feedExplorerEnabled",
                "bashEnabled",
                "javascriptEnabled",
                "feedPostEnabled",
                "feedCommentEnabled",
                "feedEngageEnabled",
                "streamlitEnabled",
                "compactionDisabled",
                "gmailEnabled",
                "chatHistorySearchEnabled",
                "googleCalendarEnabled",
                "emailOutputEnabled",
                "powerbiSelections",
                "smsMode",
                "apiAccessKeyIds",
            ]
        )
        nullable_fields = set(["datasetId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicParadigmUniversalOptions.model_rebuild()
except NameError:
    pass
