"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytesTypedDict = TypeAliasType(
    "TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytesTypedDict",
    Union[int, str],
)


TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytes = TypeAliasType(
    "TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytes", Union[int, str]
)


class TextqlRPCPublicSandboxAdminReadSandboxFileResponseTypedDict(TypedDict):
    available: NotRequired[bool]
    r"""False when the sandbox is not running (no live filesystem)."""
    name: NotRequired[str]
    size_bytes: NotRequired[
        TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytesTypedDict
    ]
    mime_type: NotRequired[str]
    content: NotRequired[str]
    r"""UTF-8 text content; empty for binary files (see binary_content)."""
    binary_content: NotRequired[str]
    r"""Raw bytes for binary files (e.g. images); empty for text files."""
    truncated: NotRequired[bool]
    r"""True when the file exceeded the read cap and content/binary was clipped."""
    is_binary: NotRequired[bool]


class TextqlRPCPublicSandboxAdminReadSandboxFileResponse(BaseModel):
    available: Optional[bool] = None
    r"""False when the sandbox is not running (no live filesystem)."""

    name: Optional[str] = None

    size_bytes: Annotated[
        Optional[TextqlRPCPublicSandboxAdminReadSandboxFileResponseSizeBytes],
        pydantic.Field(alias="sizeBytes"),
    ] = None

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None

    content: Optional[str] = None
    r"""UTF-8 text content; empty for binary files (see binary_content)."""

    binary_content: Annotated[Optional[str], pydantic.Field(alias="binaryContent")] = (
        None
    )
    r"""Raw bytes for binary files (e.g. images); empty for text files."""

    truncated: Optional[bool] = None
    r"""True when the file exceeded the read cap and content/binary was clipped."""

    is_binary: Annotated[Optional[bool], pydantic.Field(alias="isBinary")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "available",
                "name",
                "sizeBytes",
                "mimeType",
                "content",
                "binaryContent",
                "truncated",
                "isBinary",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicSandboxAdminReadSandboxFileResponse.model_rebuild()
except NameError:
    pass
