"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_questioninput import (
    TextqlRPCPublicCellsQuestionInput,
    TextqlRPCPublicCellsQuestionInputTypedDict,
)
from .textql_rpc_public_cells_questionkind import TextqlRPCPublicCellsQuestionKind
from .textql_rpc_public_cells_questionoption import (
    TextqlRPCPublicCellsQuestionOption,
    TextqlRPCPublicCellsQuestionOptionTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsQuestionSpecTypedDict(TypedDict):
    question: NotRequired[str]
    explanation: NotRequired[Nullable[str]]
    kind: NotRequired[TextqlRPCPublicCellsQuestionKind]
    options: NotRequired[List[TextqlRPCPublicCellsQuestionOptionTypedDict]]
    allow_custom: NotRequired[bool]
    inputs: NotRequired[List[TextqlRPCPublicCellsQuestionInputTypedDict]]


class TextqlRPCPublicCellsQuestionSpec(BaseModel):
    question: Optional[str] = None

    explanation: OptionalNullable[str] = UNSET

    kind: Optional[TextqlRPCPublicCellsQuestionKind] = None

    options: Optional[List[TextqlRPCPublicCellsQuestionOption]] = None

    allow_custom: Annotated[Optional[bool], pydantic.Field(alias="allowCustom")] = None

    inputs: Optional[List[TextqlRPCPublicCellsQuestionInput]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["question", "explanation", "kind", "options", "allowCustom", "inputs"]
        )
        nullable_fields = set(["explanation"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsQuestionSpec.model_rebuild()
except NameError:
    pass
