"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_connectorref import (
    TextqlRPCPublicCellsConnectorRef,
    TextqlRPCPublicCellsConnectorRefTypedDict,
)
from .textql_rpc_public_cells_fieldchange import (
    TextqlRPCPublicCellsFieldChange,
    TextqlRPCPublicCellsFieldChangeTypedDict,
)
from .textql_rpc_public_cells_orgmemberref import (
    TextqlRPCPublicCellsOrgMemberRef,
    TextqlRPCPublicCellsOrgMemberRefTypedDict,
)
from .textql_rpc_public_cells_playbookeditoraction import (
    TextqlRPCPublicCellsPlaybookEditorAction,
)
from .textql_rpc_public_cells_playbookinfo import (
    TextqlRPCPublicCellsPlaybookInfo,
    TextqlRPCPublicCellsPlaybookInfoTypedDict,
)
from .textql_rpc_public_cells_slackchannelref import (
    TextqlRPCPublicCellsSlackChannelRef,
    TextqlRPCPublicCellsSlackChannelRefTypedDict,
)
from .textql_rpc_public_cells_slackuserref import (
    TextqlRPCPublicCellsSlackUserRef,
    TextqlRPCPublicCellsSlackUserRefTypedDict,
)
from .textql_rpc_public_cells_teamschannelref import (
    TextqlRPCPublicCellsTeamsChannelRef,
    TextqlRPCPublicCellsTeamsChannelRefTypedDict,
)
from .textql_rpc_public_cells_teamsuserref import (
    TextqlRPCPublicCellsTeamsUserRef,
    TextqlRPCPublicCellsTeamsUserRefTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsPlaybookEditorCellTypedDict(TypedDict):
    action: NotRequired[TextqlRPCPublicCellsPlaybookEditorAction]
    playbooks: NotRequired[List[TextqlRPCPublicCellsPlaybookInfoTypedDict]]
    error_message: NotRequired[Nullable[str]]
    total_count: NotRequired[int]
    slack_channels: NotRequired[List[TextqlRPCPublicCellsSlackChannelRefTypedDict]]
    slack_users: NotRequired[List[TextqlRPCPublicCellsSlackUserRefTypedDict]]
    connectors: NotRequired[List[TextqlRPCPublicCellsConnectorRefTypedDict]]
    org_members: NotRequired[List[TextqlRPCPublicCellsOrgMemberRefTypedDict]]
    has_slack: NotRequired[bool]
    field_changes: NotRequired[List[TextqlRPCPublicCellsFieldChangeTypedDict]]
    teams_channels: NotRequired[List[TextqlRPCPublicCellsTeamsChannelRefTypedDict]]
    teams_users: NotRequired[List[TextqlRPCPublicCellsTeamsUserRefTypedDict]]
    has_teams: NotRequired[bool]


class TextqlRPCPublicCellsPlaybookEditorCell(BaseModel):
    action: Optional[TextqlRPCPublicCellsPlaybookEditorAction] = None

    playbooks: Optional[List[TextqlRPCPublicCellsPlaybookInfo]] = None

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None

    slack_channels: Annotated[
        Optional[List[TextqlRPCPublicCellsSlackChannelRef]],
        pydantic.Field(alias="slackChannels"),
    ] = None

    slack_users: Annotated[
        Optional[List[TextqlRPCPublicCellsSlackUserRef]],
        pydantic.Field(alias="slackUsers"),
    ] = None

    connectors: Optional[List[TextqlRPCPublicCellsConnectorRef]] = None

    org_members: Annotated[
        Optional[List[TextqlRPCPublicCellsOrgMemberRef]],
        pydantic.Field(alias="orgMembers"),
    ] = None

    has_slack: Annotated[Optional[bool], pydantic.Field(alias="hasSlack")] = None

    field_changes: Annotated[
        Optional[List[TextqlRPCPublicCellsFieldChange]],
        pydantic.Field(alias="fieldChanges"),
    ] = None

    teams_channels: Annotated[
        Optional[List[TextqlRPCPublicCellsTeamsChannelRef]],
        pydantic.Field(alias="teamsChannels"),
    ] = None

    teams_users: Annotated[
        Optional[List[TextqlRPCPublicCellsTeamsUserRef]],
        pydantic.Field(alias="teamsUsers"),
    ] = None

    has_teams: Annotated[Optional[bool], pydantic.Field(alias="hasTeams")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "playbooks",
                "errorMessage",
                "totalCount",
                "slackChannels",
                "slackUsers",
                "connectors",
                "orgMembers",
                "hasSlack",
                "fieldChanges",
                "teamsChannels",
                "teamsUsers",
                "hasTeams",
            ]
        )
        nullable_fields = set(["errorMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsPlaybookEditorCell.model_rebuild()
except NameError:
    pass
