"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPowerbiSyncPowerBIItemsResponseTypedDict(TypedDict):
    success: NotRequired[bool]
    error: NotRequired[Nullable[str]]
    synced_report_ids: NotRequired[List[str]]
    synced_dataset_ids: NotRequired[List[str]]


class TextqlRPCPublicPowerbiSyncPowerBIItemsResponse(BaseModel):
    success: Optional[bool] = None

    error: OptionalNullable[str] = UNSET

    synced_report_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="syncedReportIds")
    ] = None

    synced_dataset_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="syncedDatasetIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["success", "error", "syncedReportIds", "syncedDatasetIds"]
        )
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicPowerbiSyncPowerBIItemsResponse.model_rebuild()
except NameError:
    pass
