"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_connectortype import (
    TextqlRPCPublicConnectorConnectorType,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorCreateConnectorResponseTypedDict(TypedDict):
    connector_id: NotRequired[int]
    name: NotRequired[str]
    connector_type: NotRequired[TextqlRPCPublicConnectorConnectorType]


class TextqlRPCPublicConnectorCreateConnectorResponse(BaseModel):
    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    name: Optional[str] = None

    connector_type: Annotated[
        Optional[TextqlRPCPublicConnectorConnectorType],
        pydantic.Field(alias="connectorType"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectorId", "name", "connectorType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorCreateConnectorResponse.model_rebuild()
except NameError:
    pass
