"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_playbook_templatedatareports import (
    TextqlRPCPublicPlaybookTemplateDataReports,
    TextqlRPCPublicPlaybookTemplateDataReportsTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPlaybookGetPlaybookReportsBatchResponseTypedDict(TypedDict):
    r"""Batch response with reports grouped by template_data_id"""

    template_data_reports: NotRequired[
        List[TextqlRPCPublicPlaybookTemplateDataReportsTypedDict]
    ]


class TextqlRPCPublicPlaybookGetPlaybookReportsBatchResponse(BaseModel):
    r"""Batch response with reports grouped by template_data_id"""

    template_data_reports: Annotated[
        Optional[List[TextqlRPCPublicPlaybookTemplateDataReports]],
        pydantic.Field(alias="templateDataReports"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["templateDataReports"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPlaybookGetPlaybookReportsBatchResponse.model_rebuild()
except NameError:
    pass
