"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_ontologyowners import (
    TextqlRPCPublicPatchesOntologyOwners,
    TextqlRPCPublicPatchesOntologyOwnersTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicPatchesSetOntologyOwnersResponseTypedDict(TypedDict):
    r"""Returns the *effective* owners for a directory after walking ancestor
    OWNERS files: for every role in the org, the resolved permission the
    role would have on this directory (per `permissionForDirWithRoles`).
    Use this when you need to compare permissions across paths — the
    literal GetOntologyOwners only reflects the OWNERS file at the exact
    path, missing inheritance.
    """

    owners: NotRequired[TextqlRPCPublicPatchesOntologyOwnersTypedDict]


class TextqlRPCPublicPatchesSetOntologyOwnersResponse(BaseModel):
    r"""Returns the *effective* owners for a directory after walking ancestor
    OWNERS files: for every role in the org, the resolved permission the
    role would have on this directory (per `permissionForDirWithRoles`).
    Use this when you need to compare permissions across paths — the
    literal GetOntologyOwners only reflects the OWNERS file at the exact
    path, missing inheritance.
    """

    owners: Optional[TextqlRPCPublicPatchesOntologyOwners] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["owners"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
