"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSecretPutSecretRequestTypedDict(TypedDict):
    name: NotRequired[str]
    value: NotRequired[str]
    description: NotRequired[Nullable[str]]
    link: NotRequired[Nullable[str]]
    is_private: NotRequired[bool]


class TextqlRPCPublicSecretPutSecretRequest(BaseModel):
    name: Optional[str] = None

    value: Optional[str] = None

    description: OptionalNullable[str] = UNSET

    link: OptionalNullable[str] = UNSET

    is_private: Annotated[Optional[bool], pydantic.Field(alias="isPrivate")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "value", "description", "link", "isPrivate"])
        nullable_fields = set(["description", "link"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicSecretPutSecretRequest.model_rebuild()
except NameError:
    pass
