"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAppListAppVersionsRequestTypedDict(TypedDict):
    r"""AppFile is one non-entry file of a multi-file app tree; code remains the entry index.html."""

    app_id: NotRequired[str]
    r"""normalized relative path, forward slashes, no .. or leading /"""
    limit: NotRequired[int]
    offset: NotRequired[int]


class TextqlRPCPublicAppListAppVersionsRequest(BaseModel):
    r"""AppFile is one non-entry file of a multi-file app tree; code remains the entry index.html."""

    app_id: Annotated[Optional[str], pydantic.Field(alias="appId")] = None
    r"""normalized relative path, forward slashes, no .. or leading /"""

    limit: Optional[int] = None

    offset: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["appId", "limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAppListAppVersionsRequest.model_rebuild()
except NameError:
    pass
