"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_chartreference import (
    TextqlRPCPublicCellsChartReference,
    TextqlRPCPublicCellsChartReferenceTypedDict,
)
from .textql_rpc_public_cells_filereference import (
    TextqlRPCPublicCellsFileReference,
    TextqlRPCPublicCellsFileReferenceTypedDict,
)
from .textql_rpc_public_cells_imagereference import (
    TextqlRPCPublicCellsImageReference,
    TextqlRPCPublicCellsImageReferenceTypedDict,
)
from .textql_rpc_public_dataframe_dataframeinfo import (
    TextqlRPCPublicDataframeDataFrameInfo,
    TextqlRPCPublicDataframeDataFrameInfoTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicCellsPythonCellExecutionTimeMsTypedDict = TypeAliasType(
    "TextqlRPCPublicCellsPythonCellExecutionTimeMsTypedDict", Union[int, str]
)


TextqlRPCPublicCellsPythonCellExecutionTimeMs = TypeAliasType(
    "TextqlRPCPublicCellsPythonCellExecutionTimeMs", Union[int, str]
)


class TextqlRPCPublicCellsPythonCellTypedDict(TypedDict):
    code: NotRequired[str]
    output: NotRequired[List[str]]
    dataframe_info: NotRequired[List[TextqlRPCPublicDataframeDataFrameInfoTypedDict]]
    dataframe_preview: NotRequired[List[str]]
    images: NotRequired[List[TextqlRPCPublicCellsImageReferenceTypedDict]]
    files: NotRequired[List[TextqlRPCPublicCellsFileReferenceTypedDict]]
    html_screenshots: NotRequired[List[TextqlRPCPublicCellsImageReferenceTypedDict]]
    charts: NotRequired[List[TextqlRPCPublicCellsChartReferenceTypedDict]]
    auth_required: NotRequired[bool]
    r"""Per-member API OAuth auth hold fields"""
    auth_api_access_key_id: NotRequired[str]
    auth_provider_name: NotRequired[str]
    auth_completed: NotRequired[bool]
    auth_member: NotRequired[str]
    auth_permission_required: NotRequired[bool]
    auth_grant_type: NotRequired[str]
    execution_time_ms: NotRequired[
        Nullable[TextqlRPCPublicCellsPythonCellExecutionTimeMsTypedDict]
    ]


class TextqlRPCPublicCellsPythonCell(BaseModel):
    code: Optional[str] = None

    output: Optional[List[str]] = None

    dataframe_info: Annotated[
        Optional[List[TextqlRPCPublicDataframeDataFrameInfo]],
        pydantic.Field(alias="dataframeInfo"),
    ] = None

    dataframe_preview: Annotated[
        Optional[List[str]], pydantic.Field(alias="dataframePreview")
    ] = None

    images: Optional[List[TextqlRPCPublicCellsImageReference]] = None

    files: Optional[List[TextqlRPCPublicCellsFileReference]] = None

    html_screenshots: Annotated[
        Optional[List[TextqlRPCPublicCellsImageReference]],
        pydantic.Field(alias="htmlScreenshots"),
    ] = None

    charts: Optional[List[TextqlRPCPublicCellsChartReference]] = None

    auth_required: Annotated[Optional[bool], pydantic.Field(alias="authRequired")] = (
        None
    )
    r"""Per-member API OAuth auth hold fields"""

    auth_api_access_key_id: Annotated[
        Optional[str], pydantic.Field(alias="authApiAccessKeyId")
    ] = None

    auth_provider_name: Annotated[
        Optional[str], pydantic.Field(alias="authProviderName")
    ] = None

    auth_completed: Annotated[Optional[bool], pydantic.Field(alias="authCompleted")] = (
        None
    )

    auth_member: Annotated[Optional[str], pydantic.Field(alias="authMember")] = None

    auth_permission_required: Annotated[
        Optional[bool], pydantic.Field(alias="authPermissionRequired")
    ] = None

    auth_grant_type: Annotated[Optional[str], pydantic.Field(alias="authGrantType")] = (
        None
    )

    execution_time_ms: Annotated[
        OptionalNullable[TextqlRPCPublicCellsPythonCellExecutionTimeMs],
        pydantic.Field(alias="executionTimeMs"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "code",
                "output",
                "dataframeInfo",
                "dataframePreview",
                "images",
                "files",
                "htmlScreenshots",
                "charts",
                "authRequired",
                "authApiAccessKeyId",
                "authProviderName",
                "authCompleted",
                "authMember",
                "authPermissionRequired",
                "authGrantType",
                "executionTimeMs",
            ]
        )
        nullable_fields = set(["executionTimeMs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsPythonCell.model_rebuild()
except NameError:
    pass
