"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSlackSlackUserTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Slack user ID"""
    name: NotRequired[Nullable[str]]
    real_name: NotRequired[Nullable[str]]
    email: NotRequired[Nullable[str]]


class TextqlRPCPublicSlackSlackUser(BaseModel):
    id: Optional[str] = None
    r"""Slack user ID"""

    name: OptionalNullable[str] = UNSET

    real_name: Annotated[OptionalNullable[str], pydantic.Field(alias="realName")] = (
        UNSET
    )

    email: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "realName", "email"])
        nullable_fields = set(["name", "realName", "email"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicSlackSlackUser.model_rebuild()
except NameError:
    pass
