"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCParadigmParamsParadigmType = Union[
    Literal[
        "TYPE_UNKNOWN",
        "TYPE_SQL",
        "TYPE_RESEARCH",
        "TYPE_ONTOLOGY",
        "TYPE_BASIC",
        "TYPE_TABLEAU",
        "TYPE_EXPERIMENTAL",
        "TYPE_UNIVERSAL",
        "TYPE_PUBLIC_DEMO",
        "TYPE_SUMMARY",
        "TYPE_OBSERVABILITY",
        "TYPE_TEMPLATE",
        "TYPE_MINIMALIST",
        "TYPE_TOPICS",
    ],
    UnrecognizedStr,
]
