"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_dataframe_dataframefield import (
    TextqlRPCPublicDataframeDataFrameField,
    TextqlRPCPublicDataframeDataFrameFieldTypedDict,
)
from .textql_rpc_public_dataframe_dataframerecord import (
    TextqlRPCPublicDataframeDataFrameRecord,
    TextqlRPCPublicDataframeDataFrameRecordTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicDataframeDataFrameTypedDict(TypedDict):
    schema_: NotRequired[List[TextqlRPCPublicDataframeDataFrameFieldTypedDict]]
    records: NotRequired[List[TextqlRPCPublicDataframeDataFrameRecordTypedDict]]


class TextqlRPCPublicDataframeDataFrame(BaseModel):
    schema_: Annotated[
        Optional[List[TextqlRPCPublicDataframeDataFrameField]],
        pydantic.Field(alias="schema"),
    ] = None

    records: Optional[List[TextqlRPCPublicDataframeDataFrameRecord]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["schema", "records"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicDataframeDataFrame.model_rebuild()
except NameError:
    pass
