"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsOntologyQueryParamTypedDict(TypedDict):
    name: NotRequired[str]
    type: NotRequired[str]
    nullable: NotRequired[bool]
    description: NotRequired[Nullable[str]]
    default_value: NotRequired[Nullable[str]]


class TextqlRPCPublicCellsOntologyQueryParam(BaseModel):
    name: Optional[str] = None

    type: Optional[str] = None

    nullable: Optional[bool] = None

    description: OptionalNullable[str] = UNSET

    default_value: Annotated[
        OptionalNullable[str], pydantic.Field(alias="defaultValue")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "type", "nullable", "description", "defaultValue"]
        )
        nullable_fields = set(["description", "defaultValue"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsOntologyQueryParam.model_rebuild()
except NameError:
    pass
