"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesAutoAttachEntryTypedDict(TypedDict):
    path: NotRequired[str]
    connector_id: NotRequired[int]
    api_connector_ids: NotRequired[List[str]]
    role_ids: NotRequired[List[str]]
    connector_ids: NotRequired[List[int]]
    match_no_connector: NotRequired[bool]
    match_no_api_connector: NotRequired[bool]
    match_all: NotRequired[bool]


class TextqlRPCPublicPatchesAutoAttachEntry(BaseModel):
    path: Optional[str] = None

    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    api_connector_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="apiConnectorIds")
    ] = None

    role_ids: Annotated[Optional[List[str]], pydantic.Field(alias="roleIds")] = None

    connector_ids: Annotated[
        Optional[List[int]], pydantic.Field(alias="connectorIds")
    ] = None

    match_no_connector: Annotated[
        Optional[bool], pydantic.Field(alias="matchNoConnector")
    ] = None

    match_no_api_connector: Annotated[
        Optional[bool], pydantic.Field(alias="matchNoApiConnector")
    ] = None

    match_all: Annotated[Optional[bool], pydantic.Field(alias="matchAll")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "path",
                "connectorId",
                "apiConnectorIds",
                "roleIds",
                "connectorIds",
                "matchNoConnector",
                "matchNoApiConnector",
                "matchAll",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesAutoAttachEntry.model_rebuild()
except NameError:
    pass
