"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_agent_slackagenttrigger import (
    TextqlRPCPublicAgentSlackAgentTrigger,
    TextqlRPCPublicAgentSlackAgentTriggerTypedDict,
)
from .textql_rpc_public_chat_llmmodel import TextqlRPCPublicChatLlmModel
from .textql_rpc_public_paradigm_paradigmoptions import (
    TextqlRPCPublicParadigmParadigmOptions,
    TextqlRPCPublicParadigmParadigmOptionsTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAgentCreateAgentRequestTypedDict(TypedDict):
    name: NotRequired[str]
    prompt: NotRequired[str]
    paradigm_options: NotRequired[TextqlRPCPublicParadigmParadigmOptionsTypedDict]
    source_suggestion_id: NotRequired[str]
    slack_channel_id: NotRequired[Nullable[str]]
    slack_dm_user_ids: NotRequired[List[str]]
    skip_org_default_channel: NotRequired[bool]
    llm_model: NotRequired[TextqlRPCPublicChatLlmModel]
    fast_mode: NotRequired[Nullable[bool]]
    is_stateful: NotRequired[Nullable[bool]]
    posting_frequency_crons: NotRequired[List[str]]
    email_recipient_member_ids: NotRequired[List[str]]
    channel_ids: NotRequired[List[str]]
    teams_channel_id: NotRequired[Nullable[str]]
    teams_dm_user_aad_ids: NotRequired[List[str]]
    slack_trigger: NotRequired[TextqlRPCPublicAgentSlackAgentTriggerTypedDict]
    posting_frequency_cadences: NotRequired[List[str]]
    r"""Index-aligned with posting_frequency_crons. A non-empty cadence
    (HOURLY/FOUR-HOUR/EIGHT-HOUR/DAILY/WEEKLY) marks a flexible schedule whose
    cron the backend generates; \"\" (or an empty list) means exact.
    """


class TextqlRPCPublicAgentCreateAgentRequest(BaseModel):
    name: Optional[str] = None

    prompt: Optional[str] = None

    paradigm_options: Annotated[
        Optional[TextqlRPCPublicParadigmParadigmOptions],
        pydantic.Field(alias="paradigmOptions"),
    ] = None

    source_suggestion_id: Annotated[
        Optional[str], pydantic.Field(alias="sourceSuggestionId")
    ] = None

    slack_channel_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="slackChannelId")
    ] = UNSET

    slack_dm_user_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="slackDmUserIds")
    ] = None

    skip_org_default_channel: Annotated[
        Optional[bool], pydantic.Field(alias="skipOrgDefaultChannel")
    ] = None

    llm_model: Annotated[
        Optional[TextqlRPCPublicChatLlmModel], pydantic.Field(alias="llmModel")
    ] = None

    fast_mode: Annotated[OptionalNullable[bool], pydantic.Field(alias="fastMode")] = (
        UNSET
    )

    is_stateful: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isStateful")
    ] = UNSET

    posting_frequency_crons: Annotated[
        Optional[List[str]], pydantic.Field(alias="postingFrequencyCrons")
    ] = None

    email_recipient_member_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="emailRecipientMemberIds")
    ] = None

    channel_ids: Annotated[Optional[List[str]], pydantic.Field(alias="channelIds")] = (
        None
    )

    teams_channel_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="teamsChannelId")
    ] = UNSET

    teams_dm_user_aad_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="teamsDmUserAadIds")
    ] = None

    slack_trigger: Annotated[
        Optional[TextqlRPCPublicAgentSlackAgentTrigger],
        pydantic.Field(alias="slackTrigger"),
    ] = None

    posting_frequency_cadences: Annotated[
        Optional[List[str]], pydantic.Field(alias="postingFrequencyCadences")
    ] = None
    r"""Index-aligned with posting_frequency_crons. A non-empty cadence
    (HOURLY/FOUR-HOUR/EIGHT-HOUR/DAILY/WEEKLY) marks a flexible schedule whose
    cron the backend generates; \"\" (or an empty list) means exact.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "prompt",
                "paradigmOptions",
                "sourceSuggestionId",
                "slackChannelId",
                "slackDmUserIds",
                "skipOrgDefaultChannel",
                "llmModel",
                "fastMode",
                "isStateful",
                "postingFrequencyCrons",
                "emailRecipientMemberIds",
                "channelIds",
                "teamsChannelId",
                "teamsDmUserAadIds",
                "slackTrigger",
                "postingFrequencyCadences",
            ]
        )
        nullable_fields = set(
            ["slackChannelId", "fastMode", "isStateful", "teamsChannelId"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicAgentCreateAgentRequest.model_rebuild()
except NameError:
    pass
