"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_athenametadata_athenaauth_accesskeycredentials import (
    TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentials,
    TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentialsTypedDict,
)
from .textql_rpc_public_connector_athenametadata_athenaauth_iamrolecredentials import (
    TextqlRPCPublicConnectorAthenaMetadataAthenaAuthIAMRoleCredentials,
    TextqlRPCPublicConnectorAthenaMetadataAthenaAuthIAMRoleCredentialsTypedDict,
)
import pydantic
from textql_sdk.types import BaseModel
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class IamRoleTypedDict(TypedDict):
    iam_role: (
        TextqlRPCPublicConnectorAthenaMetadataAthenaAuthIAMRoleCredentialsTypedDict
    )


class IamRole(BaseModel):
    iam_role: Annotated[
        TextqlRPCPublicConnectorAthenaMetadataAthenaAuthIAMRoleCredentials,
        pydantic.Field(alias="iamRole"),
    ]


class AccessKeyTypedDict(TypedDict):
    access_key: (
        TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentialsTypedDict
    )


class AccessKey(BaseModel):
    access_key: Annotated[
        TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentials,
        pydantic.Field(alias="accessKey"),
    ]


TextqlRPCPublicConnectorAthenaMetadataAthenaAuthTypedDict = TypeAliasType(
    "TextqlRPCPublicConnectorAthenaMetadataAthenaAuthTypedDict",
    Union[AccessKeyTypedDict, IamRoleTypedDict],
)


TextqlRPCPublicConnectorAthenaMetadataAthenaAuth = TypeAliasType(
    "TextqlRPCPublicConnectorAthenaMetadataAthenaAuth", Union[AccessKey, IamRole]
)


try:
    IamRole.model_rebuild()
except NameError:
    pass
try:
    AccessKey.model_rebuild()
except NameError:
    pass
