"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicCellsQuestionKind = Union[
    Literal[
        "QUESTION_KIND_UNKNOWN",
        "QUESTION_KIND_CHOICE",
        "QUESTION_KIND_MULTICHOICE",
        "QUESTION_KIND_INPUTS",
    ],
    UnrecognizedStr,
]
