"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_llmmodel import TextqlRPCPublicChatLlmModel
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicRbacUpdateRoleRequestTypedDict(TypedDict):
    role_id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    allow_model_choice: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    clear_allowed_model_ids: NotRequired[bool]
    allowed_models: NotRequired[List[TextqlRPCPublicChatLlmModel]]
    default_model: NotRequired[TextqlRPCPublicChatLlmModel]


class TextqlRPCPublicRbacUpdateRoleRequest(BaseModel):
    role_id: Annotated[Optional[str], pydantic.Field(alias="roleId")] = None

    name: Optional[str] = None

    description: Optional[str] = None

    allow_model_choice: Annotated[
        Optional[bool], pydantic.Field(alias="allowModelChoice")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    clear_allowed_model_ids: Annotated[
        Optional[bool], pydantic.Field(alias="clearAllowedModelIds")
    ] = None

    allowed_models: Annotated[
        Optional[List[TextqlRPCPublicChatLlmModel]],
        pydantic.Field(alias="allowedModels"),
    ] = None

    default_model: Annotated[
        Optional[TextqlRPCPublicChatLlmModel], pydantic.Field(alias="defaultModel")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "roleId",
                "name",
                "description",
                "allowModelChoice",
                "clearAllowedModelIds",
                "allowedModels",
                "defaultModel",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicRbacUpdateRoleRequest.model_rebuild()
except NameError:
    pass
