"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_observe_threadwarninglist import (
    TextqlRPCPublicObserveThreadWarningList,
    TextqlRPCPublicObserveThreadWarningListTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicObserveGetThreadWarningsResponseTypedDict(TypedDict):
    warnings_by_chat: NotRequired[
        Dict[str, TextqlRPCPublicObserveThreadWarningListTypedDict]
    ]
    analyzed_chat_ids: NotRequired[List[str]]


class TextqlRPCPublicObserveGetThreadWarningsResponse(BaseModel):
    warnings_by_chat: Annotated[
        Optional[Dict[str, TextqlRPCPublicObserveThreadWarningList]],
        pydantic.Field(alias="warningsByChat"),
    ] = None

    analyzed_chat_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="analyzedChatIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["warningsByChat", "analyzedChatIds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicObserveGetThreadWarningsResponse.model_rebuild()
except NameError:
    pass
