"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_emailattachment import (
    TextqlRPCPublicCellsEmailAttachment,
    TextqlRPCPublicCellsEmailAttachmentTypedDict,
)
from .textql_rpc_public_cells_emailrecipient import (
    TextqlRPCPublicCellsEmailRecipient,
    TextqlRPCPublicCellsEmailRecipientTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsEmailCellTypedDict(TypedDict):
    to: NotRequired[List[str]]
    subject: NotRequired[str]
    body: NotRequired[str]
    recipients: NotRequired[List[TextqlRPCPublicCellsEmailRecipientTypedDict]]
    status: NotRequired[str]
    sent_at: NotRequired[Nullable[str]]
    message_id: NotRequired[Nullable[str]]
    error_message: NotRequired[Nullable[str]]
    error_class: NotRequired[Nullable[str]]
    sent_count: NotRequired[int]
    rendered_body_html: NotRequired[Nullable[str]]
    attachments: NotRequired[List[TextqlRPCPublicCellsEmailAttachmentTypedDict]]


class TextqlRPCPublicCellsEmailCell(BaseModel):
    to: Optional[List[str]] = None

    subject: Optional[str] = None

    body: Optional[str] = None

    recipients: Optional[List[TextqlRPCPublicCellsEmailRecipient]] = None

    status: Optional[str] = None

    sent_at: Annotated[OptionalNullable[str], pydantic.Field(alias="sentAt")] = UNSET

    message_id: Annotated[OptionalNullable[str], pydantic.Field(alias="messageId")] = (
        UNSET
    )

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    error_class: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorClass")
    ] = UNSET

    sent_count: Annotated[Optional[int], pydantic.Field(alias="sentCount")] = None

    rendered_body_html: Annotated[
        OptionalNullable[str], pydantic.Field(alias="renderedBodyHtml")
    ] = UNSET

    attachments: Optional[List[TextqlRPCPublicCellsEmailAttachment]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "to",
                "subject",
                "body",
                "recipients",
                "status",
                "sentAt",
                "messageId",
                "errorMessage",
                "errorClass",
                "sentCount",
                "renderedBodyHtml",
                "attachments",
            ]
        )
        nullable_fields = set(
            ["sentAt", "messageId", "errorMessage", "errorClass", "renderedBodyHtml"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsEmailCell.model_rebuild()
except NameError:
    pass
