"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_rbac_apikey import (
    TextqlRPCPublicRbacAPIKey,
    TextqlRPCPublicRbacAPIKeyTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicRbacRotateAPIKeyResponseTypedDict(TypedDict):
    api_key: NotRequired[TextqlRPCPublicRbacAPIKeyTypedDict]
    r"""Get current member roles and permissions messages"""
    api_key_secret: NotRequired[str]
    revoked_api_key_id: NotRequired[str]


class TextqlRPCPublicRbacRotateAPIKeyResponse(BaseModel):
    api_key: Annotated[
        Optional[TextqlRPCPublicRbacAPIKey], pydantic.Field(alias="apiKey")
    ] = None
    r"""Get current member roles and permissions messages"""

    api_key_secret: Annotated[Optional[str], pydantic.Field(alias="apiKeySecret")] = (
        None
    )

    revoked_api_key_id: Annotated[
        Optional[str], pydantic.Field(alias="revokedApiKeyId")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apiKey", "apiKeySecret", "revokedApiKeyId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicRbacRotateAPIKeyResponse.model_rebuild()
except NameError:
    pass
