"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicConnectorDailyDurationTotalMsTypedDict = TypeAliasType(
    "TextqlRPCPublicConnectorDailyDurationTotalMsTypedDict", Union[int, str]
)


TextqlRPCPublicConnectorDailyDurationTotalMs = TypeAliasType(
    "TextqlRPCPublicConnectorDailyDurationTotalMs", Union[int, str]
)


class TextqlRPCPublicConnectorDailyDurationTypedDict(TypedDict):
    date_: NotRequired[str]
    total_ms: NotRequired[TextqlRPCPublicConnectorDailyDurationTotalMsTypedDict]


class TextqlRPCPublicConnectorDailyDuration(BaseModel):
    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    total_ms: Annotated[
        Optional[TextqlRPCPublicConnectorDailyDurationTotalMs],
        pydantic.Field(alias="totalMs"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["date", "totalMs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorDailyDuration.model_rebuild()
except NameError:
    pass
