"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSettingsCheckMemberStatusResponseTypedDict(TypedDict):
    is_suspended: NotRequired[bool]
    console_access: NotRequired[bool]
    is_suspended_manual: NotRequired[bool]
    is_suspended_overage: NotRequired[bool]
    is_suspended_usage: NotRequired[bool]
    is_suspended_member_usage: NotRequired[bool]
    suspension_message: NotRequired[str]
    suspended_cost_centers: NotRequired[List[str]]
    is_suspended_org_limit: NotRequired[bool]


class TextqlRPCPublicSettingsCheckMemberStatusResponse(BaseModel):
    is_suspended: Annotated[Optional[bool], pydantic.Field(alias="isSuspended")] = None

    console_access: Annotated[Optional[bool], pydantic.Field(alias="consoleAccess")] = (
        None
    )

    is_suspended_manual: Annotated[
        Optional[bool], pydantic.Field(alias="isSuspendedManual")
    ] = None

    is_suspended_overage: Annotated[
        Optional[bool], pydantic.Field(alias="isSuspendedOverage")
    ] = None

    is_suspended_usage: Annotated[
        Optional[bool], pydantic.Field(alias="isSuspendedUsage")
    ] = None

    is_suspended_member_usage: Annotated[
        Optional[bool], pydantic.Field(alias="isSuspendedMemberUsage")
    ] = None

    suspension_message: Annotated[
        Optional[str], pydantic.Field(alias="suspensionMessage")
    ] = None

    suspended_cost_centers: Annotated[
        Optional[List[str]], pydantic.Field(alias="suspendedCostCenters")
    ] = None

    is_suspended_org_limit: Annotated[
        Optional[bool], pydantic.Field(alias="isSuspendedOrgLimit")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "isSuspended",
                "consoleAccess",
                "isSuspendedManual",
                "isSuspendedOverage",
                "isSuspendedUsage",
                "isSuspendedMemberUsage",
                "suspensionMessage",
                "suspendedCostCenters",
                "isSuspendedOrgLimit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicSettingsCheckMemberStatusResponse.model_rebuild()
except NameError:
    pass
