"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsCitationLineageNodeTypedDict(TypedDict):
    r"""QuestionsCell is the agent's \"ask the user structured questions\" tool. It is a
    haltable cell: the agent pauses until the user submits or dismisses inline.
    On submit the answers go to the agent; on dismiss only the answered count does
    and the agent waits for the user's next message (the dismissal reason).
    """

    cell_id: NotRequired[str]
    kind: NotRequired[str]
    dataframe_name: NotRequired[Nullable[str]]
    r"""prefill (pending) / summary (answered); sensitive values blanked"""
    connector_id: NotRequired[Nullable[int]]
    tables: NotRequired[List[str]]
    input_cell_ids: NotRequired[List[str]]


class TextqlRPCPublicCellsCitationLineageNode(BaseModel):
    r"""QuestionsCell is the agent's \"ask the user structured questions\" tool. It is a
    haltable cell: the agent pauses until the user submits or dismisses inline.
    On submit the answers go to the agent; on dismiss only the answered count does
    and the agent waits for the user's next message (the dismissal reason).
    """

    cell_id: Annotated[Optional[str], pydantic.Field(alias="cellId")] = None

    kind: Optional[str] = None

    dataframe_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="dataframeName")
    ] = UNSET
    r"""prefill (pending) / summary (answered); sensitive values blanked"""

    connector_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="connectorId")
    ] = UNSET

    tables: Optional[List[str]] = None

    input_cell_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="inputCellIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cellId", "kind", "dataframeName", "connectorId", "tables", "inputCellIds"]
        )
        nullable_fields = set(["dataframeName", "connectorId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsCitationLineageNode.model_rebuild()
except NameError:
    pass
