"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAppListAppsRequestTypedDict(TypedDict):
    search_term: NotRequired[Nullable[str]]
    limit: NotRequired[int]
    offset: NotRequired[int]
    folder_id: NotRequired[Nullable[str]]
    r"""Filter by specific folder"""
    uncategorized_only: NotRequired[Nullable[bool]]
    r"""Only show apps with no folder"""
    shared_with_me: NotRequired[Nullable[bool]]
    r"""Only apps shared with the caller (not authored by them)"""


class TextqlRPCPublicAppListAppsRequest(BaseModel):
    search_term: Annotated[
        OptionalNullable[str], pydantic.Field(alias="searchTerm")
    ] = UNSET

    limit: Optional[int] = None

    offset: Optional[int] = None

    folder_id: Annotated[OptionalNullable[str], pydantic.Field(alias="folderId")] = (
        UNSET
    )
    r"""Filter by specific folder"""

    uncategorized_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="uncategorizedOnly")
    ] = UNSET
    r"""Only show apps with no folder"""

    shared_with_me: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="sharedWithMe")
    ] = UNSET
    r"""Only apps shared with the caller (not authored by them)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "searchTerm",
                "limit",
                "offset",
                "folderId",
                "uncategorizedOnly",
                "sharedWithMe",
            ]
        )
        nullable_fields = set(
            ["searchTerm", "folderId", "uncategorizedOnly", "sharedWithMe"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicAppListAppsRequest.model_rebuild()
except NameError:
    pass
