"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesPatchCapabilitiesTypedDict(TypedDict):
    can_approve: NotRequired[bool]
    can_deny: NotRequired[bool]
    can_restore: NotRequired[bool]
    caller_approved: NotRequired[bool]


class TextqlRPCPublicPatchesPatchCapabilities(BaseModel):
    can_approve: Annotated[Optional[bool], pydantic.Field(alias="canApprove")] = None

    can_deny: Annotated[Optional[bool], pydantic.Field(alias="canDeny")] = None

    can_restore: Annotated[Optional[bool], pydantic.Field(alias="canRestore")] = None

    caller_approved: Annotated[
        Optional[bool], pydantic.Field(alias="callerApproved")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["canApprove", "canDeny", "canRestore", "callerApproved"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesPatchCapabilities.model_rebuild()
except NameError:
    pass
