"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAppSetAppMemberStateRequestTypedDict(TypedDict):
    app_id: NotRequired[str]
    value_json: NotRequired[str]
    r"""whole-object JSON, last-write-wins, max 64KB"""


class TextqlRPCPublicAppSetAppMemberStateRequest(BaseModel):
    app_id: Annotated[Optional[str], pydantic.Field(alias="appId")] = None

    value_json: Annotated[Optional[str], pydantic.Field(alias="valueJson")] = None
    r"""whole-object JSON, last-write-wins, max 64KB"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["appId", "valueJson"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAppSetAppMemberStateRequest.model_rebuild()
except NameError:
    pass
