"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_teams_teamsuser import (
    TextqlRPCPublicTeamsTeamsUser,
    TextqlRPCPublicTeamsTeamsUserTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicTeamsTeamsGetCurrentUserResponseTypedDict(TypedDict):
    user: NotRequired[TextqlRPCPublicTeamsTeamsUserTypedDict]


class TextqlRPCPublicTeamsTeamsGetCurrentUserResponse(BaseModel):
    user: Optional[TextqlRPCPublicTeamsTeamsUser] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["user"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
