"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CountTypedDict = TypeAliasType("CountTypedDict", Union[int, str])


Count = TypeAliasType("Count", Union[int, str])


class TextqlRPCPublicConnectorDailyQueryCountTypedDict(TypedDict):
    date_: NotRequired[str]
    count: NotRequired[CountTypedDict]


class TextqlRPCPublicConnectorDailyQueryCount(BaseModel):
    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    count: Optional[Count] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["date", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorDailyQueryCount.model_rebuild()
except NameError:
    pass
