"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsFieldChangeTypedDict(TypedDict):
    field_name: NotRequired[str]
    old_value: NotRequired[str]
    new_value: NotRequired[str]


class TextqlRPCPublicCellsFieldChange(BaseModel):
    field_name: Annotated[Optional[str], pydantic.Field(alias="fieldName")] = None

    old_value: Annotated[Optional[str], pydantic.Field(alias="oldValue")] = None

    new_value: Annotated[Optional[str], pydantic.Field(alias="newValue")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fieldName", "oldValue", "newValue"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsFieldChange.model_rebuild()
except NameError:
    pass
