"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPlaybookDemoPlaybookRequestTypedDict(TypedDict):
    chat_id: NotRequired[str]
    person_name: NotRequired[str]
    job_title: NotRequired[str]
    target_email: NotRequired[str]


class TextqlRPCPublicPlaybookDemoPlaybookRequest(BaseModel):
    chat_id: Annotated[Optional[str], pydantic.Field(alias="chatId")] = None

    person_name: Annotated[Optional[str], pydantic.Field(alias="personName")] = None

    job_title: Annotated[Optional[str], pydantic.Field(alias="jobTitle")] = None

    target_email: Annotated[Optional[str], pydantic.Field(alias="targetEmail")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["chatId", "personName", "jobTitle", "targetEmail"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPlaybookDemoPlaybookRequest.model_rebuild()
except NameError:
    pass
