"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_autoattachentry import (
    TextqlRPCPublicPatchesAutoAttachEntry,
    TextqlRPCPublicPatchesAutoAttachEntryTypedDict,
)
from .textql_rpc_public_patches_codeownerentry import (
    TextqlRPCPublicPatchesCodeownerEntry,
    TextqlRPCPublicPatchesCodeownerEntryTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesUpsertLibraryAnaConfigRequestTypedDict(TypedDict):
    path: NotRequired[str]
    auto_attach: NotRequired[List[TextqlRPCPublicPatchesAutoAttachEntryTypedDict]]
    commit_message: NotRequired[Nullable[str]]
    codeowners: NotRequired[List[TextqlRPCPublicPatchesCodeownerEntryTypedDict]]


class TextqlRPCPublicPatchesUpsertLibraryAnaConfigRequest(BaseModel):
    path: Optional[str] = None

    auto_attach: Annotated[
        Optional[List[TextqlRPCPublicPatchesAutoAttachEntry]],
        pydantic.Field(alias="autoAttach"),
    ] = None

    commit_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="commitMessage")
    ] = UNSET

    codeowners: Optional[List[TextqlRPCPublicPatchesCodeownerEntry]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "autoAttach", "commitMessage", "codeowners"])
        nullable_fields = set(["commitMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesUpsertLibraryAnaConfigRequest.model_rebuild()
except NameError:
    pass
