"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicCellsTextCellSizeBytesTypedDict = TypeAliasType(
    "TextqlRPCPublicCellsTextCellSizeBytesTypedDict", Union[int, str]
)


TextqlRPCPublicCellsTextCellSizeBytes = TypeAliasType(
    "TextqlRPCPublicCellsTextCellSizeBytes", Union[int, str]
)


class TextqlRPCPublicCellsTextCellTypedDict(TypedDict):
    file_name: NotRequired[str]
    content: NotRequired[str]
    mime_type: NotRequired[str]
    size_bytes: NotRequired[TextqlRPCPublicCellsTextCellSizeBytesTypedDict]
    dataset_source_id: NotRequired[str]
    line_count: NotRequired[int]


class TextqlRPCPublicCellsTextCell(BaseModel):
    file_name: Annotated[Optional[str], pydantic.Field(alias="fileName")] = None

    content: Optional[str] = None

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None

    size_bytes: Annotated[
        Optional[TextqlRPCPublicCellsTextCellSizeBytes],
        pydantic.Field(alias="sizeBytes"),
    ] = None

    dataset_source_id: Annotated[
        Optional[str], pydantic.Field(alias="datasetSourceId")
    ] = None

    line_count: Annotated[Optional[int], pydantic.Field(alias="lineCount")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "fileName",
                "content",
                "mimeType",
                "sizeBytes",
                "datasetSourceId",
                "lineCount",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsTextCell.model_rebuild()
except NameError:
    pass
