"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicCellsPlaybookEditorAction = Union[
    Literal[
        "PLAYBOOK_ACTION_UNKNOWN",
        "PLAYBOOK_ACTION_LIST",
        "PLAYBOOK_ACTION_GET",
        "PLAYBOOK_ACTION_CREATE",
        "PLAYBOOK_ACTION_UPDATE",
        "PLAYBOOK_ACTION_RUN",
    ],
    UnrecognizedStr,
]
