"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_exasearchresult import (
    TextqlRPCPublicCellsExaSearchResult,
    TextqlRPCPublicCellsExaSearchResultTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMsTypedDict = TypeAliasType(
    "TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMsTypedDict", Union[int, str]
)


TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMs = TypeAliasType(
    "TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMs", Union[int, str]
)


class TextqlRPCPublicCellsLinkedinSearchCellTypedDict(TypedDict):
    query: NotRequired[str]
    exa_results: NotRequired[List[TextqlRPCPublicCellsExaSearchResultTypedDict]]
    cost_dollars: NotRequired[Nullable[float]]
    execution_time_ms: NotRequired[
        Nullable[TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMsTypedDict]
    ]


class TextqlRPCPublicCellsLinkedinSearchCell(BaseModel):
    query: Optional[str] = None

    exa_results: Annotated[
        Optional[List[TextqlRPCPublicCellsExaSearchResult]],
        pydantic.Field(alias="exaResults"),
    ] = None

    cost_dollars: Annotated[
        OptionalNullable[float], pydantic.Field(alias="costDollars")
    ] = UNSET

    execution_time_ms: Annotated[
        OptionalNullable[TextqlRPCPublicCellsLinkedinSearchCellExecutionTimeMs],
        pydantic.Field(alias="executionTimeMs"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["query", "exaResults", "costDollars", "executionTimeMs"])
        nullable_fields = set(["costDollars", "executionTimeMs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsLinkedinSearchCell.model_rebuild()
except NameError:
    pass
