"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicSecretAPIAuthType = Union[
    Literal[
        "API_AUTH_TYPE_UNSPECIFIED",
        "API_AUTH_TYPE_TOKEN",
        "API_AUTH_TYPE_OAUTH_U2M",
        "API_AUTH_TYPE_OAUTH_PER_MEMBER",
        "API_AUTH_TYPE_ENV_VAR",
        "API_AUTH_TYPE_NONE",
        "API_AUTH_TYPE_OTHER",
    ],
    UnrecognizedStr,
]
r"""Authentication mode for an API connector. Provider templates have a separate
auth_type describing how their credentials are entered (e.g. basic_auth).
OAUTH_U2M shares one OAuth account among members with connector access;
OAUTH_PER_MEMBER requires each member to connect their own account.
"""
