"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_dataframe_boolvalues import (
    TextqlRPCPublicDataframeBoolValues,
    TextqlRPCPublicDataframeBoolValuesTypedDict,
)
from .textql_rpc_public_dataframe_bytevalues import (
    TextqlRPCPublicDataframeByteValues,
    TextqlRPCPublicDataframeByteValuesTypedDict,
)
from .textql_rpc_public_dataframe_doublevalues import (
    TextqlRPCPublicDataframeDoubleValues,
    TextqlRPCPublicDataframeDoubleValuesTypedDict,
)
from .textql_rpc_public_dataframe_floatvalues import (
    TextqlRPCPublicDataframeFloatValues,
    TextqlRPCPublicDataframeFloatValuesTypedDict,
)
from .textql_rpc_public_dataframe_int32values import (
    TextqlRPCPublicDataframeInt32Values,
    TextqlRPCPublicDataframeInt32ValuesTypedDict,
)
from .textql_rpc_public_dataframe_int64values import (
    TextqlRPCPublicDataframeInt64Values,
    TextqlRPCPublicDataframeInt64ValuesTypedDict,
)
from .textql_rpc_public_dataframe_stringvalues import (
    TextqlRPCPublicDataframeStringValues,
    TextqlRPCPublicDataframeStringValuesTypedDict,
)
from .textql_rpc_public_dataframe_timestampvalues import (
    TextqlRPCPublicDataframeTimestampValues,
    TextqlRPCPublicDataframeTimestampValuesTypedDict,
)
from .textql_rpc_public_dataframe_uint32values import (
    TextqlRPCPublicDataframeUint32Values,
    TextqlRPCPublicDataframeUint32ValuesTypedDict,
)
from .textql_rpc_public_dataframe_uint64values import (
    TextqlRPCPublicDataframeUint64Values,
    TextqlRPCPublicDataframeUint64ValuesTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class Uint64TypedDict(TypedDict):
    uint64: TextqlRPCPublicDataframeUint64ValuesTypedDict
    column_index: NotRequired[int]


class Uint64(BaseModel):
    uint64: TextqlRPCPublicDataframeUint64Values

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Uint32TypedDict(TypedDict):
    uint32: TextqlRPCPublicDataframeUint32ValuesTypedDict
    column_index: NotRequired[int]


class Uint32(BaseModel):
    uint32: TextqlRPCPublicDataframeUint32Values

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TimestampsTypedDict(TypedDict):
    timestamps: TextqlRPCPublicDataframeTimestampValuesTypedDict
    column_index: NotRequired[int]


class Timestamps(BaseModel):
    timestamps: TextqlRPCPublicDataframeTimestampValues

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StringsTypedDict(TypedDict):
    strings: TextqlRPCPublicDataframeStringValuesTypedDict
    column_index: NotRequired[int]


class Strings(BaseModel):
    strings: TextqlRPCPublicDataframeStringValues

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Int64TypedDict(TypedDict):
    int64: TextqlRPCPublicDataframeInt64ValuesTypedDict
    column_index: NotRequired[int]


class Int64(BaseModel):
    int64: TextqlRPCPublicDataframeInt64Values

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Int32TypedDict(TypedDict):
    int32: TextqlRPCPublicDataframeInt32ValuesTypedDict
    column_index: NotRequired[int]


class Int32(BaseModel):
    int32: TextqlRPCPublicDataframeInt32Values

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FloatsTypedDict(TypedDict):
    floats: TextqlRPCPublicDataframeFloatValuesTypedDict
    column_index: NotRequired[int]


class Floats(BaseModel):
    floats: TextqlRPCPublicDataframeFloatValues

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DoublesTypedDict(TypedDict):
    doubles: TextqlRPCPublicDataframeDoubleValuesTypedDict
    column_index: NotRequired[int]


class Doubles(BaseModel):
    doubles: TextqlRPCPublicDataframeDoubleValues

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BytesTypedDict(TypedDict):
    bytes_: TextqlRPCPublicDataframeByteValuesTypedDict
    column_index: NotRequired[int]


class Bytes(BaseModel):
    bytes_: Annotated[TextqlRPCPublicDataframeByteValues, pydantic.Field(alias="bytes")]

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BoolsTypedDict(TypedDict):
    bools: TextqlRPCPublicDataframeBoolValuesTypedDict
    column_index: NotRequired[int]


class Bools(BaseModel):
    bools: TextqlRPCPublicDataframeBoolValues

    column_index: Annotated[Optional[int], pydantic.Field(alias="columnIndex")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columnIndex"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


TextqlRPCPublicDataframeDataFrameColumnTypedDict = TypeAliasType(
    "TextqlRPCPublicDataframeDataFrameColumnTypedDict",
    Union[
        BoolsTypedDict,
        BytesTypedDict,
        DoublesTypedDict,
        FloatsTypedDict,
        Int32TypedDict,
        Int64TypedDict,
        StringsTypedDict,
        TimestampsTypedDict,
        Uint32TypedDict,
        Uint64TypedDict,
    ],
)


TextqlRPCPublicDataframeDataFrameColumn = TypeAliasType(
    "TextqlRPCPublicDataframeDataFrameColumn",
    Union[
        Bools, Bytes, Doubles, Floats, Int32, Int64, Strings, Timestamps, Uint32, Uint64
    ],
)


try:
    Uint64.model_rebuild()
except NameError:
    pass
try:
    Uint32.model_rebuild()
except NameError:
    pass
try:
    Timestamps.model_rebuild()
except NameError:
    pass
try:
    Strings.model_rebuild()
except NameError:
    pass
try:
    Int64.model_rebuild()
except NameError:
    pass
try:
    Int32.model_rebuild()
except NameError:
    pass
try:
    Floats.model_rebuild()
except NameError:
    pass
try:
    Doubles.model_rebuild()
except NameError:
    pass
try:
    Bytes.model_rebuild()
except NameError:
    pass
try:
    Bools.model_rebuild()
except NameError:
    pass
