"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_connectorconfig import (
    TextqlRPCPublicConnectorConnectorConfig,
    TextqlRPCPublicConnectorConnectorConfigTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorTestConnectorRequestTypedDict(TypedDict):
    config: NotRequired[TextqlRPCPublicConnectorConnectorConfigTypedDict]
    connector_id: NotRequired[Nullable[str]]
    r"""Optional: If provided, confidential fields will be preserved from the existing connector
    when the corresponding field in config is empty. This allows testing updates without
    requiring the user to re-enter credentials.
    """


class TextqlRPCPublicConnectorTestConnectorRequest(BaseModel):
    config: Optional[TextqlRPCPublicConnectorConnectorConfig] = None

    connector_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="connectorId")
    ] = UNSET
    r"""Optional: If provided, confidential fields will be preserved from the existing connector
    when the corresponding field in config is empty. This allows testing updates without
    requiring the user to re-enter credentials.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["config", "connectorId"])
        nullable_fields = set(["connectorId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorTestConnectorRequest.model_rebuild()
except NameError:
    pass
