"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from textql_sdk.types import BaseModel
from typing_extensions import Annotated, TypedDict


class TextqlRPCPublicChatRejectContextPromptChangeRequestTypedDict(TypedDict):
    r"""context prompt change management"""

    cell_id: str
    r"""UUID"""


class TextqlRPCPublicChatRejectContextPromptChangeRequest(BaseModel):
    r"""context prompt change management"""

    cell_id: Annotated[str, pydantic.Field(alias="cellId")]
    r"""UUID"""


try:
    TextqlRPCPublicChatRejectContextPromptChangeRequest.model_rebuild()
except NameError:
    pass
