"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorKdbMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    tls: NotRequired[bool]
    ssh_tunnel_enabled: NotRequired[bool]
    ssh_host: NotRequired[str]
    ssh_port: NotRequired[int]
    ssh_user: NotRequired[str]
    r"""PASSWORD, IAM_ROLE"""
    ssh_private_key: NotRequired[str]
    ssh_host_public_key: NotRequired[str]


class TextqlRPCPublicConnectorKdbMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    tls: Optional[bool] = None

    ssh_tunnel_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="sshTunnelEnabled")
    ] = None

    ssh_host: Annotated[Optional[str], pydantic.Field(alias="sshHost")] = None

    ssh_port: Annotated[Optional[int], pydantic.Field(alias="sshPort")] = None

    ssh_user: Annotated[Optional[str], pydantic.Field(alias="sshUser")] = None
    r"""PASSWORD, IAM_ROLE"""

    ssh_private_key: Annotated[Optional[str], pydantic.Field(alias="sshPrivateKey")] = (
        None
    )

    ssh_host_public_key: Annotated[
        Optional[str], pydantic.Field(alias="sshHostPublicKey")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "tls",
                "sshTunnelEnabled",
                "sshHost",
                "sshPort",
                "sshUser",
                "sshPrivateKey",
                "sshHostPublicKey",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorKdbMetadata.model_rebuild()
except NameError:
    pass
