"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_paradigm_params_paradigmparams import (
    TextqlRPCParadigmParamsParadigmParams,
    TextqlRPCParadigmParamsParadigmParamsTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSettingsUpdateOrganizationSettingsRequestTypedDict(TypedDict):
    org_id: NotRequired[str]
    hide_example_connectors: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    paradigm_params: NotRequired[TextqlRPCParadigmParamsParadigmParamsTypedDict]
    training_mode: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    dashboards_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    methodology_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    feed_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    observability_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    notifications_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    fast_mode_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    max_thinking_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    traces_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    sandbox_observability_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    data_apps_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """
    tool_restrictions: NotRequired[TextqlRPCParadigmParamsParadigmParamsTypedDict]
    subagents_enabled: NotRequired[bool]
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """


class TextqlRPCPublicSettingsUpdateOrganizationSettingsRequest(BaseModel):
    org_id: Annotated[Optional[str], pydantic.Field(alias="orgId")] = None

    hide_example_connectors: Annotated[
        Optional[bool], pydantic.Field(alias="hideExampleConnectors")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    paradigm_params: Annotated[
        Optional[TextqlRPCParadigmParamsParadigmParams],
        pydantic.Field(alias="paradigmParams"),
    ] = None

    training_mode: Annotated[Optional[bool], pydantic.Field(alias="trainingMode")] = (
        None
    )
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    dashboards_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="dashboardsEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    methodology_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="methodologyEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    feed_enabled: Annotated[Optional[bool], pydantic.Field(alias="feedEnabled")] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    observability_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="observabilityEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    notifications_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="notificationsEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    fast_mode_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="fastModeEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    max_thinking_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="maxThinkingEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    traces_enabled: Annotated[Optional[bool], pydantic.Field(alias="tracesEnabled")] = (
        None
    )
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    sandbox_observability_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="sandboxObservabilityEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    data_apps_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="dataAppsEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    tool_restrictions: Annotated[
        Optional[TextqlRPCParadigmParamsParadigmParams],
        pydantic.Field(alias="toolRestrictions"),
    ] = None

    subagents_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="subagentsEnabled")
    ] = None
    r"""Wrapper message for `bool`.

    The JSON representation for `BoolValue` is JSON `true` and `false`.

    Not recommended for use in new APIs, but still useful for legacy APIs and
    has no plan to be removed.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "orgId",
                "hideExampleConnectors",
                "paradigmParams",
                "trainingMode",
                "dashboardsEnabled",
                "methodologyEnabled",
                "feedEnabled",
                "observabilityEnabled",
                "notificationsEnabled",
                "fastModeEnabled",
                "maxThinkingEnabled",
                "tracesEnabled",
                "sandboxObservabilityEnabled",
                "dataAppsEnabled",
                "toolRestrictions",
                "subagentsEnabled",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicSettingsUpdateOrganizationSettingsRequest.model_rebuild()
except NameError:
    pass
