"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicObserveMemberBillingStatTypedDict(TypedDict):
    member_id: NotRequired[str]
    member_name: NotRequired[str]
    email: NotRequired[str]
    total_acu: NotRequired[float]
    acu_by_category: NotRequired[Dict[str, float]]
    r"""llm_tokens, compute_hours, cell_execution"""
    acu_by_source: NotRequired[Dict[str, float]]
    r"""chat, feed, observability"""
    profile_image_url: NotRequired[str]
    thread_count: NotRequired[int]
    playbook_count: NotRequired[int]
    dashboard_count: NotRequired[int]
    agent_count: NotRequired[int]
    is_former_member: NotRequired[bool]


class TextqlRPCPublicObserveMemberBillingStat(BaseModel):
    member_id: Annotated[Optional[str], pydantic.Field(alias="memberId")] = None

    member_name: Annotated[Optional[str], pydantic.Field(alias="memberName")] = None

    email: Optional[str] = None

    total_acu: Annotated[Optional[float], pydantic.Field(alias="totalAcu")] = None

    acu_by_category: Annotated[
        Optional[Dict[str, float]], pydantic.Field(alias="acuByCategory")
    ] = None
    r"""llm_tokens, compute_hours, cell_execution"""

    acu_by_source: Annotated[
        Optional[Dict[str, float]], pydantic.Field(alias="acuBySource")
    ] = None
    r"""chat, feed, observability"""

    profile_image_url: Annotated[
        Optional[str], pydantic.Field(alias="profileImageUrl")
    ] = None

    thread_count: Annotated[Optional[int], pydantic.Field(alias="threadCount")] = None

    playbook_count: Annotated[Optional[int], pydantic.Field(alias="playbookCount")] = (
        None
    )

    dashboard_count: Annotated[
        Optional[int], pydantic.Field(alias="dashboardCount")
    ] = None

    agent_count: Annotated[Optional[int], pydantic.Field(alias="agentCount")] = None

    is_former_member: Annotated[
        Optional[bool], pydantic.Field(alias="isFormerMember")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "memberId",
                "memberName",
                "email",
                "totalAcu",
                "acuByCategory",
                "acuBySource",
                "profileImageUrl",
                "threadCount",
                "playbookCount",
                "dashboardCount",
                "agentCount",
                "isFormerMember",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicObserveMemberBillingStat.model_rebuild()
except NameError:
    pass
