"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorMongoDBMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    database: NotRequired[str]
    r"""default database to query"""
    auth_source: NotRequired[str]
    r"""authSource (e.g. \"admin\"); defaults to database when empty"""
    tls: NotRequired[bool]
    srv: NotRequired[bool]
    r"""mongodb+srv connection (Atlas) — host is the cluster DNS name"""


class TextqlRPCPublicConnectorMongoDBMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    database: Optional[str] = None
    r"""default database to query"""

    auth_source: Annotated[Optional[str], pydantic.Field(alias="authSource")] = None
    r"""authSource (e.g. \"admin\"); defaults to database when empty"""

    tls: Optional[bool] = None

    srv: Optional[bool] = None
    r"""mongodb+srv connection (Atlas) — host is the cluster DNS name"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["host", "port", "user", "password", "database", "authSource", "tls", "srv"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorMongoDBMetadata.model_rebuild()
except NameError:
    pass
