"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_librarysizeday import (
    TextqlRPCPublicPatchesLibrarySizeDay,
    TextqlRPCPublicPatchesLibrarySizeDayTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicPatchesGetLibrarySizeTimelineResponseTypedDict(TypedDict):
    days: NotRequired[List[TextqlRPCPublicPatchesLibrarySizeDayTypedDict]]
    r"""one entry per UTC day, oldest first; days before the repo's first commit
    are omitted, and days without commits carry the previous day's tree
    """


class TextqlRPCPublicPatchesGetLibrarySizeTimelineResponse(BaseModel):
    days: Optional[List[TextqlRPCPublicPatchesLibrarySizeDay]] = None
    r"""one entry per UTC day, oldest first; days before the repo's first commit
    are omitted, and days without commits carry the previous day's tree
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["days"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
