"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorSnowflakeMetadataTypedDict(TypedDict):
    username: NotRequired[str]
    password: NotRequired[str]
    private_key: NotRequired[str]
    private_key_passphrase: NotRequired[str]
    role: NotRequired[str]
    r"""default database to query"""
    schema_: NotRequired[str]
    r"""authSource (e.g. \"admin\"); defaults to database when empty"""
    locator: NotRequired[str]
    database: NotRequired[str]
    r"""mongodb+srv connection (Atlas) — host is the cluster DNS name"""
    warehouse: NotRequired[str]
    oauth_access_token: NotRequired[str]
    oauth_refresh_token: NotRequired[str]
    oauth_client_id: NotRequired[str]
    oauth_client_secret: NotRequired[str]
    enable_sso_auth: NotRequired[bool]
    token_exchange_endpoint: NotRequired[str]
    token_exchange_audience: NotRequired[str]
    token_exchange_scope: NotRequired[str]


class TextqlRPCPublicConnectorSnowflakeMetadata(BaseModel):
    username: Optional[str] = None

    password: Optional[str] = None

    private_key: Annotated[Optional[str], pydantic.Field(alias="privateKey")] = None

    private_key_passphrase: Annotated[
        Optional[str], pydantic.Field(alias="privateKeyPassphrase")
    ] = None

    role: Optional[str] = None
    r"""default database to query"""

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = None
    r"""authSource (e.g. \"admin\"); defaults to database when empty"""

    locator: Optional[str] = None

    database: Optional[str] = None
    r"""mongodb+srv connection (Atlas) — host is the cluster DNS name"""

    warehouse: Optional[str] = None

    oauth_access_token: Annotated[
        Optional[str], pydantic.Field(alias="oauthAccessToken")
    ] = None

    oauth_refresh_token: Annotated[
        Optional[str], pydantic.Field(alias="oauthRefreshToken")
    ] = None

    oauth_client_id: Annotated[Optional[str], pydantic.Field(alias="oauthClientId")] = (
        None
    )

    oauth_client_secret: Annotated[
        Optional[str], pydantic.Field(alias="oauthClientSecret")
    ] = None

    enable_sso_auth: Annotated[
        Optional[bool], pydantic.Field(alias="enableSsoAuth")
    ] = None

    token_exchange_endpoint: Annotated[
        Optional[str], pydantic.Field(alias="tokenExchangeEndpoint")
    ] = None

    token_exchange_audience: Annotated[
        Optional[str], pydantic.Field(alias="tokenExchangeAudience")
    ] = None

    token_exchange_scope: Annotated[
        Optional[str], pydantic.Field(alias="tokenExchangeScope")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "username",
                "password",
                "privateKey",
                "privateKeyPassphrase",
                "role",
                "schema",
                "locator",
                "database",
                "warehouse",
                "oauthAccessToken",
                "oauthRefreshToken",
                "oauthClientId",
                "oauthClientSecret",
                "enableSsoAuth",
                "tokenExchangeEndpoint",
                "tokenExchangeAudience",
                "tokenExchangeScope",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorSnowflakeMetadata.model_rebuild()
except NameError:
    pass
