"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from textql_sdk.types import BaseModel
from typing_extensions import Annotated, TypedDict


class TextqlRPCPublicChatGetCompletionParametersRequestTypedDict(TypedDict):
    chat_id: str
    r"""UUID"""
    cell_id: str


class TextqlRPCPublicChatGetCompletionParametersRequest(BaseModel):
    chat_id: Annotated[str, pydantic.Field(alias="chatId")]
    r"""UUID"""

    cell_id: Annotated[str, pydantic.Field(alias="cellId")]


try:
    TextqlRPCPublicChatGetCompletionParametersRequest.model_rebuild()
except NameError:
    pass
