"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicOntologyLinkedAttributeDataTypedDict(TypedDict):
    relation_id: NotRequired[str]
    target_attribute_id: NotRequired[str]


class TextqlRPCPublicOntologyLinkedAttributeData(BaseModel):
    relation_id: Annotated[Optional[str], pydantic.Field(alias="relationId")] = None

    target_attribute_id: Annotated[
        Optional[str], pydantic.Field(alias="targetAttributeId")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["relationId", "targetAttributeId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicOntologyLinkedAttributeData.model_rebuild()
except NameError:
    pass
