"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_app_computefunctionparam import (
    TextqlRPCPublicAppComputeFunctionParam,
    TextqlRPCPublicAppComputeFunctionParamTypedDict,
)
from .textql_rpc_public_dashboard_grant import (
    TextqlRPCPublicDashboardGrant,
    TextqlRPCPublicDashboardGrantTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAppComputeFunctionTypedDict(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]
    params: NotRequired[List[TextqlRPCPublicAppComputeFunctionParamTypedDict]]
    returns: NotRequired[Nullable[str]]
    r"""Filter by specific folder"""
    code: NotRequired[str]
    r"""Only show apps with no folder"""
    tql_path: NotRequired[Nullable[str]]
    r"""Only apps shared with the caller (not authored by them)"""
    tql: NotRequired[Nullable[str]]
    grant: NotRequired[TextqlRPCPublicDashboardGrantTypedDict]
    r"""Grant is an author allowlist gating a data source or compute function. A viewer whose
    effective role names intersect roles, or whose member id is listed in members, may call it.
    Absent grant = org-visible (today's behavior); an empty grant object is invalid.
    """


class TextqlRPCPublicAppComputeFunction(BaseModel):
    name: Optional[str] = None

    description: Optional[str] = None

    params: Optional[List[TextqlRPCPublicAppComputeFunctionParam]] = None

    returns: OptionalNullable[str] = UNSET
    r"""Filter by specific folder"""

    code: Optional[str] = None
    r"""Only show apps with no folder"""

    tql_path: Annotated[OptionalNullable[str], pydantic.Field(alias="tqlPath")] = UNSET
    r"""Only apps shared with the caller (not authored by them)"""

    tql: OptionalNullable[str] = UNSET

    grant: Optional[TextqlRPCPublicDashboardGrant] = None
    r"""Grant is an author allowlist gating a data source or compute function. A viewer whose
    effective role names intersect roles, or whose member id is listed in members, may call it.
    Absent grant = org-visible (today's behavior); an empty grant object is invalid.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "description",
                "params",
                "returns",
                "code",
                "tqlPath",
                "tql",
                "grant",
            ]
        )
        nullable_fields = set(["returns", "tqlPath", "tql"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicAppComputeFunction.model_rebuild()
except NameError:
    pass
