"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicConnectorTopUserQueryCountTypedDict = TypeAliasType(
    "TextqlRPCPublicConnectorTopUserQueryCountTypedDict", Union[int, str]
)


TextqlRPCPublicConnectorTopUserQueryCount = TypeAliasType(
    "TextqlRPCPublicConnectorTopUserQueryCount", Union[int, str]
)


ChatCountTypedDict = TypeAliasType("ChatCountTypedDict", Union[int, str])


ChatCount = TypeAliasType("ChatCount", Union[int, str])


class TextqlRPCPublicConnectorTopUserTypedDict(TypedDict):
    member_id: NotRequired[str]
    display_name: NotRequired[str]
    email: NotRequired[str]
    query_count: NotRequired[TextqlRPCPublicConnectorTopUserQueryCountTypedDict]
    chat_count: NotRequired[ChatCountTypedDict]
    picture_url: NotRequired[str]


class TextqlRPCPublicConnectorTopUser(BaseModel):
    member_id: Annotated[Optional[str], pydantic.Field(alias="memberId")] = None

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None

    email: Optional[str] = None

    query_count: Annotated[
        Optional[TextqlRPCPublicConnectorTopUserQueryCount],
        pydantic.Field(alias="queryCount"),
    ] = None

    chat_count: Annotated[Optional[ChatCount], pydantic.Field(alias="chatCount")] = None

    picture_url: Annotated[Optional[str], pydantic.Field(alias="pictureUrl")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "memberId",
                "displayName",
                "email",
                "queryCount",
                "chatCount",
                "pictureUrl",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorTopUser.model_rebuild()
except NameError:
    pass
