"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicPatchesOntologyHistoryChangeType = Union[
    Literal[
        "ONTOLOGY_HISTORY_CHANGE_TYPE_UNSPECIFIED",
        "ONTOLOGY_HISTORY_CHANGE_TYPE_ADDED",
        "ONTOLOGY_HISTORY_CHANGE_TYPE_MODIFIED",
        "ONTOLOGY_HISTORY_CHANGE_TYPE_DELETED",
        "ONTOLOGY_HISTORY_CHANGE_TYPE_RENAMED",
    ],
    UnrecognizedStr,
]
