"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicParadigmTableauOptionsTypedDict(TypedDict):
    dataset_id: NotRequired[str]
    r"""id of dataset_version_tableau.dataset_id to use"""


class TextqlRPCPublicParadigmTableauOptions(BaseModel):
    dataset_id: Annotated[Optional[str], pydantic.Field(alias="datasetId")] = None
    r"""id of dataset_version_tableau.dataset_id to use"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["datasetId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicParadigmTableauOptions.model_rebuild()
except NameError:
    pass
