"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import BaseModel
from typing_extensions import TypedDict


class TextqlRPCPublicPatchesGetConfigExportCapabilitiesRequestTypedDict(TypedDict):
    r"""GetConfigExportCapabilities tells the UI whether to offer \"Save as config\":
    which object types currently have a working exporter (registered AND its
    dependencies — e.g. the ontology parser — reachable), and whether the caller
    holds the permission SaveObjectAsConfig requires. Authn-only: the response
    carries the authorization answer instead of failing the call.
    """


class TextqlRPCPublicPatchesGetConfigExportCapabilitiesRequest(BaseModel):
    r"""GetConfigExportCapabilities tells the UI whether to offer \"Save as config\":
    which object types currently have a working exporter (registered AND its
    dependencies — e.g. the ontology parser — reachable), and whether the caller
    holds the permission SaveObjectAsConfig requires. Authn-only: the response
    carries the authorization answer instead of failing the call.
    """
