"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_powerbi_powerbireport import (
    TextqlRPCPublicPowerbiPowerBIReport,
    TextqlRPCPublicPowerbiPowerBIReportTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicPowerbiListPowerBIReportsResponseTypedDict(TypedDict):
    reports: NotRequired[List[TextqlRPCPublicPowerbiPowerBIReportTypedDict]]
    error: NotRequired[Nullable[str]]


class TextqlRPCPublicPowerbiListPowerBIReportsResponse(BaseModel):
    reports: Optional[List[TextqlRPCPublicPowerbiPowerBIReport]] = None

    error: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reports", "error"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
