"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorAuroraMetadataAuroraAuthTypedDict(TypedDict):
    iam_auth: NotRequired[bool]
    cluster_id: NotRequired[str]
    region: NotRequired[str]


class TextqlRPCPublicConnectorAuroraMetadataAuroraAuth(BaseModel):
    iam_auth: Annotated[Optional[bool], pydantic.Field(alias="iamAuth")] = None

    cluster_id: Annotated[Optional[str], pydantic.Field(alias="clusterId")] = None

    region: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["iamAuth", "clusterId", "region"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorAuroraMetadataAuroraAuth.model_rebuild()
except NameError:
    pass
