"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_cell import (
    TextqlRPCPublicChatCell,
    TextqlRPCPublicChatCellTypedDict,
)
from .textql_rpc_public_dataset_dataset import (
    TextqlRPCPublicDatasetDataset,
    TextqlRPCPublicDatasetDatasetTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicChatAttachDatasetResponseTypedDict(TypedDict):
    cell: NotRequired[TextqlRPCPublicChatCellTypedDict]
    dataset: NotRequired[TextqlRPCPublicDatasetDatasetTypedDict]


class TextqlRPCPublicChatAttachDatasetResponse(BaseModel):
    cell: Optional[TextqlRPCPublicChatCell] = None

    dataset: Optional[TextqlRPCPublicDatasetDataset] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cell", "dataset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
