"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorMicrosoft365MetadataTypedDict(TypedDict):
    tenant_id: NotRequired[str]
    client_id: NotRequired[str]
    client_secret: NotRequired[str]
    access_token: NotRequired[str]
    refresh_token: NotRequired[str]
    member_id: NotRequired[str]
    token_expiry: NotRequired[str]
    metadata_only: NotRequired[bool]
    scopes: NotRequired[List[str]]


class TextqlRPCPublicConnectorMicrosoft365Metadata(BaseModel):
    tenant_id: Annotated[Optional[str], pydantic.Field(alias="tenantId")] = None

    client_id: Annotated[Optional[str], pydantic.Field(alias="clientId")] = None

    client_secret: Annotated[Optional[str], pydantic.Field(alias="clientSecret")] = None

    access_token: Annotated[Optional[str], pydantic.Field(alias="accessToken")] = None

    refresh_token: Annotated[Optional[str], pydantic.Field(alias="refreshToken")] = None

    member_id: Annotated[Optional[str], pydantic.Field(alias="memberId")] = None

    token_expiry: Annotated[Optional[str], pydantic.Field(alias="tokenExpiry")] = None

    metadata_only: Annotated[Optional[bool], pydantic.Field(alias="metadataOnly")] = (
        None
    )

    scopes: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tenantId",
                "clientId",
                "clientSecret",
                "accessToken",
                "refreshToken",
                "memberId",
                "tokenExpiry",
                "metadataOnly",
                "scopes",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorMicrosoft365Metadata.model_rebuild()
except NameError:
    pass
