"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from textql_sdk.types import UnrecognizedStr
from typing import Literal, Union


TextqlRPCPublicPatchesPatchLineOp = Union[
    Literal[
        "PATCH_LINE_OP_CONTEXT",
        "PATCH_LINE_OP_DELETE",
        "PATCH_LINE_OP_ADD",
    ],
    UnrecognizedStr,
]
