"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


TextqlRPCPublicCommonSortDirection = Literal[
    "SORT_DIRECTION_UNKNOWN",
    "SORT_DIRECTION_ASC",
    "SORT_DIRECTION_DESC",
]
r"""Common enum for sort direction used across multiple services"""
