"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_cells_appinfo import (
    TextqlRPCPublicCellsAppInfo,
    TextqlRPCPublicCellsAppInfoTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsListAppsCellTypedDict(TypedDict):
    search_term: NotRequired[str]
    app_id: NotRequired[str]
    r"""\"sql\" | \"python\" """
    total_count: NotRequired[int]
    r"""Produced dataframe name, if applicable"""
    error_message: NotRequired[Nullable[str]]
    r"""SQL only: connector ID; display name resolves client-side"""
    apps: NotRequired[List[TextqlRPCPublicCellsAppInfoTypedDict]]
    r"""SQL only: referenced tables"""


class TextqlRPCPublicCellsListAppsCell(BaseModel):
    search_term: Annotated[Optional[str], pydantic.Field(alias="searchTerm")] = None

    app_id: Annotated[Optional[str], pydantic.Field(alias="appId")] = None
    r"""\"sql\" | \"python\" """

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None
    r"""Produced dataframe name, if applicable"""

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET
    r"""SQL only: connector ID; display name resolves client-side"""

    apps: Optional[List[TextqlRPCPublicCellsAppInfo]] = None
    r"""SQL only: referenced tables"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["searchTerm", "appId", "totalCount", "errorMessage", "apps"]
        )
        nullable_fields = set(["errorMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsListAppsCell.model_rebuild()
except NameError:
    pass
