"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsGoogleDriveContentCellTypedDict(TypedDict):
    file_name: NotRequired[Nullable[str]]
    content_type: NotRequired[Nullable[str]]
    r"""results"""
    content: NotRequired[Nullable[str]]
    file_id: NotRequired[Nullable[str]]
    error_message: NotRequired[Nullable[str]]


class TextqlRPCPublicCellsGoogleDriveContentCell(BaseModel):
    file_name: Annotated[OptionalNullable[str], pydantic.Field(alias="fileName")] = (
        UNSET
    )

    content_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="contentType")
    ] = UNSET
    r"""results"""

    content: OptionalNullable[str] = UNSET

    file_id: Annotated[OptionalNullable[str], pydantic.Field(alias="fileId")] = UNSET

    error_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="errorMessage")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["fileName", "contentType", "content", "fileId", "errorMessage"]
        )
        nullable_fields = set(
            ["fileName", "contentType", "content", "fileId", "errorMessage"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsGoogleDriveContentCell.model_rebuild()
except NameError:
    pass
