"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentialsTypedDict(
    TypedDict
):
    access_key_id: NotRequired[str]
    secret_access_key: NotRequired[str]


class TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentials(BaseModel):
    access_key_id: Annotated[Optional[str], pydantic.Field(alias="accessKeyId")] = None

    secret_access_key: Annotated[
        Optional[str], pydantic.Field(alias="secretAccessKey")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accessKeyId", "secretAccessKey"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorAthenaMetadataAthenaAuthAccessKeyCredentials.model_rebuild()
except NameError:
    pass
