"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesCreateOntologyFileUploadURLResponseTypedDict(TypedDict):
    r"""Counts of the entries a caller may see beneath a subtree. Excludes the subtree
    root itself and reserved names (OWNERS, .gitignore, .DS_Store, .tmp-*), which
    are bookkeeping rather than Ontology content.
    """

    upload_url: NotRequired[str]
    upload_key: NotRequired[str]


class TextqlRPCPublicPatchesCreateOntologyFileUploadURLResponse(BaseModel):
    r"""Counts of the entries a caller may see beneath a subtree. Excludes the subtree
    root itself and reserved names (OWNERS, .gitignore, .DS_Store, .tmp-*), which
    are bookkeeping rather than Ontology content.
    """

    upload_url: Annotated[Optional[str], pydantic.Field(alias="uploadUrl")] = None

    upload_key: Annotated[Optional[str], pydantic.Field(alias="uploadKey")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uploadUrl", "uploadKey"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesCreateOntologyFileUploadURLResponse.model_rebuild()
except NameError:
    pass
