"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicRbacCreatePersonalAPIKeyRequestTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    expiry_seconds: NotRequired[Nullable[int]]
    assumed_roles: NotRequired[List[str]]
    inherit_all_roles: NotRequired[Nullable[bool]]
    client_id: NotRequired[Nullable[str]]
    full_member_access: NotRequired[bool]
    suppress_superadmin: NotRequired[bool]


class TextqlRPCPublicRbacCreatePersonalAPIKeyRequest(BaseModel):
    name: OptionalNullable[str] = UNSET

    expiry_seconds: Annotated[
        OptionalNullable[int], pydantic.Field(alias="expirySeconds")
    ] = UNSET

    assumed_roles: Annotated[
        Optional[List[str]], pydantic.Field(alias="assumedRoles")
    ] = None

    inherit_all_roles: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="inheritAllRoles")
    ] = UNSET

    client_id: Annotated[OptionalNullable[str], pydantic.Field(alias="clientId")] = (
        UNSET
    )

    full_member_access: Annotated[
        Optional[bool], pydantic.Field(alias="fullMemberAccess")
    ] = None

    suppress_superadmin: Annotated[
        Optional[bool], pydantic.Field(alias="suppressSuperadmin")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "expirySeconds",
                "assumedRoles",
                "inheritAllRoles",
                "clientId",
                "fullMemberAccess",
                "suppressSuperadmin",
            ]
        )
        nullable_fields = set(["name", "expirySeconds", "inheritAllRoles", "clientId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicRbacCreatePersonalAPIKeyRequest.model_rebuild()
except NameError:
    pass
