"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_powerbi_powerbidataset import (
    TextqlRPCPublicPowerbiPowerBIDataset,
    TextqlRPCPublicPowerbiPowerBIDatasetTypedDict,
)
from .textql_rpc_public_powerbi_powerbireport import (
    TextqlRPCPublicPowerbiPowerBIReport,
    TextqlRPCPublicPowerbiPowerBIReportTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPowerbiSyncPowerBIItemsRequestTypedDict(TypedDict):
    connector_id: NotRequired[int]
    workspace_id: NotRequired[str]
    workspace_name: NotRequired[str]
    reports: NotRequired[List[TextqlRPCPublicPowerbiPowerBIReportTypedDict]]
    datasets: NotRequired[List[TextqlRPCPublicPowerbiPowerBIDatasetTypedDict]]


class TextqlRPCPublicPowerbiSyncPowerBIItemsRequest(BaseModel):
    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    workspace_id: Annotated[Optional[str], pydantic.Field(alias="workspaceId")] = None

    workspace_name: Annotated[Optional[str], pydantic.Field(alias="workspaceName")] = (
        None
    )

    reports: Optional[List[TextqlRPCPublicPowerbiPowerBIReport]] = None

    datasets: Optional[List[TextqlRPCPublicPowerbiPowerBIDataset]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["connectorId", "workspaceId", "workspaceName", "reports", "datasets"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPowerbiSyncPowerBIItemsRequest.model_rebuild()
except NameError:
    pass
