"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class WorkbookIDTypedDict(TypedDict):
    workbook_id: str
    connector_id: NotRequired[int]


class WorkbookID(BaseModel):
    workbook_id: Annotated[str, pydantic.Field(alias="workbookId")]

    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectorId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ProjectIDTypedDict(TypedDict):
    project_id: str
    connector_id: NotRequired[int]


class ProjectID(BaseModel):
    project_id: Annotated[str, pydantic.Field(alias="projectId")]

    connector_id: Annotated[Optional[int], pydantic.Field(alias="connectorId")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectorId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


TextqlRPCPublicTableauListTableauDatasourcesRequestTypedDict = TypeAliasType(
    "TextqlRPCPublicTableauListTableauDatasourcesRequestTypedDict",
    Union[ProjectIDTypedDict, WorkbookIDTypedDict],
)


TextqlRPCPublicTableauListTableauDatasourcesRequest = TypeAliasType(
    "TextqlRPCPublicTableauListTableauDatasourcesRequest", Union[ProjectID, WorkbookID]
)


try:
    WorkbookID.model_rebuild()
except NameError:
    pass
try:
    ProjectID.model_rebuild()
except NameError:
    pass
