"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicRbacGetRoleRequestTypedDict(TypedDict):
    role_name: NotRequired[str]
    r"""Exact, case-sensitive role name, unique within the caller's organization.
    Supply role_name or role_id.
    """
    role_id: NotRequired[str]
    r"""Existing role ID. Prefer role_name; if both are supplied they must match."""


class TextqlRPCPublicRbacGetRoleRequest(BaseModel):
    role_name: Annotated[Optional[str], pydantic.Field(alias="roleName")] = None
    r"""Exact, case-sensitive role name, unique within the caller's organization.
    Supply role_name or role_id.
    """

    role_id: Annotated[Optional[str], pydantic.Field(alias="roleId")] = None
    r"""Existing role ID. Prefer role_name; if both are supplied they must match."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["roleName", "roleId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicRbacGetRoleRequest.model_rebuild()
except NameError:
    pass
