"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_connectorstatentry import (
    TextqlRPCPublicConnectorConnectorStatEntry,
    TextqlRPCPublicConnectorConnectorStatEntryTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicConnectorGetConnectorStatsResponseTypedDict(TypedDict):
    r"""A segment of an example query message - either plain text or a styled feature word"""

    stats: NotRequired[List[TextqlRPCPublicConnectorConnectorStatEntryTypedDict]]
    r"""The text content of this segment"""


class TextqlRPCPublicConnectorGetConnectorStatsResponse(BaseModel):
    r"""A segment of an example query message - either plain text or a styled feature word"""

    stats: Optional[List[TextqlRPCPublicConnectorConnectorStatEntry]] = None
    r"""The text content of this segment"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stats"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
