"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSandboxCapabilitySandboxPutAssetRequestTypedDict(TypedDict):
    file_name: NotRequired[str]
    content_type: NotRequired[str]
    data: NotRequired[str]


class TextqlRPCPublicSandboxCapabilitySandboxPutAssetRequest(BaseModel):
    file_name: Annotated[Optional[str], pydantic.Field(alias="fileName")] = None

    content_type: Annotated[Optional[str], pydantic.Field(alias="contentType")] = None

    data: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fileName", "contentType", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicSandboxCapabilitySandboxPutAssetRequest.model_rebuild()
except NameError:
    pass
