"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_cellrating import TextqlRPCPublicChatCellRating
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicChatRateChatCellRequestTypedDict(TypedDict):
    chat_id: NotRequired[str]
    cell_id: NotRequired[str]
    rating: NotRequired[TextqlRPCPublicChatCellRating]
    reason: NotRequired[Nullable[str]]
    r"""free-text \"why\" captured from the rating modal"""


class TextqlRPCPublicChatRateChatCellRequest(BaseModel):
    chat_id: Annotated[Optional[str], pydantic.Field(alias="chatId")] = None

    cell_id: Annotated[Optional[str], pydantic.Field(alias="cellId")] = None

    rating: Optional[TextqlRPCPublicChatCellRating] = None

    reason: OptionalNullable[str] = UNSET
    r"""free-text \"why\" captured from the rating modal"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["chatId", "cellId", "rating", "reason"])
        nullable_fields = set(["reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicChatRateChatCellRequest.model_rebuild()
except NameError:
    pass
