"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesUpdateOntologySyncConfigRequestTypedDict(TypedDict):
    sync_enabled: NotRequired[bool]
    sync_interval_minutes: NotRequired[int]


class TextqlRPCPublicPatchesUpdateOntologySyncConfigRequest(BaseModel):
    sync_enabled: Annotated[Optional[bool], pydantic.Field(alias="syncEnabled")] = None

    sync_interval_minutes: Annotated[
        Optional[int], pydantic.Field(alias="syncIntervalMinutes")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["syncEnabled", "syncIntervalMinutes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesUpdateOntologySyncConfigRequest.model_rebuild()
except NameError:
    pass
