"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TextqlRPCPublicPatchesPatchObjectTypedDict(TypedDict):
    r"""PatchObject is one config object parsed from a patch ref."""

    path: NotRequired[str]
    r"""Library path of the file that defines the object"""
    name: NotRequired[str]
    r"""resolved display name"""
    type: NotRequired[str]
    r"""type is the granular object type: \"playbook\", \"dashboard/streamlit\",
    \"dashboard/dash\" (the dashboard subtype is load-bearing for previewability).
    """


class TextqlRPCPublicPatchesPatchObject(BaseModel):
    r"""PatchObject is one config object parsed from a patch ref."""

    path: Optional[str] = None
    r"""Library path of the file that defines the object"""

    name: Optional[str] = None
    r"""resolved display name"""

    type: Optional[str] = None
    r"""type is the granular object type: \"playbook\", \"dashboard/streamlit\",
    \"dashboard/dash\" (the dashboard subtype is load-bearing for previewability).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "name", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
