"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsExaSearchResultTypedDict(TypedDict):
    title: NotRequired[str]
    url: NotRequired[str]
    text: NotRequired[str]
    author: NotRequired[str]
    published_date: NotRequired[str]
    favicon: NotRequired[str]
    image: NotRequired[str]
    score: NotRequired[float]
    highlights: NotRequired[List[str]]
    highlight_scores: NotRequired[List[float]]
    summary: NotRequired[str]


class TextqlRPCPublicCellsExaSearchResult(BaseModel):
    title: Optional[str] = None

    url: Optional[str] = None

    text: Optional[str] = None

    author: Optional[str] = None

    published_date: Annotated[Optional[str], pydantic.Field(alias="publishedDate")] = (
        None
    )

    favicon: Optional[str] = None

    image: Optional[str] = None

    score: Optional[float] = None

    highlights: Optional[List[str]] = None

    highlight_scores: Annotated[
        Optional[List[float]], pydantic.Field(alias="highlightScores")
    ] = None

    summary: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "url",
                "text",
                "author",
                "publishedDate",
                "favicon",
                "image",
                "score",
                "highlights",
                "highlightScores",
                "summary",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsExaSearchResult.model_rebuild()
except NameError:
    pass
