"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from textql_sdk.types import BaseModel
from typing_extensions import Annotated, TypedDict


class TextqlRPCPublicChatCheckStreamlitHealthRequestTypedDict(TypedDict):
    chat_id: str
    cell_id: str


class TextqlRPCPublicChatCheckStreamlitHealthRequest(BaseModel):
    chat_id: Annotated[str, pydantic.Field(alias="chatId")]

    cell_id: Annotated[str, pydantic.Field(alias="cellId")]


try:
    TextqlRPCPublicChatCheckStreamlitHealthRequest.model_rebuild()
except NameError:
    pass
