"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorPostgresMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    database: NotRequired[str]
    schemas: NotRequired[List[str]]
    dialect: NotRequired[str]
    ssl_mode: NotRequired[bool]
    ssh_tunnel_enabled: NotRequired[bool]
    ssh_host: NotRequired[str]
    ssh_port: NotRequired[int]
    ssh_user: NotRequired[str]
    ssh_private_key: NotRequired[str]
    ssh_host_public_key: NotRequired[str]
    secrets_manager_secret_arn: NotRequired[str]
    secrets_manager_role_arn: NotRequired[str]
    secrets_manager_external_id: NotRequired[str]


class TextqlRPCPublicConnectorPostgresMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    database: Optional[str] = None

    schemas: Optional[List[str]] = None

    dialect: Optional[str] = None

    ssl_mode: Annotated[Optional[bool], pydantic.Field(alias="sslMode")] = None

    ssh_tunnel_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="sshTunnelEnabled")
    ] = None

    ssh_host: Annotated[Optional[str], pydantic.Field(alias="sshHost")] = None

    ssh_port: Annotated[Optional[int], pydantic.Field(alias="sshPort")] = None

    ssh_user: Annotated[Optional[str], pydantic.Field(alias="sshUser")] = None

    ssh_private_key: Annotated[Optional[str], pydantic.Field(alias="sshPrivateKey")] = (
        None
    )

    ssh_host_public_key: Annotated[
        Optional[str], pydantic.Field(alias="sshHostPublicKey")
    ] = None

    secrets_manager_secret_arn: Annotated[
        Optional[str], pydantic.Field(alias="secretsManagerSecretArn")
    ] = None

    secrets_manager_role_arn: Annotated[
        Optional[str], pydantic.Field(alias="secretsManagerRoleArn")
    ] = None

    secrets_manager_external_id: Annotated[
        Optional[str], pydantic.Field(alias="secretsManagerExternalId")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "database",
                "schemas",
                "dialect",
                "sslMode",
                "sshTunnelEnabled",
                "sshHost",
                "sshPort",
                "sshUser",
                "sshPrivateKey",
                "sshHostPublicKey",
                "secretsManagerSecretArn",
                "secretsManagerRoleArn",
                "secretsManagerExternalId",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorPostgresMetadata.model_rebuild()
except NameError:
    pass
