"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesDeleteOntologyOwnersRequestTypedDict(TypedDict):
    path: NotRequired[str]
    role_ids: NotRequired[List[str]]
    commit_message: NotRequired[Nullable[str]]


class TextqlRPCPublicPatchesDeleteOntologyOwnersRequest(BaseModel):
    path: Optional[str] = None

    role_ids: Annotated[Optional[List[str]], pydantic.Field(alias="roleIds")] = None

    commit_message: Annotated[
        OptionalNullable[str], pydantic.Field(alias="commitMessage")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "roleIds", "commitMessage"])
        nullable_fields = set(["commitMessage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesDeleteOntologyOwnersRequest.model_rebuild()
except NameError:
    pass
