"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


TextqlRPCPublicDashboardDashboardSortField = Literal[
    "DASHBOARD_SORT_FIELD_UNSPECIFIED",
    "DASHBOARD_SORT_FIELD_NAME",
    "DASHBOARD_SORT_FIELD_CREATED_AT",
    "DASHBOARD_SORT_FIELD_UPDATED_AT",
    "DASHBOARD_SORT_FIELD_REFRESHED_AT",
]
