"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesPatchReviewerTypedDict(TypedDict):
    member_id: NotRequired[str]
    name: NotRequired[str]
    email: NotRequired[str]
    profile_image_url: NotRequired[str]
    is_admin: NotRequired[bool]
    is_code_owner: NotRequired[bool]


class TextqlRPCPublicPatchesPatchReviewer(BaseModel):
    member_id: Annotated[Optional[str], pydantic.Field(alias="memberId")] = None

    name: Optional[str] = None

    email: Optional[str] = None

    profile_image_url: Annotated[
        Optional[str], pydantic.Field(alias="profileImageUrl")
    ] = None

    is_admin: Annotated[Optional[bool], pydantic.Field(alias="isAdmin")] = None

    is_code_owner: Annotated[Optional[bool], pydantic.Field(alias="isCodeOwner")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["memberId", "name", "email", "profileImageUrl", "isAdmin", "isCodeOwner"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesPatchReviewer.model_rebuild()
except NameError:
    pass
