"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicAgentGetAgentDBTablePreviewRequestTypedDict(TypedDict):
    agent_id: NotRequired[str]
    table_name: NotRequired[str]
    limit: NotRequired[int]
    r"""clamped server-side; 0 uses the default"""


class TextqlRPCPublicAgentGetAgentDBTablePreviewRequest(BaseModel):
    agent_id: Annotated[Optional[str], pydantic.Field(alias="agentId")] = None

    table_name: Annotated[Optional[str], pydantic.Field(alias="tableName")] = None

    limit: Optional[int] = None
    r"""clamped server-side; 0 uses the default"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agentId", "tableName", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAgentGetAgentDBTablePreviewRequest.model_rebuild()
except NameError:
    pass
