"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_patches_migrateontologytolibraryresult import (
    TextqlRPCPublicPatchesMigrateOntologyToLibraryResult,
    TextqlRPCPublicPatchesMigrateOntologyToLibraryResultTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicPatchesMigrateOntologyToLibraryResponseTypedDict(TypedDict):
    results: NotRequired[
        List[TextqlRPCPublicPatchesMigrateOntologyToLibraryResultTypedDict]
    ]
    total_created: NotRequired[int]
    total_skipped: NotRequired[int]
    dry_run: NotRequired[bool]


class TextqlRPCPublicPatchesMigrateOntologyToLibraryResponse(BaseModel):
    results: Optional[List[TextqlRPCPublicPatchesMigrateOntologyToLibraryResult]] = None

    total_created: Annotated[Optional[int], pydantic.Field(alias="totalCreated")] = None

    total_skipped: Annotated[Optional[int], pydantic.Field(alias="totalSkipped")] = None

    dry_run: Annotated[Optional[bool], pydantic.Field(alias="dryRun")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["results", "totalCreated", "totalSkipped", "dryRun"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicPatchesMigrateOntologyToLibraryResponse.model_rebuild()
except NameError:
    pass
