"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_secret_apiaccesskey import (
    TextqlRPCPublicSecretAPIAccessKey,
    TextqlRPCPublicSecretAPIAccessKeyTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicSecretUpsertAPIAccessKeyResponseTypedDict(TypedDict):
    api_access_key: NotRequired[TextqlRPCPublicSecretAPIAccessKeyTypedDict]


class TextqlRPCPublicSecretUpsertAPIAccessKeyResponse(BaseModel):
    api_access_key: Annotated[
        Optional[TextqlRPCPublicSecretAPIAccessKey],
        pydantic.Field(alias="apiAccessKey"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apiAccessKey"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicSecretUpsertAPIAccessKeyResponse.model_rebuild()
except NameError:
    pass
