"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_connector_aurorametadata_auroraauth import (
    TextqlRPCPublicConnectorAuroraMetadataAuroraAuth,
    TextqlRPCPublicConnectorAuroraMetadataAuroraAuthTypedDict,
)
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorAuroraMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    database: NotRequired[str]
    schema_: NotRequired[str]
    dialect: NotRequired[str]
    ssl_mode: NotRequired[bool]
    aurora_auth: NotRequired[TextqlRPCPublicConnectorAuroraMetadataAuroraAuthTypedDict]


class TextqlRPCPublicConnectorAuroraMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    database: Optional[str] = None

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = None

    dialect: Optional[str] = None

    ssl_mode: Annotated[Optional[bool], pydantic.Field(alias="sslMode")] = None

    aurora_auth: Annotated[
        Optional[TextqlRPCPublicConnectorAuroraMetadataAuroraAuth],
        pydantic.Field(alias="auroraAuth"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "database",
                "schema",
                "dialect",
                "sslMode",
                "auroraAuth",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorAuroraMetadata.model_rebuild()
except NameError:
    pass
