"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TextqlRPCPublicAgentAgentRunToolCallDurationMsTypedDict = TypeAliasType(
    "TextqlRPCPublicAgentAgentRunToolCallDurationMsTypedDict", Union[int, str]
)


TextqlRPCPublicAgentAgentRunToolCallDurationMs = TypeAliasType(
    "TextqlRPCPublicAgentAgentRunToolCallDurationMs", Union[int, str]
)


StartedAtMsTypedDict = TypeAliasType("StartedAtMsTypedDict", Union[int, str])


StartedAtMs = TypeAliasType("StartedAtMs", Union[int, str])


class TextqlRPCPublicAgentAgentRunToolCallTypedDict(TypedDict):
    tool: NotRequired[str]
    summary: NotRequired[str]
    error: NotRequired[str]
    result_json: NotRequired[str]
    cell_id: NotRequired[str]
    duration_ms: NotRequired[TextqlRPCPublicAgentAgentRunToolCallDurationMsTypedDict]
    started_at_ms: NotRequired[StartedAtMsTypedDict]


class TextqlRPCPublicAgentAgentRunToolCall(BaseModel):
    tool: Optional[str] = None

    summary: Optional[str] = None

    error: Optional[str] = None

    result_json: Annotated[Optional[str], pydantic.Field(alias="resultJson")] = None

    cell_id: Annotated[Optional[str], pydantic.Field(alias="cellId")] = None

    duration_ms: Annotated[
        Optional[TextqlRPCPublicAgentAgentRunToolCallDurationMs],
        pydantic.Field(alias="durationMs"),
    ] = None

    started_at_ms: Annotated[
        Optional[StartedAtMs], pydantic.Field(alias="startedAtMs")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tool",
                "summary",
                "error",
                "resultJson",
                "cellId",
                "durationMs",
                "startedAtMs",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicAgentAgentRunToolCall.model_rebuild()
except NameError:
    pass
