"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicConnectorOracleMetadataTypedDict(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int]
    user: NotRequired[str]
    password: NotRequired[str]
    service_name: NotRequired[str]
    dialect: NotRequired[str]
    ssl_mode: NotRequired[bool]
    connection_type: NotRequired[str]
    sid: NotRequired[str]
    connect_string: NotRequired[str]
    wallet_zip: NotRequired[str]
    r"""Oracle Wallet fields"""
    wallet_password: NotRequired[str]
    tns_alias: NotRequired[str]
    r"""Optional - auto-detected from tnsnames.ora if not provided"""


class TextqlRPCPublicConnectorOracleMetadata(BaseModel):
    host: Optional[str] = None

    port: Optional[int] = None

    user: Optional[str] = None

    password: Optional[str] = None

    service_name: Annotated[Optional[str], pydantic.Field(alias="serviceName")] = None

    dialect: Optional[str] = None

    ssl_mode: Annotated[Optional[bool], pydantic.Field(alias="sslMode")] = None

    connection_type: Annotated[
        Optional[str], pydantic.Field(alias="connectionType")
    ] = None

    sid: Optional[str] = None

    connect_string: Annotated[Optional[str], pydantic.Field(alias="connectString")] = (
        None
    )

    wallet_zip: Annotated[Optional[str], pydantic.Field(alias="walletZip")] = None
    r"""Oracle Wallet fields"""

    wallet_password: Annotated[
        Optional[str], pydantic.Field(alias="walletPassword")
    ] = None

    tns_alias: Annotated[Optional[str], pydantic.Field(alias="tnsAlias")] = None
    r"""Optional - auto-detected from tnsnames.ora if not provided"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "host",
                "port",
                "user",
                "password",
                "serviceName",
                "dialect",
                "sslMode",
                "connectionType",
                "sid",
                "connectString",
                "walletZip",
                "walletPassword",
                "tnsAlias",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicConnectorOracleMetadata.model_rebuild()
except NameError:
    pass
