"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_llmmodel import TextqlRPCPublicChatLlmModel
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicRbacCallerModelAccessTypedDict(TypedDict):
    r"""WhoAmI messages"""

    allowed_models: NotRequired[List[TextqlRPCPublicChatLlmModel]]
    default_model: NotRequired[TextqlRPCPublicChatLlmModel]
    restricted: NotRequired[bool]


class TextqlRPCPublicRbacCallerModelAccess(BaseModel):
    r"""WhoAmI messages"""

    allowed_models: Annotated[
        Optional[List[TextqlRPCPublicChatLlmModel]],
        pydantic.Field(alias="allowedModels"),
    ] = None

    default_model: Annotated[
        Optional[TextqlRPCPublicChatLlmModel], pydantic.Field(alias="defaultModel")
    ] = None

    restricted: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["allowedModels", "defaultModel", "restricted"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicRbacCallerModelAccess.model_rebuild()
except NameError:
    pass
