"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicCellsMicrosoft365EmailContentCellTypedDict(TypedDict):
    email_id: NotRequired[Nullable[str]]
    subject: NotRequired[Nullable[str]]
    sender: NotRequired[Nullable[str]]
    synthetic_tool_use_id: NotRequired[Nullable[str]]


class TextqlRPCPublicCellsMicrosoft365EmailContentCell(BaseModel):
    email_id: Annotated[OptionalNullable[str], pydantic.Field(alias="emailId")] = UNSET

    subject: OptionalNullable[str] = UNSET

    sender: OptionalNullable[str] = UNSET

    synthetic_tool_use_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="syntheticToolUseId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["emailId", "subject", "sender", "syntheticToolUseId"])
        nullable_fields = set(["emailId", "subject", "sender", "syntheticToolUseId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TextqlRPCPublicCellsMicrosoft365EmailContentCell.model_rebuild()
except NameError:
    pass
