"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textql_rpc_public_chat_watchchatevent import (
    TextqlRPCPublicChatWatchChatEvent,
    TextqlRPCPublicChatWatchChatEventTypedDict,
)
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


GenerationTypedDict = TypeAliasType("GenerationTypedDict", Union[int, str])


Generation = TypeAliasType("Generation", Union[int, str])


class TextqlRPCPublicChatPollChatEventsResponseTypedDict(TypedDict):
    events: NotRequired[List[TextqlRPCPublicChatWatchChatEventTypedDict]]
    cursor: NotRequired[str]
    running: NotRequired[bool]
    generation: NotRequired[GenerationTypedDict]


class TextqlRPCPublicChatPollChatEventsResponse(BaseModel):
    events: Optional[List[TextqlRPCPublicChatWatchChatEvent]] = None

    cursor: Optional[str] = None

    running: Optional[bool] = None

    generation: Optional[Generation] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["events", "cursor", "running", "generation"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
