"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from textql_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TextqlRPCPublicDashboardPreviewConfigDashboardRequestTypedDict(TypedDict):
    r"""PreviewConfigDashboard renders a config-managed dashboard from a patch ref before
    merge (ADR-0022). The previewing member + org come from auth context.
    """

    patch_ref: NotRequired[str]
    r"""git ref of the patch to preview from"""
    dashboard_path: NotRequired[str]
    r"""Library path of the .dashboard file"""


class TextqlRPCPublicDashboardPreviewConfigDashboardRequest(BaseModel):
    r"""PreviewConfigDashboard renders a config-managed dashboard from a patch ref before
    merge (ADR-0022). The previewing member + org come from auth context.
    """

    patch_ref: Annotated[Optional[str], pydantic.Field(alias="patchRef")] = None
    r"""git ref of the patch to preview from"""

    dashboard_path: Annotated[Optional[str], pydantic.Field(alias="dashboardPath")] = (
        None
    )
    r"""Library path of the .dashboard file"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["patchRef", "dashboardPath"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TextqlRPCPublicDashboardPreviewConfigDashboardRequest.model_rebuild()
except NameError:
    pass
