workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    TextQL API:
        inputs:
            - location: registry.speakeasyapi.dev/textql/home/textql-api
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/textql/home/textql-api
targets:
    textql:
        target: python
        source: TextQL API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/textql/home/textql-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: true
