#!/usr/bin/env python3
"""Render Speakeasy's RELEASES.md as a Mintlify Python SDK release log."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


FRONTMATTER = """---
title: "Python SDK release log"
description: "Release history for the TextQL Python SDK"
icon: "python"
---

Install the latest release from [PyPI](https://pypi.org/project/textql-sdk/):

```bash
pip install textql-sdk
```
"""

SECTION = re.compile(
    r"^## (?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\s*$",
    re.MULTILINE,
)
PYPI_LINK = re.compile(
    r"\[PyPI v(?P<version>[^\]]+)\](?:\((?P<link_url>https?://[^)]+)\)|\s+(?P<plain_url>https?://\S+))"
)
SPEAKEASY = re.compile(
    r"^- Speakeasy CLI (?P<cli>\S+)(?: \((?P<generator>[^)]+)\))?(?: (?P<url>https?://\S+))?\s*$",
    re.MULTILINE,
)


@dataclass(frozen=True)
class Release:
    published_at: datetime
    version: str
    pypi_url: str
    speakeasy_cli: str | None = None
    generator_version: str | None = None
    speakeasy_url: str | None = None


def parse_releases(markdown: str) -> list[Release]:
    """Parse the release records generated by Speakeasy."""
    matches = list(SECTION.finditer(markdown))
    if not matches:
        raise ValueError("RELEASES.md does not contain any timestamped releases")

    releases: list[Release] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        body = markdown[match.end() : end]
        pypi = PYPI_LINK.search(body)
        if pypi is None:
            raise ValueError(f"release {match.group('timestamp')} has no PyPI link")

        speakeasy = SPEAKEASY.search(body)
        releases.append(
            Release(
                published_at=datetime.strptime(
                    match.group("timestamp"), "%Y-%m-%d %H:%M:%S"
                ),
                version=pypi.group("version"),
                pypi_url=pypi.group("link_url") or pypi.group("plain_url"),
                speakeasy_cli=speakeasy.group("cli") if speakeasy else None,
                generator_version=speakeasy.group("generator") if speakeasy else None,
                speakeasy_url=speakeasy.group("url") if speakeasy else None,
            )
        )
    return releases


def render_release(release: Release) -> str:
    date = (
        f"{release.published_at.strftime('%B')} "
        f"{release.published_at.day}, {release.published_at.year}"
    )
    lines = [
        f'<Update label="v{release.version}" description="{date}">',
        "",
        f"[View `textql-sdk` v{release.version} on PyPI]({release.pypi_url}).",
        "",
        "```bash",
        f"pip install textql-sdk=={release.version}",
        "```",
    ]
    if release.speakeasy_cli:
        label = f"Speakeasy CLI {release.speakeasy_cli}"
        if release.generator_version:
            label += f" (generator {release.generator_version})"
        if release.speakeasy_url:
            lines.extend(["", f"Generated with [{label}]({release.speakeasy_url})."])
        else:
            lines.extend(["", f"Generated with {label}."])
    lines.extend(["", "</Update>"])
    return "\n".join(lines)


def render(markdown: str) -> str:
    releases = sorted(
        parse_releases(markdown),
        key=lambda release: release.published_at,
        reverse=True,
    )
    return FRONTMATTER.rstrip() + "\n\n" + "\n\n".join(
        render_release(release) for release in releases
    ) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Speakeasy RELEASES.md")
    parser.add_argument("destination", type=Path, help="Mintlify MDX output")
    args = parser.parse_args()

    result = render(args.source.read_text())
    args.destination.parent.mkdir(parents=True, exist_ok=True)
    args.destination.write_text(result)
    print(f"Rendered {len(parse_releases(args.source.read_text()))} Python SDK release(s)")


if __name__ == "__main__":
    main()
